### PR TITLE
{tool} [dummy] vsc-mympirun/3.4.3 (REVIEW)

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 1 out of 3 (1 easyconfigs in this PR)
r01i32n2 - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d9a531533ac4dfa3a55e9c22e1b0464b for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
r01i32n2 - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6f5fe4f4fade1d9129736b7b5bca1f1f for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
r01i32n2 - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d5748f462cd10fddab14d8d644aa0c6d for a full test report.

**Comment by boegel** [comment]
@wpoely86 wassup with the failing test reports?

**Comment by boegel** [comment]
@wpoely86 ping?

**Comment by boegel** [comment]
superseded by #4808

**Pull request closed without merging**
