### PR TITLE
{bio} Fix linkage error for Cufflinks 2.0.2 (REVIEW)

### PR DESCRIPTION
**Pull request by wpoely86**
Explicit add linking to boost_system

Fix for #1333

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ff6de20ca81906bdc30c for a full test report.

**Comment by boegel** [comment]
@wpoely86: doesn't seem to break anything on my end (Scientific Linux 6.5)

**Comment by wpoely86** [comment]
@boegel great, you probably would have been hit by this if you were running SL 7.

**Comment by boegel** [comment]
@wpoely86: let me check that...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.0.1406, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/21688e36c4caa3d478e5 for a full test report.

**Comment by boegel** [comment]
@wpoely86: I do indeed run into the same problems as was reported in #1333 on CentOS 7:

```
ld: compress_gtf.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
ld: note: '_ZN5boost6system15system_categoryEv' is defined in DSO /tmp/vsc40023/software/Boost/1.51.0-ictce-5.3.0-Python-2.7.3/lib/libboost_system.so.1.51.0 so try adding it to the linker command line
/tmp/vsc40023/software/Boost/1.51.0-ictce-5.3.0-Python-2.7.3/lib/libboost_system.so.1.51.0: could not read symbols: Invalid operation
make[2]: *** [compress_gtf] Error 1
```

As my last test report show, the changes made in here fix that problem. Nice job!

**Comment by boegel** [comment]
@wpoely86: can you look into submitting a test report for this on Debian? feel free to leave out a particular toolchain if there's too much overhead, should be fine

**Comment by wpoely86** [comment]
Some background information:
- https://fedoraproject.org/wiki/UnderstandingDSOLinkChange
- https://wiki.debian.org/ToolChain/DSOLinking

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 4 out of 7 (1 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/999c16e82cee2bb9f156 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/de632887945428899bd1 for a full test report.

**Comment by boegel** [comment]
@wpoely86: you missing one Cufflinks easyconfig for fixing the `source_urls`: `Cufflinks-2.2.1-intel-2015a.eb` (available in `develop`)

**Comment by boegel** [comment]
Ah, nvm, that one already has the right `source_urls`, my bad..

**Comment by boegel** [comment]
Looking good then, going in. Thanks @wpoely86, and @sylmarien for reporting the issue!

**Pull request merged**
