### PR TITLE
Libxslt-1.1.28 for foss-2016a

### PR DESCRIPTION
**Pull request by RvDijk**
Libxslt for foss 2016a

### CODE REVIEW

**Comment by RvDijk** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

(@RvDijk: I don't mind you talking to our bot, but it only listens to certain 'admins' ;-))

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2054.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/62d66f68aefd52d3b3a95fc208b49cd1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2652.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0e3787b9d19ddbc8fcbadfdec902e9a2 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @RvDijk!

**Comment by RvDijk** [comment]
Thanks @boegel for the tip!

**Pull request merged**
