### PR TITLE
include tk-devel is list of OS deps for Python 2.7.9 Cray easyconfigs, make sure 'import Tkinter' works

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by pforai** [comment]
LGTM!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/c95587456ec4e98cb7a6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/379c6afcd6d41468d276 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pforai!

**Pull request merged**
