### PR TITLE
JDK 1.8.0_66

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**
fixing my errors (push the correct file into the correct branch)...

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@truatpasteurdotfr: it's perfectly fine to combine two (Java) easyconfigs in a single PR btw, no need to separate this one from #2074 (but it's fine as is)

**Comment by truatpasteurdotfr** [comment]
ok, I will do that next time.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c19b6052d3aa223c8bf8 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Going in, thanks @truatpasteurdotfr!

**Pull request merged**
