### PR TITLE
{vis}[intel/2016b] wxPython 3.0.2.0 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node1051.muk.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ba1d81b9ffdddba231f5f7488ae6ae72 for a full test report.

**Comment by hajgato** [comment]
There is a problem with `wxPython`. In the previous version the `$root/lib/python2.7/site-packages/wx-3.0-gtk2` and `$root/lib/python2.7/site-packages/` added  to `PYTHONPATH`, now only `$root/lib/python2.7/site-packages/wx-3.0-gtk2`. I have to investigate. (I suspect the `EasyBlock`, but not sure.

**Comment by hajgato** [comment]
@boegel needs https://github.com/hpcugent/easybuild-easyblocks/pull/1018

**Comment by boegel** [comment]
@hajgato how did you notice this? Is it worth adding a sanity check command to verify this somehow?

**Comment by hajgato** [comment]
@boegel `Python` was able to import `wx`, but not `wxversion`
It popped out when I installed `GRASS`, it compiled without problems, and when I tried to run with X, it complained that `wxversion` is not accessible. (the non-X version was running without a problem)
I do not know how can we make a sanity check for this.

**Comment by boegel** [comment]
@hajgato see https://github.com/hajgato/easybuild-easyblocks/pull/13

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node1373.muk.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/37c925fb39afd23beaf04b1d72974523 for a full test report.

**Comment by boegel** [comment]
retested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/1018, lgtm

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
