### PR TITLE
h5py for Python 3.5 in foss 2016b and h5py for intel 2016b

### PR DESCRIPTION
**Pull request by jhein32**
This is a follow up on the earlier PR #3900 the provides the latest HDF5 versions
1.8.18 and 1.10.0-patch1.  This new PR contains python bindings for Python
3.5 in foss 2016b and Python 2.7 & 3.5 in Intel 2016b

### CODE REVIEW

**Comment by jhein32** [comment]
The "left over stuff" ;)

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2420.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8cbc0731520a75a4647557ac0b1c21de for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2120.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f992d06d9fa948c86032c0f18bfc1881 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jhein32!

**Pull request merged**
