### PR TITLE
add easyconfig file for LAMARC + required patch file

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by JensTimmerman** [comment]
@boegel ok to merge

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/179b9983d84d3a9e4938 for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @JensTimmerman!

**Pull request merged**
