### PR TITLE
{chem} CP2K 3.0 CrayGNU-2015.11-XC 

### PR DESCRIPTION
**Pull request by gppezzi**
- CUDA enabled CP2K requires easyblock https://github.com/hpcugent/easybuild-easyblocks/pull/850
- The CPU version should work with stock cp2k.py

by @lucamar

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
@gppezzi: no test reports yet?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
sisu-login5 - Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/a17a018772d96b6e102c for a full test report.

**Comment by boegel** [comment]
@gppezzi good to go, but I'd like to see some more test reports for this first...

**Comment by gppezzi** [comment]
Test report by @gppezzi
**SUCCESS**
Build succeeded for 8 out of 8 (3 easyconfigs in this PR)
daint102 - Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.6
See https://gist.github.com/9aad0319b1bf7ce3e4b5 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @gppezzi!

**Pull request merged**
