### PR TITLE
{toolchain}[dummy] intel/2016.03-GCC-5.4 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires ~~#3170~~

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 please review

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2515.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d622628d0f81f68bd2581119cc0363fd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2028.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/daadab7ad5a1c723636a776bb8d452ed for a full test report.

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
