### PR TITLE
update FFTW 3.3.5 easyconfigs to use FFTW easyblock & enable running of tests

### PR DESCRIPTION
**Pull request by boegel**
requires ~~https://github.com/hpcugent/easybuild-easyblocks/pull/1083~~

### CODE REVIEW

**Comment by boegel** [comment]
@geimer, @wpoely86 please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2095.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1521ea6fdbb9912f96b81d33719183ba for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2578.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/543ac6950ca4dadf4b4f3a0611d666b7 for a full test report.

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
swatc01 - Linux debian 7.11, Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz, Python 2.7.3
See https://gist.github.com/d7c4deb541e369fe29cde415bf6eac69 for a full test report.

**Comment by boegel** [comment]
@geimer visual review OK too?

**Comment by geimer** [comment]
@boegel Looks good to me, yes. I was trying to also get a test report on POWER, but I somehow managed to mess up my sandbox... :-(

**Comment by boegel** [comment]
@geimer If any issues turn up on POWER, don't hesitate to report them.

Thanks for the review!

**Pull request merged**
