### PR TITLE
{bio} [intel-2015a] Blast 2.2.30 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by hajgato** [comment]
Jenkins approved

**Comment by JensTimmerman** [comment]
blast was renamed blast+
can you please make that change? see https://github.com/hpcugent/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/b/BLAST%2B

**Comment by JensTimmerman** [comment]
see my pull request

**Comment by boegel** [comment]
@JensTimmerman: no need to close this explicitly, it'll be closed automagically when #1473 is merged

**Comment by JensTimmerman** [comment]
I just wanted to make clear to hajgato that I'll look into it.

**Comment by boegel** [comment]
merged via #1474

**Pull request closed without merging**
