### PR TITLE
{numlib} [intel-2015b] CGAL 4.6.3 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
Needs PR ~~#2024~~ ~~#2025~~ ~~#2026~~ ~~#2027~~

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8b620a70e96147791088 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0ec8bfd2e4a0e640f6dd for a full test report.

**Comment by boegel** [comment]
@hajgato: something is broken? Does this easyconfig work for you?

**Comment by hajgato** [comment]
@boegel I suspect that deps were missing, (Qt), but interesting why Jenkins not complained...

**Comment by boegel** [comment]
@hajgato: the Qt dep is there so the Qt module was loaded when building CGAL; something else must be wrong?

**Comment by hajgato** [comment]
@boegel: CMake problem. Does not work with 3.3.2. It does with 2.8.12.2

**Comment by hajgato** [comment]
@boegel  We always bumping CMake versions, maybe we should not follow so tightly CMake evoultion....

**Comment by hajgato** [comment]
@boegel  added `CMake 3.2.3` as builddependency

**Comment by boegel** [comment]
@hajgato: we've seen problems with CMake 3.3 in other places too, seems like they broke something somewhere... 3.2 should be fine indeed

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b34610c218e38c619167 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/81de22f8d6d9c813d963 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
