### PR TITLE
{tools}[dummy/dummy] EasyBuild v2.7.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
boegel.ugent.be - Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz, Python 2.7.10
See https://gist.github.com/c7642ae0acd8ef481e4d for a full test report.

**Comment by fgeorgatos** [comment]
lgtm, reviewed? 

(we'd rather merge this in by the end of the week, when all 2.7.0 feedback has been collected?)
fyi. I've been using 2.7.0 for providing some compilers and it all looks good so far.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
daint103 - Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/915bebc08f1a7bf23329 for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @fgeorgatos!

**Pull request merged**
