### PR TITLE
add EasyABC, lhs, tensorA, shape libraries to R 3.2.1 easyconfigs (+ sync them)

### PR DESCRIPTION
**Pull request by boegel**
(#2067 didn't keep the R 3.2.1 easyconfigs in sync like it should have)

### CODE REVIEW

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/090627752a83676e6332 for a full test report.

**Comment by boegel** [comment]
urgh, ignore the failed test report, I had an `intel` module loaded, which isn't really helpful when building things with different compiler toolchains in the same run :-)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/716057b183c287ef45f7 for a full test report.

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
