### PR TITLE
{lang}[intel/foss/goolf] Python 2.7.9 inetfaces/inetaddr pkgs (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
inspired by the changes to the Python 2.7.9 easyconfig in #1368 by @ehiggs

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0f082abb4b1d92bee26d for a full test report.

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
