### PR TITLE
{toolchain}[dummy] intel/2016a (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/af2edaa24dabe4d368e4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2218426d6e27b8c95305 for a full test report.

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
definition finalised as discussed via EB mailing list and last conf call

tested with Python 2.7.11 (#2337), Perl 5.20.3 (#2336), Boost 1.59.0 (#2351), CMake 3.4.1 (#2343), Bison 3.0.4 + M4 1.4.17 + flex 2.5.39/2.6.0 (#2342)

going in, thanks for the review @wpoely86!

**Pull request merged**
