### PR TITLE
Create CP2K-2.6.0-intel-para-2014.11.eb

### PR DESCRIPTION
**Pull request by ocaisa**
To be used in conjunction with a proposed easyblock that supports MPICH mpi families. 
```runtest = "False"``` is required because our system does not support mpirun (but can be omitted for most others)

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@ocaisa: missing easyconfigs for:

```
Libint/1.1.4-intel-para-2014.12, libxc/2.2.1-intel-para-2014.12, flex/2.5.39-intel-para-2014.12,
Bison/3.0.2-intel-para-2014.12'
```

**Comment by boegel** [comment]
@ocaisa: you'll need an easyconfig for `M4/1.4.17-intel-para-2014.12` too

**Comment by ocaisa** [comment]
Closing and createing a new pull request with everything

**Comment by boegel** [comment]
Not sure why you need a new PR, but fine. :-)

**Comment by boegel** [comment]
replaced by #1471

**Pull request closed without merging**
