### PR TITLE
GStreamer 1.6.4 using the foss 2016a toolchain and the base plugins.

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
GStreamer 1.6.4 built using the foss 2016a toolchain and the GST base plugins.

### CODE REVIEW

**Comment by boegel** [comment]
@FokkeDijkstra missing dep:

```
ERROR: Irresolvable dependencies encountered: GObject-Introspection/1.48.0-foss-2016a
```

**Comment by boegel** [comment]
@FokkeDijkstra one more...

```
EasyBuildError: 'Irresolvable dependencies encountered: cairo/1.14.6-foss-2016a-GLib-2.48.0'
```

**Comment by FokkeDijkstra** [comment]
Is there an easy way to check these dependencies yourself? These easyconfigs have been built earlier and therefore installed on our site. But not everything has been committed as I find out now.

**Comment by boegel** [comment]
@FokkeDijkstra you can check using `--dry-run` or `-D`, while making sure you don't have the path to your own (non-upstream) easyconfigs listed in the robot search path (see `eb --show-config`)

**Comment by FokkeDijkstra** [comment]
@boegel will this not look at already installed modules?

**Comment by boegel** [comment]
@FokkeDijkstra no, all required easyconfig files must be available to build the full dependency graph; only afterwards will it check whether a module is available for each entry in the dep graph, but modules are not used to construct the dep graph

For this PR, all required easyconfigs are included now though...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2646.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0bd4673b9329fd34d0e48a9169124fc2 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2050.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c039510289aef2b525b455e1a11545d0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @FokkeDijkstra!

**Pull request merged**
