### PR TITLE
{bio}[intel/2016a] BioPerl v1.6.924

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

depends on #2540

### CODE REVIEW

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/355125e27132e17ff78b for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Going in, thanks @wpoely86!

**Pull request merged**
