### PR TITLE
get rid of backticks in gettext descriptions, causes problems when packaging with FPM

### PR DESCRIPTION
**Pull request by haribert**
EasyBuild fails to create RPM packages with backticks in the
description. The backticks are not escaped by EasyBuild or fpm.

### CODE REVIEW

**Comment by boegel** [comment]
@rjeschmi can we protect against this in the FPM framework support?

@haribert this cleanup looks good to go once Travis gives the green light, but we should make sure this isn't a problem to begin with; do you have any error messages that we can include here for future reference?

**Comment by haribert** [comment]
@boegel Thank you for your quick response.

The line which indicated that something is wrong with the backticks is the following one:

```
/bin/bash: -c: line 0: unexpected EOF while looking for matching ``'
/bin/bash: -c: line 3: syntax error: unexpected end of file
```

the rest of the log is shown below:

```
== 2017-02-15 16:38:59,066 run.py:433 DEBUG cmd "fpm --workdir /tmp/eb-EJGat0/eb-pkgs-yZfr8F --name "gettext" --provides "gettext" -t rpm -s dir --version 0.19.8 --iteration 170215.centos7 --description "GNU `gettext' is an important step for the GNU Translation Project, as it is an asset on which we may
build many other steps. This package offers to programmers, translators, and even users, a well integrated set of tools
and documentation" --url "http://www.gnu.org/software/gettext/" --exclude "unibas/lcs-software/software/gettext/0.19.8/easybuild/*.log" --exclude "unibas/lcs-software/software/gettext/0.19.8/easybuild/*.md" --debug  --depends "ncurses" /unibas/lcs-software/software/gettext/0.19.8 /unibas/lcs-software/modules/all/gettext/0.19.8.lua" exited with exitcode 1 and output:
/bin/bash: -c: line 0: unexpected EOF while looking for matching ``'
/bin/bash: -c: line 3: syntax error: unexpected end of file

== 2017-02-15 16:38:59,141 build_log.py:147 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd "fpm --workdir /tmp/eb-EJGat0/eb-pkgs-yZfr8F --name "gettext" --provides "gettext" -t rpm -s dir --version 0.19.8 --iteration 170215.centos7 --description "GNU `gettext' is an important step for the GNU Translation Project, as it is an asset on which we may
build many other steps. This package offers to programmers, translators, and even users, a well integrated set of tools
and documentation" --url "http://www.gnu.org/software/gettext/" --exclude "unibas/lcs-software/software/gettext/0.19.8/easybuild/*.log" --exclude "unibas/lcs-software/software/gettext/0.19.8/easybuild/*.md" --debug  --depends "ncurses" /unibas/lcs-software/software/gettext/0.19.8 /unibas/lcs-software/modules/all/gettext/0.19.8.lua" exited with exitcode 1 and output:
/bin/bash: -c: line 0: unexpected EOF while looking for matching ``'
/bin/bash: -c: line 3: syntax error: unexpected end of file
 (at easybuild/tools/run.py:438 in parse_cmd_output)
== 2017-02-15 16:38:59,141 easyblock.py:2499 WARNING build failed (first 300 chars): cmd "fpm --workdir /tmp/eb-EJGat0/eb-pkgs-yZfr8F --name "gettext" --provides "gettext" -t rpm -s dir --version 0.19.8 --iteration 170215.centos7 --description "GNU `gettext' is an important step for the GNU Translation Project, as it is an asset on which we may
build many other steps. This package o
== 2017-02-15 16:38:59,142 easyblock.py:276 INFO Closing log for application name gettext version 0.19.8
== 2017-02-15 16:38:59,142 easyblock.py:276 INFO Closing log for application name gettext version 0.19.8
== 2017-02-15 16:38:59,142 build_log.py:216 INFO FAILED: Installation ended unsuccessfully (build directory: /opt/easybuild/.local/easybuild/build/gettext/0.19.8/dummy-): build failed (first 300 chars): cmd "fpm --workdir /tmp/eb-EJGat0/eb-pkgs-yZfr8F --name "gettext" --provides "gettext" -t rpm -s dir --version 0.19.8 --iteration 170215.centos7 --description "GNU `gettext' is an important step for the GNU Translation Project, as it is an asset on which we may
build many other steps. This package o
== FAILED: Installation ended unsuccessfully (build directory: /opt/easybuild/.local/easybuild/build/gettext/0.19.8/dummy-): build failed (first 300 chars): cmd "fpm --workdir /tmp/eb-EJGat0/eb-pkgs-yZfr8F --name "gettext" --provides "gettext" -t rpm -s dir --version 0.19.8 --iteration 170215.centos7 --description "GNU `gettext' is an important step for the GNU Translation Project, as it is an asset on which we may
build many other steps. This package o
== 2017-02-15 16:38:59,143 build_log.py:216 INFO Results of the build can be found in the log file(s) /tmp/eb-EJGat0/easybuild-gettext-0.19.8-20170215.163232.rkoHj.log
== Results of the build can be found in the log file(s) /tmp/eb-EJGat0/easybuild-gettext-0.19.8-20170215.163232.rkoHj.log
== 2017-02-15 16:38:59,144 build_log.py:147 ERROR EasyBuild crashed with an error (at ?:124 in __init__): build failed (first 300 chars): cmd "fpm --workdir /tmp/eb-EJGat0/eb-pkgs-yZfr8F --name "gettext" --provides "gettext" -t rpm -s dir --version 0.19.8 --iteration 170215.centos7 --description "GNU `gettext' is an important step for the GNU Translation Project, as it is an asset on which we may
build many other steps. This package o (at easybuild/main.py:118 in build_and_install_software)
== 2017-02-15 16:38:59,145 filetools.py:995 DEBUG Not creating existing path /tmp/eb-EJGat0
== 2017-02-15 16:38:59,146 build_log.py:147 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Build of /opt/easybuild/easyconfig/css-lcs-dev-easybuild-reviewed-dependencies/gettext/gettext-0.19.8.eb failed (err: 'build failed (first 300 chars): cmd "fpm --workdir /tmp/eb-EJGat0/eb-pkgs-yZfr8F --name "gettext" --provides "gettext" -t rpm -s dir --version 0.19.8 --iteration 170215.centos7 --description "GNU `gettext\' is an important step for the GNU Translation Project, as it is an asset on which we may\nbuild many other steps. This package o') (at easybuild/main.py:150 in build_and_install_software)
ERROR: Build of /opt/easybuild/easyconfig/css-lcs-dev-easybuild-reviewed-dependencies/gettext/gettext-0.19.8.eb failed (err: 'build failed (first 300 chars): cmd "fpm --workdir /tmp/eb-EJGat0/eb-pkgs-yZfr8F --name "gettext" --provides "gettext" -t rpm -s dir --version 0.19.8 --iteration 170215.centos7 --description "GNU `gettext\' is an important step for the GNU Translation Project, as it is an asset on which we may\nbuild many other steps. This package o')
```

**Comment by boegel** [comment]
Thanks for the extra info @haribert!

This is good to go, we'll try and look into a proper fix for this in the EasyBuild framework too.
@rjeschmi Maybe open an issue on this to avoid forgetting about it?

**Comment by rjeschmi** [comment]
We have an issue in framework too

https://github.com/hpcugent/easybuild-framework/issues/2014

I'll try to look at this today...

**Pull request merged**
