### PR TITLE
New Easyconfig for ORCA 3.0.3

### PR DESCRIPTION
**Pull request by scintimandrion**

### CODE REVIEW

**Comment by scintimandrion** [comment]
Yes.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e3819b4dbf0a2f3137fc for a full test report.

**Comment by boegel** [comment]
Looks good, works like a charm, going in. Thanks @scintimandrion!

**Pull request merged**
