### PR TITLE
Contrib GATK v.3.0.0

### PR DESCRIPTION
**Pull request by tloizou**
Contributing GATK version 3.0.0

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by ocaisa** [comment]
style review ok

**Comment by ocaisa** [comment]
Hmm, it's no longer possible to download the version of java listed in the eb. Can we change it to 1.7.0_80?

**Comment by boegel** [comment]
Bumping Java version makes sense, but I have the 1.7.0_10 tarball on my end, so I'm fine either way.

@tloizou: let me know how you'll handle this

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/16a8ede898a839862ab6 for a full test report.

**Comment by tloizou** [comment]
@boegel: We can leave it as is then. Maybe I can try at some point to install a newer GATK version with the latest Java version.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7e760500de285d94510f for a full test report.

**Comment by boegel** [comment]
Please ignore the failed test reports, I seem to have misplaced the tarball...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4bdbcb7dce9256c323a0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8fc2c3b6591e1307fbfe for a full test report.

**Comment by boegel** [comment]
Going in, thanks @tloizou!

**Pull request merged**
