### PR TITLE
{math}[foss/2016a]OBITools-1.2.9

### PR DESCRIPTION
**Pull request by RvDijk**

### CODE REVIEW

**Comment by RvDijk** [comment]
Dependency on #3387

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2413.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d921c61743dd613554397a26f199f970 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2098.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6e97bf0bdebc1b24f3a25b3f9e1f7ab9 for a full test report.

**Comment by RvDijk** [comment]
@boegel ignore close, I was a bit to enthusiastic with deleting the branch..

**Comment by boegel** [comment]
Going in, thanks @RvDijk!

**Pull request merged**
