### PR TITLE
SAMtools-1.4-goolf-1.4.10.eb and ncurses-6.0-goolf-1.4.10.eb

### PR DESCRIPTION
**Pull request by danielnavarrogomez**
Added SAMtools-1.4-goolf-1.4.10.eb and ncurses-6.0-goolf-1.4.10.eb, the second one is a dependece of the first. By Daniel Navarro-Gomez, MEEI Bioinformatics Center

	new file:   easyconfigs/n/ncurses/ncurses-6.0-goolf-1.4.10.eb
	new file:   easyconfigs/s/SAMtools/SAMtools-1.4-goolf-1.4.10.eb

### CODE REVIEW

**Comment by boegel** [comment]
@danielnavarrogomez Any particular reason you are (still) using this quite old toolchain?

**Comment by danielnavarrogomez** [comment]
This is the one that I use for my production pipeline (old), will be updated soon, but I need compatibility meanwhile.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2001.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9630e3649942c90a3c69d456df7073d3 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @danielnavarrogomez!

**Pull request merged**
