### PR TITLE
libXaw 1.0.12 goolf 1.5.14

### PR DESCRIPTION
**Pull request by valtandor**
New easyconfigs for libXaw-1.0.12 with the goolf-1.5.14 toolchain, along with various dependencies.

### CODE REVIEW

**Comment by JensTimmerman** [comment]
jenkins: ok to test
@valtandor0 can you rebase this on top of master?

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
`easyblock = 'ConfigureMake'` missing in several places

**Comment by valtandor** [comment]
If by rebasing you mean merging from develop then pushing the result up, I've just done that.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 12 out of 13 (13 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a97f70da7f0b96b4ce89 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e98e6c2d7a6ca5f9dd5c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
