### PR TITLE
{system}[foss/2016b,intel/2016b] libpciaccess v0.13.4, libpciaccess v0.13.4

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2585.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/bb39d05cf1aa5541aabe4a9c2e1c4b82 for a full test report.

**Comment by verdurin** [comment]
depends on #4030

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2005.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7f1a9519f9099cb66760ae45886810ad for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
