### PR TITLE
fix Xmipp easyconfigs: naming, patches, deps + add foss/2015a equivalent

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-easyblocks/pull/630

### CODE REVIEW

**Comment by boegel** [comment]
@JensTimmerman: please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux RHEL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1b48d70a499699616b67 for a full test report.

**Comment by JensTimmerman** [comment]
fine by me

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
Linux RHEL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/53c49f48271334c5cfb6 for a full test report.

**Comment by boegel** [comment]
`intel/2015a` build in failed test report failed due to issue with Intel compiler license, retrying...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux RHEL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/40b44cb8a56e9e806c00 for a full test report.

**Comment by boegel** [comment]
Good to go now https://github.com/hpcugent/easybuild-easyblocks/pull/630 is merged in.

Thanks for the review @JensTimmerman!

**Pull request merged**
