### PR TITLE
Update molmod and matplotlib for Python 2.7.9 intel 2015a.

### PR DESCRIPTION
**Pull request by ehiggs**

### CODE REVIEW

**Comment by JensTimmerman** [comment]
is there a reason not to bump to python 2.7.10 ?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d1fcd72df282b76d41dc for a full test report.

**Comment by ehiggs** [comment]
I added 2.7.10 as well.

**Comment by boegel** [comment]
Looks fine.

@JensTimmerman: these are missing deps for something else, where Python 2.7.9 is already used, updating to Python 2.7.10 would require touching more easyconfigs (and is trivial anyway).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/808fa25e114b9372da27 for a full test report.

**Comment by boegel** [comment]
Thanks @ehiggs!

**Pull request merged**
