### PR TITLE
{math}[intel/2016b] Octave 4.0.3 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
Needs PRs ~~#3704 #3705 #3706 #3707 #3708 #3709 #3710 #3711 #3712 #3713 #3714 #3715 #3716~~
Replaces #2684 and #2766

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2110.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/52379a2d2c66f0a0a60630570bfe1f8f for a full test report.

**Comment by boegel** [comment]
@hajgato doesn't seem to work for me (even though I rebuilt FLTK using the update from #3704)...

Any ideas?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2301.phanpy.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/73929807972050eb4c80d4a56d04976a for a full test report.

**Comment by hajgato** [comment]
@boegel: It is exactly the same problem than before. 
I will not be able to solve this problem, unless I will get access to the node that having the problem.
For some reason, wrong version of `moc` is used.

**Comment by hajgato** [comment]
@boegel: I have to see all the logs, (including config log, etc). It is a quite annoying problem.

**Comment by hajgato** [comment]
@boegel: It seems that I might found a solution. Can you check this?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2078.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/005c00d947b1afb1659217c06970b33e for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in this PR)
node2301.phanpy.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6b97dd244769206b196c93b1d3bb6e23 for a full test report.

**Comment by boegel** [comment]
@hajgato same problem as in #2766, the actual *error* is:

```
error: <prefix>/software/Octave/4.0.3-intel-2016b/lib/octave/4.0.3/oct/x86_64-pc-linux-gnu/PKG_ADD:
<prefix>/software/Octave/4.0.3-intel-2016b/lib/octave/4.0.3/oct/x86_64-pc-linux-gnu/__init_fltk__.oct: failed to load:
 <prefix>/software/FLTK/1.3.3-intel-2016b/lib/libfltk_gl.so.1.3: undefined symbol: _ZN18Fl_XFont_On_Demand5valueEv
error: called from
    /user/data/gent/vsc400/vsc40023/tmp/CO7/haswell/software/Octave/4.0.3-intel-2016b/lib/octave/4.0.3/oct/x86_64-pc-linux-gnu/PKG_ADD at line 3 column 1
```

looks like a missing dep?

**Comment by hajgato** [comment]
@boegel lest solve this problem first, then we will go back to PR #2766 .

**Comment by hajgato** [comment]
The `undefined symbol: _ZN18Fl_XFont_On_Demand5valueEv` is an `FLTK` problem, this supposed to handled by PR #3704. see for example:
https://bugzilla.redhat.com/show_bug.cgi?id=1160251
https://groups.google.com/forum/#!topic/fltkgeneral/GT6i2KGCb3A
http://www.fltk.org/str.php?L3156

If this problem is not handled by that FLTK patch, then `Octave` does not use `EasyBuild` `FLTK`. 
Did you used recompiled `FLTK` from PR #3704? 
if Yes, can you check what `FLTK` was used for compilation? And for the run time?

**Comment by hajgato** [comment]
@boegel ^

**Comment by boegel** [comment]
@hajgato you're right, it works fine after making sure that `FLTK` is rebuilt using the patch added in #3704, my apologies...

Test reports coming up, merge is imminent, thanks for all the effort!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2301.phanpy.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5635a7019deae77a5443aa538df73cf7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node1001.muk.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f9a82d93b372c4bb5119ada02da65e73 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
