### PR TITLE
CUDA 6.5.14

### PR DESCRIPTION
**Pull request by hajgato**
needs https://github.com/hpcugent/easybuild-easyblocks/pull/476

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
I submitted a test job for this, but it seems like it was hanging:

```
Job exceeded its walltime limit. Job was aborted
```

@hajgato: can you try submitting a test report for this one?

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux opensuse 13.1, Intel(R) Xeon(R) CPU           W3530  @ 2.80GHz, Python 2.7.6
See https://gist.github.com/ea43433bf6559d1282e5 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux opensuse 13.1, Intel(R) Xeon(R) CPU           W3530  @ 2.80GHz, Python 2.7.6
See https://gist.github.com/c862aa38907252d16f6a for a full test report.

**Comment by hajgato** [comment]
@boegel Test report uploaded to https://gist.github.com/c862aa38907252d16f6a
do not forget https://github.com/hpcugent/easybuild-easyblocks/pull/476

**Comment by boegel** [comment]
@hajgato: for some reason, this fails on my end:

```
== 2015-06-02 20:00:13,218 main.run DEBUG run_cmd: running cmd /bin/sh /user/data/gent/vsc400/vsc40023/EasyBuild/sources/c/CUDA/cuda_6.5.14_linux_64.run --noexec --nox11 --target /tmp/vsc40023/easybuild_build/CUDA/6.5.14/dummy-dummy (in /vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40023)
Extraction failed.
Ensure there is enough space in /tmp/eb-FYoPyj and that the installation package is not corrupt
/gpfs/scratch/users/vsc400/vsc40023/easybuild_easy_installed/bin/eb: line 86: 49932 Killed                  python $easybuild_main $@
```

I noticed similar issues with #877, not sure why I'm the only one seeing this, very weird...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a41f7631252f29a7e463 for a full test report.

**Comment by boegel** [comment]
@hajgato: thanks for adding the MD5sum, it seemed like my download was corrupt, indeed

I'm now running into a failed sanity check, because I wasn't using https://github.com/hpcugent/easybuild-easyblocks/pull/476, will fix.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6b51811efbdd46e3cc62 for a full test report.

**Comment by boegel** [comment]
Tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/476, together with all existing CUDA easyconfigs (to test changed easyblock).

Looking good, thanks @hajgato!

**Pull request merged**
