### PR TITLE
add custom sanity check for libjpeg-turbo

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 21 out of 21 (21 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/48dbb5095ee5b07d366c for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review? should be good to go...

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
