### PR TITLE
add easyconfig for WPS v3.6.1 with intel/2014b

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fbe3669c7c6ded35945e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2050.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8eec749504c7aebe318b1026908ac151 for a full test report.

**Comment by hajgato** [comment]
@boegel The test fails, for some reason `Intel MPI` does not able to fire up `mpd`, so `mpirun` or `mpiexec` does not work.

**Comment by boegel** [comment]
@hajgato: the problem is mostly related to the toolchain, rather than WPS itself... I should probably just bump the toolchain.

**Comment by boegel** [comment]
closing this in favour of https://github.com/hpcugent/easybuild-easyconfigs/pull/3391

**Pull request closed without merging**
