### PR TITLE
{bio}[foss/2016b] SPAdes v3.10.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Minor version bump, other than also including `Boost` as a build dependency.

It seems like SPAdes only requires the Boost include files, it doesn't actually link to the Boost libraries?

@verdurin please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2455.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4d406173a51727ced1d51dd8d126f695 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2151.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b38176e8be6738c3e9ea76f112dbb64a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2455.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/77a29ce157f10707f9b9013b336a4698 for a full test report.

**Comment by boegel** [comment]
@verdurin Thanks for the feedback!

Is there any reason you didn't include Boost as a (build) dependency in the `SPAdes` easyconfigs you contributed earlier, or do you have a Boost version installed in the OS that made you miss the requirement?

Also, have you tried building `SPAdes` with the Intel compilers by any chance? I had to struggle with it quite a bit, and although I got it to compile now, it segfaults on the `spades.py --test` sanity check command...

**Comment by verdurin** [comment]
@boegel - think I inherited the lack of `Boost` from the older versions. Some Boost RPMs are installed, but not the headers, so I can only assume it wasn't required in 3.9.x?

I see they don't mention it in the manual, either. Tsk.

Haven't tried with Intel yet.

**Comment by boegel** [comment]
@verdurin `SPAdes` ships a very old Boost version (1.51.0), so I'm now in doubt whether including our own Boost dependency is actually wise, especially taking into account the large difference in Boost version...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2458.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/146d3e3fc6605f54eb3b4d57c2a1a01d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2141.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c54e2b79f2dfa050abb1108dd617c20a for a full test report.

**Comment by boegel** [comment]
@verdurin I kicked out the Boost (build) dep, it's probably wiser to go with the included Boost in this case...

**Comment by boegel** [comment]
Thanks for the review @verdurin!

**Pull request merged**
