### PR TITLE
argparse is part of the Python standard library as of 3.2

### PR DESCRIPTION
**Pull request by ocaisa**
cfr. https://docs.python.org/3/library/argparse.html

### CODE REVIEW

**Comment by wpoely86** [comment]
test this please

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for looking into this @ocaisa!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1ea30072a7337dcd1e04 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
