### PR TITLE
{lang} [foss/2015a]  R 3.1.3 (REVIEW)

### PR DESCRIPTION
**Pull request by tmwsiy2012**
First draft for R-3.1.3-foss-2015a.eb just updated bioconductor extensions.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@tmwsiy2012: thanks a lot for tackling this. We should look into updating all library versions. This can be pretty painful, but it's scriptable.

**Comment by boegel** [comment]
@tmwsiy2012: I'm looking into bumping all versions of extensions, PR coming your way in a bit...

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d4025af7f3c7b591a1c3 for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9fe8fad51a4ffa952713 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/626f0b8f994cdf747613 for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 8 out of 20 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/462c6d3c9cea33d53a58 for a full test report.

**Comment by boegel** [comment]
@pescobar: OpenMPI failed with `configure: WARNING: Verbs support requested (via --with-verbs) but not found.`

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 18 out of 20 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/e1889d8ba8b655845507 for a full test report.

**Comment by boegel** [comment]
this needs https://github.com/tmwsiy2012/easybuild-easyconfigs/pull/2 since `AnnotationDbi` was updated and the previous version is no longer available (yes, that again)

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/53e4a5a7571b6738d393 for a full test report.

**Pull request merged**
