### PR TITLE
{lang}[intel/2016a] Perl 5.22.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
with updated extension versions

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2668.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bd45c4a0ba1a98e230c9 for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2090.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2ec396f33bdbb5891d5a for a full test report.

**Pull request merged**
