### PR TITLE
fix bioconductor extension versions in R 3.1.3 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato, @pescobar: please review?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/974f7233db0d5cb7b7c3 for a full test report.

**Comment by hajgato** [comment]
extra ampty line https://github.com/hpcugent/easybuild-easyconfigs/pull/1748/files#diff-67634fc895510c2b96cbdf0cc5e7329dR392

**Comment by hajgato** [comment]
@boegel Is that up tp date?
https://github.com/hpcugent/easybuild-easyconfigs/pull/1748/files#diff-67634fc895510c2b96cbdf0cc5e7329dR50

**Comment by hajgato** [comment]
@bogel Is that up to date?
https://github.com/hpcugent/easybuild-easyconfigs/pull/1748/files#diff-18c808ccf7740cefd1d25b372be7a4bcR50

**Comment by hajgato** [comment]
@boegel: otherwise it looks fine for me.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/83f16f9a66c09038ba1f for a full test report.

**Comment by boegel** [comment]
Thanks for the review @hajgato!

**Pull request merged**
