### PR TITLE
add easyconfigs for ATSAS

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by verdurin** [comment]
I would be interested in this one. 

Upstream is now at 2.7.1.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@verdurin: do the ones provided here work for you?

**Comment by verdurin** [comment]
@boegel - I've submitted #2587 which is an update to the latest upstream and works in local testing.

Feel free to just update this one with changes from there.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/cb22eb3b5c288886c35b for a full test report.

**Comment by boegel** [comment]
Considering this reviewed through #2587 by @verdurin, thanks!

**Pull request merged**
