### PR TITLE
{toolchain} intel/2015b (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
depends on ~~#1836~~ (GNU)

**note**: do *not* consider the definition of this common toolchain final until the PR is merged!

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@wpoely86, @gjbex, @backelj, @hajgato: please test?

**Comment by backelj** [comment]
Test report by @backelj
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/ad08392619780c1a9c48 for a full test report.

**Comment by boegel** [comment]
@backelj: enable `--robot`, it will tell you what's missing

**Comment by backelj** [comment]
Test report by @backelj
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/22f5686e6fef0e5c1590 for a full test report.

**Comment by backelj** [comment]
@boegel: oops, missing the Intel sources... where can I find them?

**Comment by boegel** [comment]
@backelj: you'll need to put the sources in place...

**Comment by boegel** [comment]
@backelj: you'll need to download them manually from Intel, requires an active license, etc, etc.

**Comment by backelj** [comment]
Test report by @backelj
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/5516e4390513569b1c99 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 7 out of 15 (8 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/79e49e773e979899bcfb for a full test report.

**Comment by boegel** [comment]
@hajgato: you need to make sure `$INTEL_LICENSE_FILE` is defined (correctly)

**Comment by hajgato** [comment]
@boegel This is what I always forget...

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 15 out of 15 (8 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/bfdc811e621bafa1084c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/90189d1d542e92218ce8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/7971b38e427b760204cc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/d04b7502f36c4101a5c1 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux debian 8.1, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/4d6f30d5d6866e470e52 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/cbb8332e6d5dca9a6e03 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/ff917cf6a8875abafb93 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/53f92bcd90efb2118d6f for a full test report.

**Comment by backelj** [comment]
I'm still in France at this moment. I will test it as soon as I'm back, in the week of August 24...
________________________________
Van: Kenneth Hoste<mailto:notifications@github.com>
Verzonden: ‎9/‎08/‎2015 22:35
Aan: hpcugent/easybuild-easyconfigs<mailto:easybuild-easyconfigs@noreply.github.com>
CC: Backeljauw Franky<mailto:franky.backeljauw@uantwerpen.be>
Onderwerp: Re: [easybuild-easyconfigs] {toolchain} intel/2015b (REVIEW) (#1696)


Test report by @boegel<https://github.com/boegel>
SUCCESS
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/53f92bcd90efb2118d6f for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/9c3fccaaa571657ec908 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 5 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/0f92f3fc0a2476e77cb4 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 5 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/72644887b135fa8dce2e for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@hajgato: a fix for the issue you were running into has been merged into easybuild-easyblocks `develop`, see https://github.com/hpcugent/easybuild-easyblocks/pull/660

Can you update and retry testing this PR on top of that?

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/9ebe124e926ba808ad78 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/bc08caeaf08defa59357 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/2bc13067f5c2f37a5832 for a full test report.

**Comment by boegel** [comment]
Good to go after extensive testing, thanks to all who helped with reviewing/testing!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1dd1d4a96705efcc262d for a full test report.

**Pull request merged**
