### PR TITLE
add missing /gnu/ ins ftpmirror.gnu.org source_urls, or use GNU_SOURCE where possible

### PR DESCRIPTION
**Pull request by boegel**
fix for https://github.com/hpcugent/easybuild-framework/issues/2233

### CODE REVIEW

**Comment by boegel** [comment]
@migueldiascosta please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 75 out of 75 (73 easyconfigs in this PR)
node2032.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cf0ff88d1d78ae01c84bcc3f315b1027 for a full test report.

**Comment by boegel** [comment]
I had to seed in the source for ed v1.9 since `ed-1.9.tar.gz` is no longer available at ftpmirror.gnu.org/gnu/ed/...

It is still available at https://launchpad.net/ed though, shall we include that as an alternate source URL?

**Comment by migueldiascosta** [comment]
weird (what happened between 2009/1.4 and 2015/1.11?)

regarding launchpad, sure, as long as there is a checksum any source will do, no?

**Comment by migueldiascosta** [comment]
what about adding templates for `http://ftpmirror.gnu.org/gnu/%(namelower)s`, `http://ftpmirror.gnu.org/gnu/%(namelower)s/%(namelower)s-%(version)s`, ... ?

**Comment by boegel** [comment]
@migueldiascosta We have a template for `http://ftpmirror.gnu.org/gnu/%(namelower)s`, i.e. `GNU_SOURCE`.
The one that includes `%(name)s-%(version)s` is specific to GCC, not sure it's worth the trouble to add a template just for GCC?

**Comment by migueldiascosta** [comment]
@boegel I must have missed something, isn't GNU_SOURCE without /gnu? 

In any case, looks good to me

**Comment by boegel** [comment]
@migueldiascosta The `/gnu/` should be there, see https://github.com/hpcugent/easybuild-framework/pull/2235... :)

**Comment by migueldiascosta** [comment]
:) ok - the explicit gmp, mpfr and coreutils I understand, but why can't GSL use the new GNU_SOURCE then?

**Comment by boegel** [comment]
Tested on top of https://github.com/hpcugent/easybuild-framework/pull/2235 (to check that the fixed `GNU_SOURCE` is indeed correct). Good to go as soon as Travis agrees...

**Comment by boegel** [comment]
Thanks for the review @migueldiascosta!

**Comment by CJCShadowsan** [comment]
Holy thread revival Batman!

It appears that whilst building easyconfigs/n/ncurses/ncurses-6.5-GCCcore-13.3.0.eb - It attempts to download from https://ftpmirror.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz which fails repeatedly... 

...Downloading from https://ftp.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz works first time.

Does this need changing now?

**Comment by CJCShadowsan** [comment]
> Holy thread revival Batman!
> 
> It appears that whilst building easyconfigs/n/ncurses/ncurses-6.5-GCCcore-13.3.0.eb - It attempts to download from https://ftpmirror.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz which fails repeatedly...
> 
> ...Downloading from https://ftp.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz works first time.
> 
> Does this need changing now?

This also now breaks on easyconfigs/m/make/make-4.4.1-GCCcore-13.3.0.eb which tries to get make from:  https://ftpmirror.gnu.org/gnu/make/make-4.4.1.tar.gz - Which also fails.

**Pull request merged**
