### PR TITLE
Check-0.9.12-goolf-1.4.10.eb

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**SUCCESS**
Build succeeded for 1 out of 1
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/264a69272e9b5e57e283 for a full test report.

**Comment by JensTimmerman** [comment]
@boegel this looks good to go

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@pescobar: missing `easyblock = 'ConfigureMake'`

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/76d867839a0c479af391 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pescobar!

**Pull request merged**
