### PR TITLE
correctly set $PYTHONPATH for ROOT v6.06.x

### PR DESCRIPTION
**Pull request by ysagon**

### CODE REVIEW

**Comment by boegel** [comment]
@ysagon I would have been easier to update `$PYTHONPATH` in all the ROOT easyconfigs in a single PR, but fine. ;-)

**Comment by ysagon** [comment]
@boegel yes sure, I wasn't sure if it was ok for travis to do that. I'll do like that next time:)

**Comment by boegel** [comment]
@ysagon It's a lot better for Travis, since now it has to run the easyconfigs unit test suite multiple times (once for each PR).

It may complicate test reports a bit because of the mix of toolchains in a single PR, that's true, but here we don't need to redo the full installation (just regenerate the module & redo the sanity check).

Anyway, it's not a *big* issue, just results in some overhead/bookkeeping.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
node2569.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3918ac74e935949a1738e3cbe32ff67e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2569.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0244ae78671b2e36e01947b91026320a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2054.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/28eb9335d04282b581a218ad4e114cc0 for a full test report.

**Comment by boegel** [comment]
This one is good to go, as soon as Travis approves...

**Pull request merged**
