### PR TITLE
{bio} [foss-2015b,2016a] BEDTools-2.25.0

### PR DESCRIPTION
**Pull request by verdurin**
Simple port of `2.25.0` to `foss-2015b` and `foss-2016a`

### CODE REVIEW

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
maraba - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.7.11
See https://gist.github.com/8459d37488dade4d84c7f273642ff21e for a full test report.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2140.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e5ff40a4555296a25dbc42e5771467a2 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
