### PR TITLE
add easyconfig file for GAMESS-US 2014.12.05-R1, including patch to make rungms work with SLURM

### PR DESCRIPTION
**Pull request by boegel**
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/558

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/55b0afadf2a858847b89 for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/fc789e4286f5f27d47ce for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c3e6ad3fb63f4a58764f for a full test report.

**Comment by boegel** [comment]
@pescobar: using `ictce/6.2.5`, one of the included tests fails for me:

```
exam42: Eerr=5.8e-03 Gerr=0.0e+00.                                     !!FAILED.
```

with `intel/2015a`, all is well...

So, I think I'll kick out the ictce/6.2.5 easyconfig again, seems like there may be a compiler bug. Let's see what your test brings up...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/47ca31de48b8a2724416 for a full test report.

**Comment by boegel** [comment]
Building 'old' GAMESS-US version works fine, while building it with `ictce/6.2.5` is problematic (one failed test).

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/68eea2f0e0ab6afc2e36 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ac35c7ab5017519b8057 for a full test report.

**Comment by boegel** [comment]
@wpoely86: up for giving this a spin (on top of https://github.com/hpcugent/easybuild-easyblocks/pull/558)?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/951be48e236940810ce0 for a full test report.

**Comment by boegel** [comment]
@wpoely86: tests utterly failed... I'm seeing a lot of `MPI startup(): dapl fabric is not available and fallback fabric is not enabled`.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/8dd0ab48aefe4c354c6c for a full test report.

**Comment by boegel** [comment]
@wpoely86: the rungms script sets `$I_MPI_FABRICS` hard to `dapl`, which explains why it's failing on your end?

Please try defining `$I_MPI_FALLBACK`, and testing again. If that helps, I'll make the GAMESS-US easyblock set $I_MPI_FALLBACK` in `test_step`, which should fix the problem.

**Comment by boegel** [comment]
see https://software.intel.com/sites/products/documentation/hpc/ics/impi/41/lin/Reference_Manual/Communication_Fabrics_Control.htm#I_MPI_FALLBACK1

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/3b137e85b9932cb00d1f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.0.1406, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1a35d1ccde1adac32ab2 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/2326cf3da609011b9a24 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.0.1406, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d2ddf8eb23accca8fd2a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.0.1406, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/de8fe0cc54511a7e8091 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5bc221f71aeebd17f22b for a full test report.

**Comment by boegel** [comment]
OK, I'm calling this since it works on Debian and SL6 (our main testing platform).

I need to look into our new CentOS 7 system a bit more before I consider failing tests there a blocker.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Going in, thanks for testing @wpoely86 and @pescobar!

**Pull request merged**
