### PR TITLE
easyconfig for PlatformMPI-9.1.2

### PR DESCRIPTION
**Pull request by ahmedsajid**
added easybuild config file. Will be doing easyblock pull soon.

### CODE REVIEW

**Comment by ahmedsajid** [comment]
@boegel Its only comes as binary/RPM.

**Comment by fgeorgatos** [comment]
in that case, of binary, a versionsuffix -linux-x86-64 or similar, may be
appropriate?

On 22 April 2015 at 18:27, ahmedsajid <notifications@github.com> wrote:

> @boegel <https://github.com/boegel> Its only comes as binary/RPM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-easyconfigs/pull/1029#issuecomment-95275210>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by boegel** [comment]
@ahmedsajid: I can only download a file named `platform_mpi-09.01.02.00u.x64.bin` (via the community version), which doesn't match the `sources` specification you've included in your easyconfig file (`SOURCE_TGZ` which translates to `PlatformMPI-9.1.2.tgz`).

Did you obtain the tarball as-is, or did you create it yourself?

**Comment by boegel** [comment]
The `.bin`  file I'm able to download is an interactive installer:

```
$ ./platform_mpi-09.01.02.00u.x64.bin 
Preparing to install...
Extracting the JRE from the installer archive...
Unpacking the JRE...
Extracting the installation resources from the installer archive...
Configuring the installer for this system's environment...

Launching installer...


Graphical installers are not supported by the VM. The console mode will be used instead...

===============================================================================
IBM_PlatformMPI                                  (created with InstallAnywhere)
-------------------------------------------------------------------------------

Preparing CONSOLE Mode Installation...




===============================================================================
Introduction
------------

InstallAnywhere will guide you through the installation of IBM_PlatformMPI.

It is strongly recommended that you quit all programs before continuing with 
this installation.

Respond to each prompt to proceed to the next step in the installation.  If you
want to change something on a previous step, type 'back'.

You may cancel this installation at any time by typing 'quit'.

PRESS <ENTER> TO CONTINUE: 
```

**Comment by ahmedsajid** [comment]
@boegel I created .tgz myself.

**Pull request closed without merging**
