### PR TITLE
{data}[intel/2015b] TiMBL 6.4.6 + TiCCutils 0.7 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/eb10a1e6daf57a9b1320 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4ef2aaf6208279a51fa5 for a full test report.

**Comment by ehiggs** [comment]
Looks ok. If it works, should be fine.

**Comment by boegel** [comment]
@ehiggs: it works, see the submitted test reports

**Comment by boegel** [comment]
Thanks for the review @ehiggs!

**Pull request merged**
