### PR TITLE
{numlib}[intel/2015b] GSL 2.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/98b86ed81d9ba844a09b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0ef91da9fb1c45774698 for a full test report.

**Comment by boegel** [comment]
@wpoely86: please ~~merge~~ review ;-)

**Comment by rjeschmi** [comment]
looks fine, but seems weird to have to define with-pic in config options along with toolchainopts

**Pull request merged**
