### PR TITLE
{vis}[intel/2016b] mahotas v1.4.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2143.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5f00496977da6cc222b9346118fdd2f5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2426.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/16d2e369bcd647805da37fe8ffba08ed for a full test report.

**Comment by boegel** [comment]
@verdurin or @pescobar please review (trivial imho)

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login000.camp.thecrick.org - Linux centos linux 7.2.1511, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/a30ef657f816044552bbcd3de364777e for a full test report.

**Comment by verdurin** [comment]
Looks okay to me.

**Comment by boegel** [comment]
Thanks for the review @verdurin!

**Pull request merged**
