### PR TITLE
{bio}[goolf/1.7.20] SPAdes v3.6.2

### PR DESCRIPTION
**Pull request by pescobar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar 

```
ERROR: Irresolvable dependencies encountered: Boost/1.53.0-goolf-1.7.20, CMake/2.8.12-goolf-1.7.20
```

You probably want to bump those versions?

**Comment by pescobar** [comment]
> You probably want to bump those versions?

not really. Those are the versions I use in my machine unless users specifically request or need a different one

**Comment by pescobar** [comment]
@boegel please retest?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (3 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3050dda305c86ccaa6e74542ff71ef90 for a full test report.

**Comment by boegel** [comment]
@pescobar you're using hidden somewhere for `bzip2`?

```
Module 'bzip2/.1.0.6-goolf-1.7.20' conflicts with the currently loaded module(s) 'bzip2/1.0.6-goolf-1.7.20'
```

**Comment by pescobar** [comment]
ups my mistake. I removed the hidden deps..

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6100a991c6a6a9499230b8945bbab1e9 for a full test report.

**Comment by boegel** [comment]
@pescobar still the same issue... the old CMake may be too stupid, maybe bumping the CMake version will be required after all here?

**Comment by pescobar** [comment]
@boegel cmake version bumped

this is really weird because in the machine I am building I have no boost rpms installed and I could build this without defining boost as a dependency

I think spades was using boost before but now it no longer uses boost but when cmake finds boost libs in `/usr/lib` the build system gets crazy.... 

I have no big hope that this gets fixed by bumping cmake version but anyway...would you retest just in case?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4677613cbb0c5747170811e2516be596 for a full test report.

**Comment by pescobar** [comment]
@boegel if you try to build this easyconfig in a machine which has no boost rpm installed it will work. This has happened to me before with a different application :)

 cmake fancy stuff...

**Comment by pescobar** [comment]
btw, I will remove the boost dependency because I am sure it's not needed. Check the spades changelog, they removed the boost dependency in version `SPAdes 2.3.0, 30 October 2012`

http://spades.bioinf.spbau.ru/changelog.html

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/190a08f067e81f008cdb9d6d2f04699e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pescobar!

**Pull request merged**
