### PR TITLE
{compiler} [intel-2015a] LLVM 3.6.2 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by wpoely86** [comment]
lgtm

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/16a4fc240c1b8f7e1dbb for a full test report.

**Comment by wpoely86** [comment]
lgtm, @boegel ready to merge

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a4be53e38eacfdaf0df3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
