### PR TITLE
{bio}[intel/2015a] SAMtools (REVIEW)

### PR DESCRIPTION
**Pull request by gjbex**
latest SAMtools build with intel

### CODE REVIEW

**Comment by gjbex** [comment]
Test report by @gjbex
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.6
See https://gist.github.com/10704c6de59c990c1147 for a full test report.

**Comment by wpoely86** [comment]
ok to test

**Comment by wpoely86** [comment]
@boegel good to go

**Comment by fgeorgatos** [comment]
@boegel: test & merge this?

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d7611194b8b7875bcef3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @gjbex an @fgeorgatos + @wpoely86 for the review!

**Pull request merged**
