### PR TITLE
 {toolchains} [gmvapich2, gmvolf]

### PR DESCRIPTION
**Pull request by sguera**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**SUCCESS**
Build succeeded for 7 out of 7
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/e6c40629fc27a6a0a572 for a full test report.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (7 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/56a407f15794978a396e for a full test report.

**Comment by boegel** [comment]
Looking great @sguera, thanks for making your 1st contribution. Welcome to the wonderful world of EasyBuild!

Thanks to @fgeorgatos for the support delivered to @sguera during the EasyBuild hackathon in Basel.

Going in, so this will effectively become part of the upcoming EasyBuild v2.0!

**Comment by sguera** [comment]
It was great a great workshop, very successfull on my side. Thank you @boegel  for organizing it.
Many thanks to @fgeorgatos for your help and patience

**Comment by fgeorgatos** [comment]
@sguera: thanks go to many hands for different reasons: @stdweird for writing the first bits, @boegel for running much of the show ever since, @pescobar for organizing the hackathon of this week!

**Pull request merged**
