### PR TITLE
Delete deprecated Cray toolchains and easyconfig files (for stable cray support)

### PR DESCRIPTION
**Pull request by gppezzi**
Let's wait for https://github.com/hpcugent/easybuild-easyconfigs/pull/2435 and https://github.com/hpcugent/easybuild-easyconfigs/pull/2434

### CODE REVIEW

**Comment by boegel** [comment]
@gppezzi any reason you're not removing the CrayGNU-5.1.29 and CrayGNU-5.2.25 easyconfigs here too?

**Comment by gppezzi** [comment]
@boegel I don't remember why I did that, now I think I've deleted all the old stuff. Let me know if it is OK (github is complaining about conflicts)

**Comment by boegel** [comment]
good to go, but let's indeed wait until #2434 and #2435 are merged in

**Comment by gppezzi** [comment]
ping @boegel

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Going in, thanks @gppezzi!

**Pull request merged**
