### PR TITLE
{cae}[intel/2016b] MATSim 0.8.1 w/Java-1.8.0_112 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by hajgato** [comment]
I do not have an idea why this is failed. Probably due to the `modloadmsg` part. Any suggestion?

**Comment by boegel** [comment]
@hajgato the version number is missing in the easyconfig file name

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2684.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1041c8d3dcbbf6648fa04959827eed12 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2082.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7fa43d6b37ab985c749c2b95f0766867 for a full test report.

**Comment by hajgato** [comment]
@boegel Oops. Error is corrected.

**Comment by boegel** [comment]
@hajgato you'll need to remove the faulty file...

**Comment by hajgato** [comment]
@boegel Oh crap, I though that moving the file would be enough...

**Comment by boegel** [comment]
@hajgato if you use `git mv`, yes, it should be enough... anyway, good to go now

**Pull request merged**
