### PR TITLE
add easyconfig file for Extrae

### PR DESCRIPTION
**Pull request by boegel**
this easyconfig is contributed by @berndmohr via https://github.com/fgeorgatos/easybuild.experimental/tree/master/users/unite

depends on ~~#505~~ for `PAPI`

requires ~~https://github.com/hpcugent/easybuild-easyblocks/pull/892~~ https://github.com/hpcugent/easybuild-easyblocks/pull/955

### CODE REVIEW

**Comment by geimer** [comment]
@boegel: I just checked this PR and saw that it also adds `sanity_check_path` to most (if not all) libxml2 easyconfigs. To keep PRs handy and focused, I suggest to split this part into a separate PR. What do you think?

**Comment by fgeorgatos** [comment]
+1

I was doing the same practice, at those good times that PRs were merged
quickly :)

On 11 June 2015 at 11:58, geimer <notifications@github.com> wrote:

> @boegel <https://github.com/boegel>: I just checked this PR and saw that
> it also adds sanity_check_path to most (if not all) libxml2 easyconfigs.
> To keep PRs handy and focused, I suggest to split this part into a separate
> PR. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-easyconfigs/pull/507#issuecomment-111084655>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by boegel** [comment]
The libxml2 stuff is fleshed out (and extended to cover all libxml2 easyconfigs) in #1690.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2038.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4cb30aaf7c9f23e4430e812481761271 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/375d18243f2687a6bfa6d6e869c51979 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/97cfd01b33d06624140fa67c4f0a87a9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/adcf01287b22453647096ba29996d518 for a full test report.

**Comment by boegel** [comment]
I'd say it's time to merge this in, 2.5 years after it was opened (oldest PR to date...) \o/

**Pull request merged**
