### PR TITLE
{tools}[GCC/4.9.2] parallel 20150322, Perl 5.20.2 (bare) (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/30ed2dbdc3c8ed09375d for a full test report.

**Comment by wpoely86** [comment]
okay

**Comment by boegel** [comment]
Thanks @wpoely86!

**Pull request merged**
