### PR TITLE
{cae} [intel/2016a] OpenFOAM 2.2.2 (REVIEW)

### PR DESCRIPTION
**Pull request by wpoely86**
@boegel please review

### CODE REVIEW

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2626.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3828e6dba0e471e38c65bd20ef1f015e for a full test report.

**Comment by boegel** [comment]
@wpoely86 lgtm, but test install fails?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2626.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a03d94759ac80d1d10a4678fdf60545b for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2005.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9cca5b792528ab53e80f99768f1da6b2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/bcd4f9ed47327383e50c2882da4c9c43 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
node2584.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/75527e3b460d0daf03fb1e0ad66a84eb for a full test report.

**Comment by wpoely86** [comment]
@boegel you're using an old version of the patch. I've already tested the build on golett...

**Comment by boegel** [comment]
@wpoely86 note that I wanted to test the build of an *old* OpenFOAM easyconfig, that is using the same patch as the one you're changing... I'll make it pick up your updated patch instead.

**Comment by boegel** [comment]
Anyway, it doesn't matter, the sources are the same, and you've already tested on CentOS7 indeed, so going in.

Thanks @wpoely86!

**Pull request merged**
