### PR TITLE
{tools}[dummy] GC3Pie 2.4.2 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by rjeschmi** [comment]
I guess we should test this under a few different systems pythons?

Otherwise, looks fine.

**Comment by boegel** [comment]
@rjeschmi: we did that for previous versions of GC3Pie, on OS X, SLES, RHEL6, CentOS 6, and Debian, see #1692 and #1756

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz, Python 2.7.6
See https://gist.github.com/7549627d2ead6df162b2 for a full test report.

**Comment by boegel** [comment]
Thanks for the review @rjeschmi!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/cd237b6aca93aa094fa0 for a full test report.

**Pull request merged**
