### PR TITLE
{tools} [GCC/4.8.x] Lmod/5.9 (REVIEW)

### PR DESCRIPTION
**Pull request by fgeorgatos**
Lmod/5.9 is cache-fast, bug-free (!), and simply rocks.

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**SUCCESS**
Build succeeded for 4 out of 4
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/b34ad4460b02a7b723c9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/196fea57c256cc41281c for a full test report.

**Comment by boegel** [comment]
last test failed because of:

```
The sourceforge.net website is temporarily in static offline mode.
Only a very limited set of project pages are available until the main website returns to service.
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/08043b997412c62f9423 for a full test report.

**Comment by boegel** [comment]
Thanks for providing the tarball @fgeorgatos!

Working great, so going in!

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 4 out of 6 (4 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/aa7d98717e8fd60ce4c6 for a full test report.

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**FAILED**
Build succeeded for 3 out of 4
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/fea07bb2c3389d8c4475 for a full test report.

**Pull request merged**
