### PR TITLE
libdrm Noveau deleted + some polishing

### PR DESCRIPTION
**Pull request by hajgato**
onfigopts = '--enable-nouveau-experimental-api' deleted, plus some polishing
Fleshed out form closed PR #1166

### CODE REVIEW

**Comment by wpoely86** [comment]
lgtm

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 14 out of 21 (6 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1bf1dc5a390bedbec2e1 for a full test report.

**Comment by boegel** [comment]
@wpoely86: seems like you have some very old modules around :)

**Comment by wpoely86** [comment]
@boegel it seems I do. 
```
grep -rHn 'SOFTROOTGCC' /apps/gent/SL6/sandybridge/modules/all/
/apps/gent/SL6/sandybridge/modules/all/GCC/4.6.3:19:setenv	SOFTROOTGCC		$root
```
I don't (yet) have write access to that directory :wink: You will have to take care.

**Comment by boegel** [comment]
@wpoely86: we wont be touched that module... :-)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/cbb91d8e383d4332e6da for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
