### PR TITLE
{data}[intel/2016a] dask v0.8.2 w/ Python 2.7.11 & 3.5.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires #2887 to be merged

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2448.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fb5a2bd9d70490f886edfd777cf132fc for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fbde7760ee04ed57b4902da19e4183ea for a full test report.

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Test on SL6 failed with on `import lzma`, I'll figure out what's going on (may be an outdated installation of the Python 3.5.1 module there).

**Comment by boegel** [comment]
Hmm, the problem persists even after making sure the installation is fully up-to-date:

```
bash-4.1$ module load Python/3.5.1-intel-2016a
bash-4.1$ python -c "import lzma"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/apps/gent/SL6/sandybridge/software/Python/3.5.1-intel-2016a/lib/python3.5/lzma.py", line 26, in <module>
    from _lzma import *
ImportError: No module named '_lzma'
```

May be due to a missing dependency...

**Comment by boegel** [comment]
To build LZMA support in Python 3.3 or more recent, XZ must be around. Our SL6 system has `xz-devel` missing, while our CentOS7 systems do have it, explaining the issue.

I'll look into adding a dep on XZ for Python 3.5.1.

**Comment by boegel** [comment]
fix for the `lzma` issue is in #2887

**Comment by boegel** [comment]
issue is fixed on top of rebuilt Python 3.5.1 from #2887, see incoming test report

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c198934e8fe0e14ce3fda4f48238dce5 for a full test report.

**Comment by boegel** [comment]
good to go now #2887 is merged

thanks for the review @wpoely86!

**Pull request merged**
