### PR TITLE
{math}[CrayGNU/2016.03] GMP v6.1.0

### PR DESCRIPTION
**Pull request by gppezzi**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@gppezzi test report?

**Comment by gppezzi** [comment]
Test report by @gppezzi
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dora102 - Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.7.7
See https://gist.github.com/29b82771415840178d57841190b09d1f for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @gppezzi!

**Pull request merged**
