### PR TITLE
{mpi}[dummy/dummy] impi v2017.0.098, impi v2017.1.132, impi v2017.1.132, ...

### PR DESCRIPTION
**Pull request by jdonners**
(created using `eb --new-pr`)
Update description for Intel MPI releases that support newer MPI standards

### CODE REVIEW

**Comment by boegel** [comment]
@jdonners Did you miss the `5.1.[0-2]` ones?

**Comment by jdonners** [comment]
hmm, indeed. And the 5.1.3 ones should me MPI-3.0

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @jdonners!

**Pull request merged**
