### PR TITLE
Update Bioconductor to 3.2 for R 3.2.1 with goolf 1.7.20, with subpackage updates

### PR DESCRIPTION
**Pull request by verdurin**
Port the current goolf 1.7.20 Bioconductor bundle to R 3.2.1 and update various Bioconductor component packages.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@verdurin: required easyconfig for R 3.2.1 with `goolf/1.7.20` is missing?

**Comment by verdurin** [comment]
Bah - yes, it is. Must have just built it locally and forgot to add here.

**Comment by verdurin** [comment]
This is effectively now targetting Bioconductor 3.2

**Comment by verdurin** [comment]
Hmm - rebasing this branch may have created a big mess.

It might be simpler to start again, with the new R-3.2.3 as a base.

**Comment by boegel** [comment]
@verdurin: big mess indeed, although it's probably GitHub screwing up...

Are you up for issuing a new PR for a Biocondutor 3.2 easyconfig on top of R 3.2.3?

**Comment by verdurin** [comment]
@boegel: Yes, that's my plan. Have started work locally and will issue the PR when it's ready for further testing.

**Comment by boegel** [comment]
@verdurin this should be closed, since it's broken beyond repair?

**Comment by verdurin** [comment]
Agreed - closed.

**Pull request closed without merging**
