### PR TITLE
New EasyConfig for x264 20160114 with the foss-2015a toolchain

### PR DESCRIPTION
**Pull request by valtandor**
Required as part of the GRASS 7.0.2 dependency tree. Depends on Yasm 1.3.0, which is included for the sake of testing.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@valtandor: needs sync with `develop` now that #2405 is merged

**Comment by valtandor** [comment]
Synced with develop.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8d85b0bc08bd2bdf5d33 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/903fa6f22f08b1a16c9f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
