### PR TITLE
libxml2 dependency on HDF5 

### PR DESCRIPTION
**Pull request by RvDijk**
If libxml2 is not installed on OS, the following error occurs:

/software/software/binutils/2.25-GCCcore-4.9.3/bin/ld.gold: error: cannot find -lxml2
collect2: error: ld returned 1 exit status

@boegel if this is OK, should I include libxml2 as a dependency in all other HDF5 easyconfigs?

### CODE REVIEW

**Comment by boegel** [comment]
@RvDijk urgh, as you maybe noticed, including `libxml2` as a dep now is an issue because this HDF5 is used as a dep in places where `libxml2` is already a dependency too, so both the `version` and `versionsuffix` of `libxml2` must match.

There are a handful of easyconfigs that seem to depend both on this HDF5 and `libxml2` 2.9.3 with `-Python-2.7.11` as `versionsuffix`, i.e.:

* `MDSplus-7.0.67-foss-2016a-Java-1.7.0_79-Python-2.7.11.eb`
* `NCO-4.6.0-foss-2016a.eb`
* `libdap-3.18.1-foss-2016a-Python-2.7.11.eb`

So, if you want to go through with this, you'll need to see what the `libxml2` with Python bindings is really required for these, and if not, drop the `versionsuffix` for `libxml2` in them...

With this in mind, it's probably going to be very painful to add `libxml2` as dep in all existing HDF5 easyconfigs, but we should try and do it for at least the most recent ones...

**Comment by RvDijk** [comment]
@boegel this seems to work on Travis, except for the newer lmod versions.  If this is what you had in mind, then I'll also change this in other versions of HDF5.

**Comment by boegel** [comment]
(close/open to retrigger Travis with correct config)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (3 easyconfigs in this PR)
node2044.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c5b33432c80b3462c2720ab529659396 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (3 easyconfigs in this PR)
node2693.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e4ac1147164e9844237af29001c926e3 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @RvDijk!

**Pull request merged**
