### PR TITLE
add easyconfig for Paraview v4.1.0 + missing deps

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato: Jenkins detected this:

```
Conflict found for dependencies of Paraview-4.1.0-ictce-4.1.13: libxml2-2.8.0-ictce-4.1.13-Python-2.7.3 vs libxml2-2.9.1-ictce-4.1.13
```

**Comment by ocaisa** [comment]
I'm not sure this easyconfig makes sense, you can't have both MESA and Qt support in the same build of Paraview from what I know (but I'm happy for someone to prove me wrong). For the parallel build one should look at #1627 which has a much more complete list of dependencies.

**Comment by boegel** [comment]
This PR should probably be closed if #1627 makes it in...

**Comment by boegel** [comment]
superseded by #1627

**Pull request closed without merging**
