### PR TITLE
{lang}[foss/2016b,intel/2016b] R 3.3.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
dependencies & list of extensions are updated

depends on ~~#3329~~ and ~~#3330~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (12 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ee08d80d873cecd7504b5ceec5ac66ea for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (12 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3fd4f623301a0fa0aa568a9249e55bed for a full test report.

**Comment by boegel** [comment]
'trivial' version/toolchain update, going in

**Comment by backelj** [comment]
@boegel Do the nodes from delcatty and golett have some system development packages installed? Because the package for R-3.3.1-intel-2016b.eb needs to have both cairo and tclck (as mentioned in other issues) but cairo is not in the dependency list and the configopts is missing the options for tcltk...

**Comment by boegel** [comment]
@backelj Sorry for not getting back on this, we have an issue open for this at https://github.com/hpcugent/easybuild-easyconfigs/issues/2742, we should fix this problem with the 2017a toolchains.

**Pull request merged**
