### PR TITLE
BEDOPS-2.4.1-GCC-4.8.2.eb (REVIEW)

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**FAILED**
Build succeeded for 0 out of 1
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/fe878fe719471282e9ec for a full test report.

**Comment by fgeorgatos** [comment]
@boegel: looks please test/merge

**Comment by fgeorgatos** [comment]
put this in REVIEW plz!

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos 6.6, AMD Opteron(tm) Processor 6380, Python 2.6.6
See https://gist.github.com/3027cb56e2c20ce1584f for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos 6.6, AMD Opteron(tm) Processor 6380, Python 2.6.6
See https://gist.github.com/c3814629f6430e5084f4 for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos 6.6, AMD Opteron(tm) Processor 6380, Python 2.6.6
See https://gist.github.com/0509d490c34d8a911d0a for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
Linux centos 6.6, AMD Opteron(tm) Processor 6380, Python 2.6.6
See https://gist.github.com/dee906e54d1b644827b8 for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6a2827bc0243b34884ac for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos 6.6, AMD Opteron(tm) Processor 6380, Python 2.6.6
See https://gist.github.com/eff2c0178709187c24c9 for a full test report.

**Comment by rjeschmi** [comment]
I'm pretty sure this is broken in some way:

```
== FAILED: Installation ended unsuccessfully (build directory: /software/experimental/build/BEDOPS/2.4.1/GCC-4.8.4): build failed (first 300 chars): cmd " make -j 1  static && make install" exited with exitcode 2 and output:
touch applications/bed/sort-bed/src/.forcestatic
touch applications/bed/bedops/src/.forcestatic
touch applications/bed/closestfeats/src/.forcestatic
touch applications/bed/bedmap/src/.forcestatic
touch applications/bed/conve
```

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ea2320c1492795b09d5e for a full test report.

**Comment by boegel** [comment]
@rjeschmi: works for me... Can you retest?

**Comment by boegel** [comment]
@rjeschmi ping on retest?

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login18.cluster.bc2.ch - Linux centos 6.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.6.6
See https://gist.github.com/daff18a4b40bc33edf514f641d8c8f15 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e07543cb5f2fe35d40289893b0012c8e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/17e72da112496f69721a7c333113a21d for a full test report.

**Comment by boegel** [comment]
not holding this back any further... going in!

**Comment by verdurin** [comment]
Hmm - this builds on my test box at home but not on a new cluster:

```
== 2016-07-23 07:10:32,904 run.py:99 DEBUG run_cmd: running cmd  make -j 1  static && make install (in /camp/apps/eb/build/BEDOPS/2.4.2/GCC-4.8.2/bedops-2.4.2)
== 2016-07-23 07:10:40,446 run.py:392 DEBUG cmd " make -j 1  static && make install" exited with exitcode 2 and output:
touch applications/bed/sort-bed/src/.forcestatic
touch applications/bed/bedops/src/.forcestatic
touch applications/bed/closestfeats/src/.forcestatic
touch applications/bed/bedmap/src/.forcestatic
touch applications/bed/conversion/src/wig2bed/.forcestatic
touch applications/bed/bedextract/src/.forcestatic
touch applications/bed/starch/src/.forcestatic
test -s third-party/boost_1_46_1 || { bzcat third-party/boost_1_46_1.tar.bz2 | tar -x -C third-party; }
ln -sf boost_1_46_1 third-party/boost
test -s third-party/bzip2-1.0.6 || { bzcat third-party/bzip2-1.0.6.tar.bz2 | tar -x -C third-party; }
ln -sf bzip2-1.0.6 third-party/bzip2
test -s third-party/jansson-2.4 || { bzcat third-party/jansson-2.4.tar.bz2 | tar -x -C third-party; }
ln -sf jansson-2.4 third-party/jansson
test -s third-party/zlib-1.2.7 || { bzcat third-party/zlib-1.2.7.tar.bz2 | tar -x -C third-party; }
ln -sf zlib-1.2.7 third-party/zlib
make -C applications/bed/sort-bed/src
make[1]: Entering directory `/camp/apps/eb/build/BEDOPS/2.4.2/GCC-4.8.2/bedops-2.4.2/applications/bed/sort-bed/src'
rm -rf .forcestatic
mkdir -p ../bin
mkdir -p objects
g++ -Wall -Wextra -pedantic -ansi -O3 -std=c++11 -c SortDetails.cpp -o objects/SortDetails.o -I../../../../interfaces/general-headers
g++ -Wall -Wextra -pedantic -ansi -O3 -std=c++11 -c Sort.cpp -o objects/Sort.o -I../../../../interfaces/general-headers
g++ -o ../bin/sort-bed  -static -s -Wall -Wextra -pedantic -ansi -O3 -std=c++11 objects/SortDetails.o objects/Sort.o
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[1]: *** [sort] Error 1
make[1]: Leaving directory `/camp/apps/eb/build/BEDOPS/2.4.2/GCC-4.8.2/bedops-2.4.2/applications/bed/sort-bed/src'
make: *** [sort_c] Error 2

== 2016-07-23 07:10:40,715 build_log.py:152 ERROR cmd " make -j 1  static && make install" exited with exitcode 2 and output:
touch applications/bed/sort-bed/src/.forcestatic
touch applications/bed/bedops/src/.forcestatic
touch applications/bed/closestfeats/src/.forcestatic
touch applications/bed/bedmap/src/.forcestatic
touch applications/bed/conversion/src/wig2bed/.forcestatic
touch applications/bed/bedextract/src/.forcestatic
touch applications/bed/starch/src/.forcestatic
test -s third-party/boost_1_46_1 || { bzcat third-party/boost_1_46_1.tar.bz2 | tar -x -C third-party; }
ln -sf boost_1_46_1 third-party/boost
test -s third-party/bzip2-1.0.6 || { bzcat third-party/bzip2-1.0.6.tar.bz2 | tar -x -C third-party; }
ln -sf bzip2-1.0.6 third-party/bzip2
test -s third-party/jansson-2.4 || { bzcat third-party/jansson-2.4.tar.bz2 | tar -x -C third-party; }
ln -sf jansson-2.4 third-party/jansson
test -s third-party/zlib-1.2.7 || { bzcat third-party/zlib-1.2.7.tar.bz2 | tar -x -C third-party; }
ln -sf zlib-1.2.7 third-party/zlib
make -C applications/bed/sort-bed/src
make[1]: Entering directory `/camp/apps/eb/build/BEDOPS/2.4.2/GCC-4.8.2/bedops-2.4.2/applications/bed/sort-bed/src'
rm -rf .forcestatic
mkdir -p ../bin
mkdir -p objects
g++ -Wall -Wextra -pedantic -ansi -O3 -std=c++11 -c SortDetails.cpp -o objects/SortDetails.o -I../../../../interfaces/general-headers
g++ -Wall -Wextra -pedantic -ansi -O3 -std=c++11 -c Sort.cpp -o objects/Sort.o -I../../../../interfaces/general-headers
g++ -o ../bin/sort-bed  -static -s -Wall -Wextra -pedantic -ansi -O3 -std=c++11 objects/SortDetails.o objects/Sort.o
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[1]: *** [sort] Error 1
make[1]: Leaving directory `/camp/apps/eb/build/BEDOPS/2.4.2/GCC-4.8.2/bedops-2.4.2/applications/bed/sort-bed/src'
make: *** [sort_c] Error 2
```

**Pull request merged**
