### PR TITLE
Octave 4.2.1: add easyconfig for intel 2016b with updated deps incl Qt5

### PR DESCRIPTION
**Pull request by bartoldeman**

### CODE REVIEW

**Comment by bartoldeman** [comment]
I also needed `configopts += '--enable-fortran-calling-convention=gfortran '` in our configuration but I am not 100% sure if that is needed for intel 2016b

**Comment by boegel** [comment]
@bartoldeman It is needed, see https://github.com/hpcugent/easybuild-easyconfigs/pull/4430/files#diff-a55258c08819ce6888cccb100b4a5330R54, so please include it here as well.

I'll close my PR #4430 since your PR has slightly more up-to-date dependencies.

**Comment by bartoldeman** [comment]
I should have searched PRs... Anyway #4430 also talks about Qhull which is resolved by #4451.

```
# these need to be specified explicitly, or they get derived wrongly to '-I' and '-L'
configopts += '--with-qhull-libdir=$EBROOTQHULL/lib --with-qhull-includedir=$EBROOTQHULL/include '
```

**Comment by boegel** [comment]
@bartoldeman ah, right, I should've connected the dots...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
node2408.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/bf37cae54875b8625c9807db8c55012e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2140.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/73733be06a149ac04e30a05d2e70ab35 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
