### PR TITLE
{tools}[intel/2017a] HPL v2.2 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2519.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9527568602ab49645b951209983c1acf for a full test report.

**Comment by JackPerdue** [comment]
Can somebody add intel-gdb to the list of components for icc (probably sufficent to add just to icc and not ifort)?   I realized today I got no gdb-ia for 2016 and 2017 intel toolchains.  Finally tracked it down to that.

**Comment by boegel** [comment]
@JackPerdue done, I now have this with the updated list of components:

```
$ ls $EASYBUILD_PREFIX/software/icc/2017.1.132-GCC-6.3.0-2.27/bin | grep gdb
gdb-ia
gdb-igfx
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2044.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/578436f2f6adb0952b9e539c95107e85 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2693.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3c72120f06d0c6222ab34b66d0e2ab00 for a full test report.

**Comment by boegel** [comment]
Thoroughly tested with these (+ all deps) via `--try-toolchain-version=2017a --robot`, works like a charm:

* `CP2K-3.0-intel-2016b.eb`
* `Perl-5.24.0-intel-2016b.eb`
* `Pyton-2.7.12-intel-2016b.eb`
* `Python-3.5.2-intel-2016b.eb`
* `R-3.3.1-intel-2016b.eb`

**Comment by boegel** [comment]
Going in, to be included with EasyBuild v3.1.0

**Pull request merged**
