### PR TITLE
Doxygen EasyConfigs with added dependency EasyConfigs

### PR DESCRIPTION
**Pull request by valtandor**

### CODE REVIEW

**Comment by boegel** [comment]
@valtandor: needs sync with `develop` as soon as #2421 is merged

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@valtandor: please sync with `develop` now that #2421 is merged, and tackle the problems Jenkins is complaining about (wrong toolchain for flex?)

**Comment by valtandor** [comment]
flex-2.6.0-GCC-4.9.2 has now been added to a new PR (#2485). This PR could reasonably be tested again once #2485 has gone in.

**Comment by boegel** [comment]
@valtandor: CMake dep is missing in two of these Doxygen easyconfigs

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/eac0a8db418255bcf1e6 for a full test report.

**Comment by valtandor** [comment]
I've added it to Doxygen-1.8.11-GCC-4.9.2.eb. It seems to be missing from *all* older EasyConfigs, though.

**Comment by boegel** [comment]
@valtandor: build system for Doxygen was changed to CMake in v1.8.10, cfr. http://www.stack.nl/~dimitri/doxygen/manual/changelog.html

**Comment by boegel** [comment]
@valtandor: no easyconfig for `CMake/3.4.1-GCC-4.9.2` yet

either add it, or stick to CMake 3.2.1

**Comment by valtandor** [comment]
@boegel: I can add it, I guess.

**Comment by valtandor** [comment]
@boegel: I've now made https://github.com/hpcugent/easybuild-easyconfigs/pull/2525 for CMake

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/b6b4fbeea706da01f832 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/84f246780149371aaeb5 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
