### PR TITLE
add fpp + deps as R extensions

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by ehiggs** [comment]
Looks good. +1

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/58ca366bf5d840739389 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0137a9e05fbf7a622081 for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @ehiggs!

**Pull request merged**
