### PR TITLE
add easyconfigs for CP2K v2.6.0 + deps with intel/2015a

### PR DESCRIPTION
**Pull request by boegel**
@wpoely86: please review

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3d25550eba7b7fa189f1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f225d4ba68488ca05370 for a full test report.

**Comment by wpoely86** [comment]
looks fine

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in this PR)
Linux debian 7.7, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/093d5383d3c208747b16 for a full test report.

**Comment by boegel** [comment]
@wpoely86: `libxc` installation failed because sources couldn't be downloaded, seems like `http://tddft.org/` is (temporarily?) down

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux debian 7.7, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/528a672fd7925c87eeee for a full test report.

**Comment by boegel** [comment]
going in, thanks for the review/testing @wpoely86!

**Pull request merged**
