### PR TITLE
{math}[intel/2016a] OpenFOAM-Extend 3.2 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires ~~#2958~~, ~~#2959~~, ~~#2960~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/142c4d8e5242500807982f09b1bf9413 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2002.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6bbb2c6dd1eaafee9d491e36253e3e65 for a full test report.

**Comment by boegel** [comment]
basically just a toolchain bump compared to existing easyconfig file...

anything to add @wpoely86?

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Thanks @wpoely86!

**Pull request merged**
