### PR TITLE
Drop GNU

### PR DESCRIPTION
**Pull request by ocaisa**
The argument goes (from @geimer originally) that since `binutils` uses machine code, it doesn't matter how you build binutils. In that case, there's no need to introduce the obfuscation layer `GNU`, simply explicitly list `binutils` as a dependency of `GCC`. 

This allows the `GCC` module to work out-of-the-box when building arch-optimised code.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
This yields conflicts for all easyconfigs that use the `GNU` toolchain, so the easyconfigs for the GNU toolchain itself should be modified too?

**Comment by ocaisa** [comment]
The conflict is from a fundamental change to the GCC easyconfig `builddependencies -> dependencies`. The only try way around it is to have a new GCC easyconfig.

**Comment by boegel** [comment]
@ocaisa: Well, the issue is that GNU includes a binutils next to GCC, while GCC now also loads binutils as a dependency itself.

So, GNU should be redefined to only load the GCC, or to include the same binutils as GCC does?

**Comment by ocaisa** [comment]
Yeah, that's the debate. To keep GNU working as it did, I'd have to create a new GCC easyconfig that still uses the builddep...not very hard to do. Changing GNUs binutils dep changes GNU (however superficially) so I'm probably more inclined to just create the new GCC and update the GCC dep in GNU.

**Comment by ocaisa** [comment]
Agree?

**Comment by boegel** [comment]
I don't see the problem with changing the dependencies in `GNU`, as long as it still delivers GCC + binutils (the latter directly or indirectly).

I wouldn't add more GCC easyconfigs, it would only add to the confusion?

**Comment by ocaisa** [comment]
Ok, then the answer is trivial, I just delete the binutils dependency since it comes directly from the GCC easyconfig anyway. This makes GNU just a pseudo-layer over GCC. It will probably trigger a few other dependency errors, I'll fix them when they pop up.

**Comment by boegel** [comment]
@ocaisa: maybe make it explicit and change the version of the binutils dep in GNU instead? (along with adding a comment that that binutils version is also loaded as a dep via GCC)?

**Comment by wpoely86** [comment]
I'm not entirely convinced that this is a good idea (not rebuilding binutils). Replacing GNU by GCC is perfectly fine by me. But I would keep the rebuild.

**Comment by ocaisa** [comment]
But that's not possible (right?), if GCC has a bintuils dependency (not build dependency), you can't use the GCC easyconfig to build binutils

**Comment by ocaisa** [comment]
You'd need to make the binutils build part of GCC itself (like someone suggested in the mailing list) and revert back to a binutils builddep

**Comment by wpoely86** [comment]
@ocaisa you would need an intermediary GCC (but not named so) easyconfig. Not pretty.

**Comment by ocaisa** [comment]
@wpoely86 Yeah, we had discussed internally about whether to have a `GCC-base`. This is not pretty but has a nice side effect for us: `GCC-base` can sit underneath all compiler 'families' (GCC, iccifort, PGI,...) and gives all of them an equivalence. This means I can install common tools like cmake at the GCC-base level rather than dummy. If others thought this was a good idea I'd be happy to implement, with our toolchain-based naming scheme it makes my life even easier.

**Comment by ocaisa** [comment]
So yes, definitely I would be +1 for an intermediate GCC

**Comment by boegel** [comment]
so, https://github.com/hpcugent/easybuild-easyconfigs/pull/2108 is preferred over this, right? so let's close this one? @ocaisa?

**Comment by ocaisa** [comment]
Yes, #2108 is preferred...closing

**Pull request closed without merging**
