### PR TITLE
Update GCCcore-5.4.0.eb

### PR DESCRIPTION
**Pull request by serge-p**
- added original source url for Integer Set Library (isl-0.15.tar.bz2)

### CODE REVIEW

**Comment by boegel** [comment]
@serge-p should this same change be made in the other GCC(core) easyconfigs?

cc @wpoely86

**Comment by wpoely86** [comment]
Yes, definitely. Weird we forgot that one. GCC usually has a copy too but the original is always better.

**Comment by boegel** [comment]
@serge-p are you up for applying this same change to the other GCC(core) easyconfigs?

**Comment by boegel** [comment]
merged via #3798

**Pull request merged**
