### PR TITLE
{bio} [intel-2014b] SOBAcl (REVIEW)

### PR DESCRIPTION
**Pull request by backelj**
Needed to fix two Easyconfig files to install SOBA.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@backelj: PR subject doesn't match contents? Please clarify?

**Comment by backelj** [comment]
What's wrong? As said, we needed to make the committed changes to the two Easyconfig files.
The goal is to install SOBA but we don't have an Easyconfig file for this yet.

**Comment by boegel** [comment]
Well, there's nothing *wrong*, except that the title is misleading. ;-)

Can you fix the `source_urls` in the other `Qt` 4.8.6 easyconfigs too, so they're kept in sync?

**Comment by boegel** [comment]
@backelj: Can you mark this PR as WIP until you consider it ready for consumption?

See also https://github.com/hpcugent/easybuild/wiki/Policy-for-easyconfig-pull-requests (I need to promote that more clearly).

**Comment by backelj** [comment]
@boegel: we are still learning here ;-)
I updated the PR title to include (WIP), is that okay?
Now I'm just waiting for an answer to my question on the mailing list about whether or not to include the toolchain name for the SOBAcl module before I commit it, and then it should be final... or ready for (REVIEW) that is :-)

**Comment by boegel** [comment]
@backelj: test report submitted

Just one question: any particular reason you guys are still stuck on `intel/2014b`?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 8 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3780598eacb58ade88f8 for a full test report.

**Comment by backelj** [comment]
@boegel: We were unable to compile one of these modules with intel-2015a. We got an internal error which Intel has fixed for their 2016 release (currently in test).

**Comment by boegel** [comment]
@backelj: what kind of internal error? Try building with `-O0` via `toolchainopts = {'noopt': True}`, to see if you can maybe dance around it by lowering the optimisation level? If `-O0` doesn't work, you're in trouble though.

**Comment by backelj** [comment]
@boegel: the kind of error that Intel confirmed :-)

**Comment by backelj** [comment]
Test report by @backelj
**SUCCESS**
Build succeeded for 46 out of 46 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/9ccd5d889b843b6119da for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@backelj: that last test report is... impressive :)

**Comment by boegel** [comment]
@backelj: we prefer keeping easyconfigs in sync across toolchains; are you up for opening a separate PR to update the other two Perl 5.20.0 easyconfigs too?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 4 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e46b25ecf05955fc5fce for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 4 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7e6c9599106a24d9d4ee for a full test report.

**Comment by backelj** [comment]
@boegel: I don't get the two last reports.... The first one says it can build Pango, the second one doesn't with the error being "C compiler cannot create executables". They are run on the same system, right?

I can see one other difference: the first one uses /gpfs/scratch/users/vsc400, the second one /vscmnt/gent_vulpix/_/user/home/gent/vsc4000...

What's wrong?

**Comment by boegel** [comment]
@backelj: these tests were probably run on an unstable framework branch, I'll need to retest them (but can't right now, our systems are down for maintenance)

Maybe @wpoely86 can fire a test for this, if he still has `foss/2014b` available?

**Comment by boegel** [comment]
Just for completeness sake, I had https://github.com/hpcugent/easybuild-framework/pull/1294 installed when testing this, and it seems like there still are some issues with that change (I ran into similar problems in #1337, I think).

**Comment by wpoely86** [comment]
@backelj please do not use a `/` in the name of a branch. It causes trouble.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 45 out of 45 (4 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/d1913b2c04b49c915514 for a full test report.

**Comment by backelj** [comment]
@boegel: Is there anything that needs to be done here?

**Comment by boegel** [comment]
@backelj: it should be good to go, but I want to get a successful test report from my end too first (which is troublesome right now)

I don't expect any problems, since the test already passed on both SL6 and Debian...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 47 out of 47 (4 easyconfigs in this PR)
Linux RHEL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f3ecc6410ac049ab32d1 for a full test report.

**Comment by boegel** [comment]
Alrighty, going in, thanks for tackling this @backelj!

**Pull request merged**
