### PR TITLE
{data}[foss/2016a]Log-Log4perl 1.47

### PR DESCRIPTION
**Pull request by RvDijk**

### CODE REVIEW

**Comment by RvDijk** [comment]
Test 026FileApp.t fails

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2461.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c77897b3fef843eef701e1a7265366ec for a full test report.

**Comment by boegel** [comment]
@RvDijk where are you seeing failing tests?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2071.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8e6ae7c8c401f6f2e6983a600d8a7bef for a full test report.

**Comment by RvDijk** [comment]
@boegel in the log file, test 026FileApp fails, details below. This might be a local problem since this error does not occur in your tests..

t/022Wrap.t ............... ok
t/023Date.t ............... ok
t/024WarnDieCarp.t ........ ok
t/025CustLevels.t ......... ok

#   Failed test at t/026FileApp.t line 493.
#          got: '509'
#     expected: '488'

#   Failed test at t/026FileApp.t line 497.
#          got: '436'
#     expected: '416'
# Looks like you failed 2 tests of 26.
t/026FileApp.t ............ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/26 subtests 
	(less 2 skipped subtests: 22 okay)
t/027Watch2.t ............. ok
t/027Watch3.t ............. ok
t/027Watch4.t ............. ok
t/028Additivity.t ......... ok

**Comment by boegel** [comment]
@RvDijk https://stackoverflow.com/questions/33135089/cpanm-failed-test-at-t-026fileapp-t-line-491 looks related (but that's on Cygwin, and no resolution posted there)

Based on https://rt.cpan.org/Public/Bug/Display.html?id=102647, this has something to do with unexpected permissions.

Can you share the output of `eb --show-config`? Are you fiddling with `--umask` or ` --set-gid-bit` or anything like that, which may break the test?

**Comment by RvDijk** [comment]
--show-config shows:

buildpath      (E) = /software/.local/build
installpath    (E) = /software/
modules-tool   (E) = Lmod
...
sourcepath     (E) = /software/.local/sources
umask          (C) = 002

Should umask have another value?  I did not change anything with the flags --umask or --set-gid-bit.

**Comment by boegel** [comment]
@RvDijk the `C` indicates that you're tweaking the `umask` configuration setting using a configuration file (`eb --show-default-configfiles` could help here).

It seems like that may be the culprit of the failing tests...

**Comment by RvDijk** [comment]
running the eb command with '\eb Log-Log4perl...' still gives the same error, however '\eb  --show-config' does not show umask (C) = 002. This suggests that umask does not cause the tests to fail?

**Comment by boegel** [comment]
@RvDijk OK, then it seems `umask` can't be blamed... Can you copy-paste the full output of `eb --show-config`?

**Comment by RvDijk** [comment]
@boegel 
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (E) = /software/.local/build
installpath    (E) = /software/
modules-tool   (E) = Lmod
repositorypath (D) = /home/p275545/.local/easybuild/ebfiles_repo
robot-paths    (E) = /home/p275545/easybuild/easybuild-easyconfigs/easybuild/easyconfigs, /software/.local/localconfigs/easybuild/easyconfigs
sourcepath     (E) = /software/.local/sources
umask          (C) = 002

**Comment by boegel** [comment]
@RvDijk now `umask` is there again? :)

**Comment by boegel** [comment]
@RvDijk I tried myself using `--umask=002`, and I can't seem to reproduce the failing test on my end...

**Comment by RvDijk** [comment]
@boegel then it seems to be a local problem? The problem still occurs for other umask values.

**Comment by boegel** [comment]
@RvDijk seems so, yes... I think we have a couple of options (in order of my preference):

* merge as is, and let you disable the tests when you install this (using `runtest = False`)
* figure out a way to either fix the test, or disable just that broken test
* disable all tests using `runtest = False`, and then merge

Thoughts?

**Comment by RvDijk** [comment]
@boegel it seems fine to me to merge as it is, I will use runtest = False.

**Comment by boegel** [comment]
@RvDijk OK, going in then, thanks!

**Pull request merged**
