### PR TITLE
Add easyconfig BWA-0.7.13-goolf-1.4.10

### PR DESCRIPTION
**Pull request by danielnavarrogomez**

### CODE REVIEW

**Comment by pescobar** [comment]
test this please

**Comment by danielnavarrogomez** [comment]
It's ready to be tested.

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.6.6
See https://gist.github.com/a193d84acc88ea22a23f for a full test report.

**Comment by pescobar** [comment]
this easyconfig should include zlib as dependency. See ldd output

```
[escobar@login18 bin]$ ldd bwa
	linux-vdso.so.1 =>  (0x00007fff663ff000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003823000000)
	libz.so.1 => /lib64/libz.so.1 (0x0000003823400000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003822800000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003822c00000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003822400000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003821c00000)
```

**Comment by danielnavarrogomez** [comment]
I just added @pescobar comments.

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.6.6
See https://gist.github.com/0f32e972304b8f9bde7d for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar01.gligar.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fc9120c8b85cc29bc772 for a full test report.

**Comment by boegel** [comment]
@pescobar convinced me to include this last-minute for EasyBuild v2.7.0 :)

Thanks @danielnavarrogomez!

**Pull request merged**
