### PR TITLE
{vis}[foss/2016a] libXrandr 1.5.0 (REVIEW)

### PR DESCRIPTION
**Pull request by jrbosch**
libXrandr 1.5.0 easyconfig for foss-2016a toolchain

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2632.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fbb44e5740baea052e57277ae9d02567 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2043.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4ca947c24f73748fea2d0c251219e2cf for a full test report.

**Comment by hajgato** [comment]
@jrbosch @boegel check PR #2760

**Comment by boegel** [comment]
@hajgato other than a source URL (which is properly using a constant here), the libXrandr and randrproto easyconfigs are identical to the ones in your PR, so I'll merge this PR which will make your PR a little bit smaller (it will need a sync with `develop` though)

@jrbosch PR #2760 also contains an easyconfig for freeglut 3.0.0, which I believe is on your list of required easyconfigs too?

Going in, thanks again @jrbosch!

**Pull request merged**
