### PR TITLE
Python no matplotlib

### PR DESCRIPTION
**Pull request by JensTimmerman**

### CODE REVIEW

**Comment by boegel** [comment]
issues with a stand-alone matplotlib that @ehiggs ran into:

```
Installed /vscmnt/gent_vulpix/_/user/home/gent/vsc410/vsc41041/.local/easybuild/software/matplotlib/1.3.1-intel-2015a-Python-2.7.8/lib/python2.7/site-packages/tornado-4.1-py2.7-linux-x86_64.egg
error: [Errno 13] Permission denied: '/vscmnt/gent_vulpix_apps/_apps_gent/SL6/sandybridge/software/Python/2.7.8-intel-2015a/lib/python2.7/site-packages/python_dateutil-2.2-py2.7.egg/EGG-INFO/requires.txt'

== 2015-03-06 16:07:03,527 main.easyblock WARNING build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/tools/run.py:384 in parse_cmd_output): cmd " python setup.py install --prefix=/user/home/gent/vsc410/vsc41041/.local/easybuild/software/matplotlib/1.3.1-intel-2015a-Python-2.7.8 " exited with exitcode 1 and output:
=======================================
```

**Comment by JensTimmerman** [comment]
yes, but these are not part of this pull request... this pull request actually fixes the build of the python easyconfigs.

**Comment by boegel** [comment]
I agree, but this PR *should* include matplotlib easyconfigs to go along with it, not just 'kill' matplotlib

**Comment by JensTimmerman** [comment]
in my experience, before this patch: no python, no matplotlib, after this patch: python, no matplotlib
So I consider this an improvement, your results may vary.

**Comment by JensTimmerman** [comment]
*should* not must :)

**Comment by boegel** [comment]
Check again with current develop, these lines are already gone?

**Comment by JensTimmerman** [comment]
I thought so, had to rebase on master to make github notice and close this. Thx

**Pull request closed without merging**
