### PR TITLE
{numlib}[intel/2016a] CGAL 4.8 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
'just' needs missing deps (incl. Mesa...)

requires ~~#2972~~, ~~#2973~~, ~~#2974~~, ~~#2975~~, ~~#2976~~, ~~#2977~~

### CODE REVIEW

**Comment by wpoely86** [comment]
@boegel ping? I could use this.

**Comment by boegel** [comment]
@wpoely86: just bump the deps, all you need is there already I think...

**Comment by boegel** [comment]
close/open to also trigger Travis on this...

**Comment by boegel** [comment]
reworked to CGAL 4.8, on top of Mesa 11.2.1 (cfr. #2974) and Qt5 5.6.0 (cfr. #2977)

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2565.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6f8551699d7a9959b82be8a0ce773577 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/92037bc29a53b500b1e657a162e05524 for a full test report.

**Comment by boegel** [comment]
\o/

**Pull request merged**
