### PR TITLE
{vis}[GCCcore/5.4.0] libpng v1.6.24, freetype v2.6.5, fontconfig v2.12.1

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)
Minimal toolchain version of `fontconfig` with dependencies

### CODE REVIEW

**Comment by vanzod** [comment]
Missing `expat2.2.0` provided in separate PR #4654

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2415.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1978c8429bf965446eab03d09bab61cc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2032.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/83767cdf30fd3470fef48e16be7f45b6 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
