### PR TITLE
{numlib}[dummy/dummy] cuDNN v6.0

### PR DESCRIPTION
**Pull request by RvDijk**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
very nice, thanks! 

Could we bump the priority of this one for release 3.2.0?!

**Comment by RvDijk** [comment]
@fgeorgatos seems fine to me. Am I able to do something in order to increase priority?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2523.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1b65ed6f87b16f9bd861e388e7ae36d9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2151.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/618a7b0b2f7c7a9da2fdbc3a0d9b5474 for a full test report.

**Comment by boegel** [comment]
@RvDijk Donate me a bag of time. ;-)

No, submitting a test report helps a great deal, see http://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#uploading-test-reports-upload-test-report .

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @RvDijk!

**Pull request merged**
