### PR TITLE
{devel}[iccifort/2016.3.210-GCC-5.4.0-2.26] SQLite v3.13.0

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

edit: depends on ~~#4691~~

### CODE REVIEW

**Comment by boegel** [comment]
@vanzod missing deps:

```
ERROR: Irresolvable dependencies encountered: libreadline/6.3-iccifort-2016.3.210-GCC-5.4.0-2.26, Tcl/8.6.5-iccifort-2016.3.210-GCC-5.4.0-2.26
```

**Comment by vanzod** [comment]
I added the `GCCcore` easyconfig here #4660. This should satisfy the dependency with minimal toolchain. Do you want an `iccifort` version too?

**Comment by boegel** [comment]
@vanzod OK, `libreadline` is there indeed (my bad), but `Tcl` is not...

**Comment by boegel** [comment]
To clarify: since EasyBuild v3.0, the robot will also consider subtoolchains even without `--minimal-toolchains`. With the latter, subtoolchains will be considered *first*, while by default it'll consider the toolchain of the 'parent' first and fall back to subtoolchains if that doesn't suffice to resolve dependencies.
Long story short: if the dependencies are there with `GCCcore`, it's fine.

**Comment by vanzod** [comment]
My bad. I added them in a separate PR: #4691

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2423.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ba79942f91a344eaa8fcd58f5da2e9c7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2056.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b8d63d5acc9644d8ea4d889f8bbc653e for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
