### PR TITLE
{lib}[foss/2016a] pandas v0.18.0

### PR DESCRIPTION
**Pull request by timeu**
For both version 2.7.x and 3.5.x version of python

### CODE REVIEW

**Comment by boegel** [comment]
@timeu PR title says 0.18.1, but easyconfigs are for 0.18.0? :)

**Comment by timeu** [comment]
@boegel Yes sorry that was a typo. I updated the title. I will also ammend the commit to fix the commit message. 
On that note. I am contributing this EasyConfig because I plan to also submit an EasyConfig for [limix](https://github.com/PMBio/limix), which depends on pandas and scikit-learn. I am wondering what's the policy. Currently I created an EasyConfig for limix for the latest pandas and scikit-learn modules for foss-2016a, but I can also create configs for other toolchains and python versions.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2427.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/11e61ce789cc3c204376e7856177207e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2062.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c4e8304c2e2f974d9a598687bcb6e0f5 for a full test report.

**Comment by boegel** [comment]
@timeu entirely up to you for which Python versions/toolchains you contribute easyconfigs for; ideally, limit yourself to the ones you can test yourself

**Comment by boegel** [comment]
@timeu also, to make contributing back easyconfigs easier, take a look at http://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#submitting-new-and-updating-pull-requests-new-pr-update-pr (`--new-pr` does a good job at auto-guessing the PR title, for example)

**Comment by timeu** [comment]
@boegel: Thanks, I was planing to use `--new-pr` that but I am blocked by this [issue](https://github.com/hpcugent/easybuild-framework/issues/1890).

**Comment by boegel** [comment]
@timeu howso? You should be targeting the `hpcugent` organisation with your PRs anyway? And you need to supply a GitHub token for your personal account?

**Comment by timeu** [comment]
We forked the `easybuild-easyconfig` repo into our institute's github organization and currently the github integration constructs the URL of the remote repo for the PR using the supplied github username.  So either I fork it again with my personal github account (which I want to avoid) or I create a user with the same name as the organization or I provide a patch to support organizations.

**Comment by boegel** [comment]
OK, you're right, I overlooked that, thanks for clarifying.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @timeu!

**Pull request merged**
