### PR TITLE
{vis} [intel-2015b] Paraview 4.4.0 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
ignore the commit message

### CODE REVIEW

**Comment by boegel** [comment]
What's wrong with the commit message? :)

**Comment by hajgato** [comment]
Its not OpenFOAM but Paraview....

**Comment by hajgato** [comment]
OpenFOAM eb-deps will come, though....

**Comment by boegel** [comment]
@hajgato: with `git commit --amend` you can rewrite commit messages (but it you do that now, you'll have to use `git push --force`)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c68d16e195f1872c83a0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/53eb2e690da2e25d8d8f for a full test report.

**Comment by boegel** [comment]
Looks great, works fine, going in. Thanks @hajgato!

**Pull request merged**
