### PR TITLE
{chem}[intel/2017a] NAMD v2.12

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires https://github.com/hpcugent/easybuild-framework/pull/2221

### CODE REVIEW

**Comment by boegel** [comment]
@akesandgren please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2532.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/dbf08ab769961a0c5e2109d01d338d2a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2049.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/255575723081c11dadc6a6c09227285c for a full test report.

**Comment by akesandgren** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @akesandgren!

**Pull request merged**
