### PR TITLE
{toolchain}[Cray*/5.2.40] HPL 2.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/5d838739391dd8bab2f8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/ad4ae5482326d8c92629 for a full test report.

**Comment by boegel** [comment]
@pforai: please review?

**Comment by pforai** [comment]
Test report by @pforai
**FAILED**
Build succeeded for 0 out of 6 (6 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/bed487ac9e5a0c103cc8 for a full test report.

**Comment by boegel** [comment]
@pforai: Sisu doesn't have `PrgEnv-*/5.2.40` (yet)

**Comment by pforai** [comment]
Yeah, I just noticed. Otherwise ready to go in!

**Comment by boegel** [comment]
Thanks for the review @pforai!

**Pull request merged**
