### PR TITLE
Add M4 as a dep of flex, this is required by some configure processes…

### PR DESCRIPTION
**Pull request by ocaisa**
…when working with `lex` (I saw it for `binutils`, also true for `GCC`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 15 out of 15 (14 easyconfigs in this PR)
node2601.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/693423d220eac8db9446a68a108b9914 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 14 (14 easyconfigs in this PR)
node2011.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2ded2d48704378fd8cc55491eb0e003e for a full test report.

**Comment by ocaisa** [comment]
Failures are related to `Lmod` problems

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (14 easyconfigs in this PR)
node2011.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/170fff093c2ddba12e6b6d85ae0413b5 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
