### PR TITLE
[ictce/5.3.0] gputools/0.28 for R/3.0.2 (REVIEW)

### PR DESCRIPTION
**Pull request by fgeorgatos**
Hi,
this one looks surprisingly simple but it proved to be very tedious business (spin-off of #282); reason is you MUST:

first, be careful with the exact git commit ID that corresponds to v0.28, this is not exactly a 1-1 relationship :-P

1) untar/retar manually the github tarball ; reason: incompatibility github vs R-untar, see easyblocks thread:
    https://github.com/hpcugent/easybuild-easyblocks/issues/313
2) you still need to supply full path from within R, eg. `dyn.load("/hello/big/world")`, while R_LIB does get populated
3) you need do this on GPU-equiped node, otherwise you receive an obscure message about missing `libcuda.so.1`
4) `e5cb024` works OK, while next commits (all called v0.28!) break down somewhere along the commit sequence. 
Let's focus on the `e5cb024` case for now, that should be the one to get out working first.
I need your help w. arguing the possible workarounds, I have a specified manual reproducible case at this point.

Signed-off-by: Fotis Georgatos <fotis.georgatos@uni.lu>

### CODE REVIEW

**Comment by boegel** [comment]
@fgeorgatos: ping on this?

I'm cleaning up the oldest PRs, in an effort to reduce the pile of open PRs.

Is this still relevant? Any idea of the amount of extra effort required to get it ready for merge?

**Comment by fgeorgatos** [comment]
I'd expect this to be mergeable, esp. if for ictce/5.5.0; where could we see the current build status?!

**Comment by boegel** [comment]
@fgeorgatos please take a look at https://github.com/fgeorgatos/easybuild-easyconfigs/pull/37

@fgeorgatos I'm still experiencing problems when testing this:

```
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Rgputools/0.28-ictce-5.3.0-e5cb024-R-3.0.2/gputools/libs/gputools.so':
  libcuda.so.1: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
```

Where is `libcuda.so.1` supposed to come from?

**Comment by gppezzi** [comment]
libcuda.so should be part of the nvidia driver

**Comment by fgeorgatos** [comment]
@boegel:

You really exercise my memory when you ask me something 3 years later :-p
Luckily, although I did not remember, I had already described the build process in this issue, see:
```
3) you need do this on GPU-equipped node, otherwise you receive an obscure message about missing libcuda.so.1
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
centos6 - Linux centos 6.5, AMD Opteron(tm) Processor 6136, Python 2.6.6
See https://gist.github.com/0406db964d7253de0932c8d17d191528 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
centos6 - Linux centos 6.5, AMD Opteron(tm) Processor 6136, Python 2.6.6
See https://gist.github.com/53044489eaf8d2803f7c7e8ef34c9f41 for a full test report.

**Comment by boegel** [comment]
Green lights everywhere, going in, thanks @fgeorgatos!

**Comment by fgeorgatos** [comment]
fyi. bug #1 made it's appearance again on my side ; here's how it manifests itself:
```
make: *** [rinterface.o] Error 1
ERROR: compilation failed for package ‘gputools’
 (at easybuild/tools/run.py:397 in parse_cmd_output)
== 2016-06-16 12:59:43,774 easyblock.py:2362 WARNING build failed (first 300 chars): cmd "R CMD INSTALL e5cb024.tar.gz   --library=/home/fgeorgatos
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installi
== 2016-06-16 12:59:43,775 easyblock.py:270 INFO Closing log for application name gputools version 0.28
```

I have my workaround, as described above, however I feel obliged to report...

**Comment by fgeorgatos** [comment]
btw. 
if people face trouble in the future, I recommend a simple test-case in the lines of:
```
library(gputools) 

set.seed(5446) 
p <- 20 
X <- matrix(rnorm(2^p),ncol = 2^(p/2)) 

system.time(d <- dist(X)) 
system.time(d <- gpuDist(X)) 
```
ref. http://dept.stat.lsa.umich.edu/~bobyuen/gpuwiki/

**Comment by boegel** [comment]
@fgeorgatos can you provide a more complete error/log for the unpack issue? what's the exact problem with the unpack? It seems we have something related in `ConfigureMake` that may provide a workaround.

**Comment by fgeorgatos** [comment]
@boegel: well, the case had been described here: 
https://github.com/hpcugent/easybuild-easyblocks/issues/313
IMHO, it is either incomplete implementation on the python untar2 side or, overshooting from github

**Pull request merged**
