### PR TITLE
add libibmap dependency for MVAPICH2 v2.2b

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

Missing `libibmad` dependency.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@SimonPinches did MVAPICH2 fail to build for you without this included?

Also, please provide the missing easyconfig for `libibmad` itself?

**Comment by boegel** [comment]
@SimonPinches can you share the errors you were getting without having `libibmad` included?

I'm not sure how wise it is to let EB handle this dep, it may be closely tied to the IB kernel drivers being used...

@damianam any idea about this?

**Comment by damianam** [comment]
On my opinion this should be an OS dependency. I am not sure if there are compatibility issues with specific driver versions, but it looks weird to me to install an IB library with EB in an IB-capable cluster. This should be at the core of the IB tools I assume.

**Comment by SimonPinches** [comment]
This is the output that leads to the failed build.  It seems as if `infiniband/mad.h` is not found on our system (with infiniband):

> checking for the InfiniBand includes path... default
checking for the InfiniBand library path... default
checking for library containing shm_open... -lrt
checking for library containing dlopen... -ldl
checking for library containing ibv_open_device... -libverbs
checking infiniband/verbs.h usability... yes
checking infiniband/verbs.h presence... yes
checking for infiniband/verbs.h... yes
configure: checking checking for infiniband umad installation...
checking for library containing umad_init... -libumad
checking infiniband/umad.h usability... yes
checking infiniband/umad.h presence... yes
checking for infiniband/umad.h... yes
configure: infiniband libumand found
checking for ibv_open_xrc_domain... no
configure: WARNING: support for XRC is disabled
checking whether to enable hybrid communication channel... no
configure: checking for RDMA CM support...
checking for library containing rdma_create_event_channel... no
configure: RDMA CM support disabled
configure: checking for Hardware multicast support enabled...
checking for library containing mad_get_field... no
checking infiniband/mad.h usability... no
checking infiniband/mad.h presence... no
checking for infiniband/mad.h... no
configure: error: 'infiniband/mad.h not found. Please retry with --disable-mcast'
 (at easybuild/tools/run.py:397 in parse_cmd_output)
== 2016-05-02 13:38:11,602 easyblock.py:2296 WARNING build failed (first 300 chars): cmd " ./configure --prefix=/work/imas/opt/EasyBuild/software/MVAPICH2/2.2b-GCC-4.9.3-2.25  --with-rdma=gen2  --with-thre
ad-package=pthreads --enable-fast --enable-shared --enable-sharedlibs=gcc --enable-static --enable-f77 --enable-fc --enable-cxx " exited with exitcode 1 and output:
./configure: li
== 2016-05-02 13:38:11,602 easyblock.py:267 INFO Closing log for application name MVAPICH2 version 2.2b

**Comment by boegel** [comment]
@SimonPinches as @damianam mentioned, it's probably better to resolve this via OS packages, here's what we have:

```
-bash-4.1$ rpm -qa | grep libibmad
libibmad-1.3.11.MLNX20150329.b2cb00f-0.1.x86_64
libibmad-devel-1.3.11.MLNX20150329.b2cb00f-0.1.x86_64
-bash-4.1$ rpm -q --filesbypkg libibmad-devel
libibmad-devel            /usr/include/infiniband/mad.h
libibmad-devel            /usr/include/infiniband/mad_osd.h
libibmad-devel            /usr/lib64/libibmad.so
```

**Comment by SimonPinches** [comment]
Okay, I'll try and resolve this at the OS level and let you know how I get on...

**Comment by SimonPinches** [comment]
I've resolved this at the system level by installing the missing `libimad*` rpms so I'll close this pull request.

**Pull request closed without merging**
