### PR TITLE
{tools}[intel/2017a] Davix 0.6.6 (REVIEW)

### PR DESCRIPTION
**Pull request by smoors**

### CODE REVIEW

**Comment by boegel** [comment]
OK, so Travis isn't picking up on this either... There must be something fishy with the last commits (although I don't know what, it's weird).

@smoors I think we have two options: you do a `git rebase` on current develop in your branch, and then do a `git push --force`, or you issue a new PR (yes, I know, another one...) using `eb --new-pr` for these 3 easyconfigs.

cc @wpoely86

**Comment by boegel** [comment]
w00! that worked :)

**Comment by smoors** [comment]
yeah there was a problem with my account, which was wrongly flagged by travis

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2444.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6d4baf413841b30e52f39da2e70d601b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2156.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2ccfbac4d914ea983e9fec0a68d2187b for a full test report.

**Comment by boegel** [comment]
@smoors Do you mind fixing this minor style issue?

I'm working towards enabling automatic style checks, so I want to avoid merging PRs that add new style issues:

```
$ eb --check-style --from-pr 4755
== temporary log file in case of crash /tmp/eb-8zZERR/easybuild-qt0QTy.log

*** WARNING: Using easyconfigs from unstable (pending/failed tests or merge conflict) PR #4755 ***

Running style check on 3 easyconfig(s)...
/tmp/eb-8zZERR/files_pr4755/d/davix/davix-0.6.6-intel-2017a.eb:15:47: E231 missing whitespace after ','
[FAIL] /tmp/eb-8zZERR/files_pr4755/d/davix/davix-0.6.6-intel-2017a.eb
[PASS] /tmp/eb-8zZERR/files_pr4755/g/gSOAP/gSOAP-2.8.48-GCCcore-6.3.0.eb
[PASS] /tmp/eb-8zZERR/files_pr4755/g/gtest/gtest-1.8.0-GCCcore-6.3.0.eb
ERROR: One or more style checks FAILED!
```

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
