### PR TITLE
{lang}[foss/2016a,goolf/1.7.20,intel/2016a] Python v2.7.11, Python v2.7.11, Python v2.7.11 - fix Cython download

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@verdurin please clarify the PR title?

It seems like we need to enforce this when existing easyconfigs are updated with `--new-pr`, since the default title is pretty meaningless...

Also, please change this consistently in *all* Python 2.7.11 easyconfigs that have `Cython`

**Comment by verdurin** [comment]
@boegel - the original `Cython` download link doesn't work anymore, so this switches it to pypi.

Happy to apply it the rest of them, though I can't test them all locally.

**Comment by boegel** [comment]
@verdurin since this only applies to the download, it's easy to test (`--stop fetch`)

**Comment by boegel** [comment]
Verified, going in, thanks @verdurin!

**Pull request merged**
