### PR TITLE
{tools}[dummy] Hadoop w/ native libs (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/563

### CODE REVIEW

**Comment by boegel** [comment]
@ehiggs, @wpoely86: please review?

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1d21a981372f347ef490 for a full test report.

**Comment by boegel** [comment]
Tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/563, looks great.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
going in, thanks for the review @wpoely86!

cc @stdweird, @ehiggs

**Pull request merged**
