### PR TITLE
add Autconf as build dep for GCCcore

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
required on older systems

@wpoely86 please review?

**Comment by boegel** [comment]
@wpoely86 ping?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node2641.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/356638e5f20a6deb10d3d6b594e0c74d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2054.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5911145a294c344261e7cf956dedbf54 for a full test report.

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Thanks @wpoely86!

**Pull request merged**
