### PR TITLE
{lib}[intel/2015a] pandas 0.16.2 w/ Python 2.7.10 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/17ae2b2d1992d05b6be2 for a full test report.

**Comment by ehiggs** [comment]
Is this just a rework of a previous version? [`setup.py`](https://github.com/pydata/pandas/blob/master/setup.py) says the following are required for install:

```
                         'install_requires': ['python-dateutil >= 2',
                                              'pytz >= 2011k',
                                              'numpy >= %s' % min_numpy_ver],
```

[`tox.ini`](https://github.com/pydata/pandas/blob/master/tox.ini) says the following deps are used:

```
deps =
    cython
    nose
    pytz>=2011k
    python-dateutil
    beautifulsoup4
    lxml
    openpyxl<2.0.0
    xlsxwriter
    xlrd
    six
    sqlalchemy
```

**Comment by boegel** [comment]
python-dateutil, pytz and numpy are available via the Python dep, the others are optional deps?

**Comment by ehiggs** [comment]
There others are optional. It's a pain to get all the optional dependencies if users won't use them. Like, who in hpc is going to parse an excel file (xlrd) or scrape html (beautifulsoup) (aside, I guess from information retrieval peeps?).

**Comment by boegel** [comment]
Exactly, so let's not, until we get a request for it.

**Comment by boegel** [comment]
Thanks for the review @ehiggs!

**Pull request merged**
