### PR TITLE
{vis}[foss/2016a] GL2PS v1.3.9 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
(created using `eb --new-pr`)
needs PR ~~#2743~~ and #2758

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato please sync with `develop` after merging #2832

**Comment by hajgato** [comment]
@boegel done

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2604.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/684f01646829343916d4be9332afd8f9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9da60b15b8cddee149a744585ab2cdaa for a full test report.

**Comment by boegel** [comment]
good to go once #2758 is merged

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
