### PR TITLE
{bio}[intel-2015b] GROMACS 5.1.1

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by hajgato** [comment]
`libxml2` is not picked by `CMake`, so tests are not made.

**Comment by boegel** [comment]
@hajgato: not sure what you mean with your last comment? Can you clarify?

**Comment by hajgato** [comment]
@boegel: 
from the `EasyBuild` log file:
```
...
-- Found LibXml2: /apps/brussel/ivybridge/software/libxml2/2.9.2-intel-2015b/lib/libxml2.a (found version "2.9.2")
-- Looking for xmlTextWriterEndAttribute in /apps/brussel/ivybridge/software/libxml2/2.9.2-intel-2015b/lib/libxml2.a
-- Looking for xmlTextWriterEndAttribute in /apps/brussel/ivybridge/software/libxml2/2.9.2-intel-2015b/lib/libxml2.a - not found
...
CMake Warning at CMakeLists.txt:543 (message):
  libxml2 not found.  Will build GROMACS without unit-tests.  This is not
  recommended, because the unit-tests help to verify that GROMACS functions
  correctly.  Most likely you are missing the libxml2-dev(el) package.  After
  you installed it, set GMX_BUILD_UNITTESTS=ON.
...
```

**Comment by hajgato** [comment]
@boegel 
Plus does not compile with `intel` compilers on `AMD Buldozer` architecture:
```
CMake Error at cmake/gmxManageSimd.cmake:187 (message):
  Cannot find compiler flags for 128 bit AVX with FMA support.  Use a newer
  compiler, or choose SSE4.1 SIMD (slower).
Call Stack (most recent call first):
  CMakeLists.txt:645 (gmx_manage_simd)
```

**Comment by boegel** [comment]
@hajgato Is trying with `intel/2016a` an option?

**Comment by hajgato** [comment]
@boegel: no
`Intel` compiler does not know that combination, so we wither force to use `SSE4.1` with `intel` compiler or we use the `GCC` version. 
form http://www.gromacs.org/Documentation/Installation_Instructions_5.0 
```
On the AMD Bulldozer architecture (Opteron 6200), AMD introduced fused multiply-add instructions and an "FMA4" instruction format not available on Intel x86 processors. Thus, on the most recent AMD processors you want to use gcc version 4.7 or later for best performance! The Intel compiler will only generate code for the subset also supported by Intel processors, and that is significantly slower.
```
If  the CPU is not AMD Bulldozer (or newer), we do not have to care.

**Comment by boegel** [comment]
@hajgato: so, we need to make https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/toolchains/compiler/inteliccifort.py#L73 smarter?

**Comment by hajgato** [comment]
@boegel: It will not help. Intel compilers does not generate `FMA4` code at all, because none of the `Intel` CPUs understand that. From `Haswell` architecture, Intel implemented the `FMA3`  which virtually knows the same than `FMA4`, but not binary compatible. AMD started to implement `FMA3` in 2nd generation Bulldozer and Piledriver architectures, but it is unlikely that Intel would implement `FMA4` at all, since `FMA3` is already there. 
GROMACS searches for the best solution for each CPU, using individual switches for CPU instruction subsets (like for example `-mavx`, etc. We use `-xHost` for that purpose, I do not understand the developers intention to check individually the microcode-subset options.
We have to force `GROMACS` to use `SSE4.1` with Intel compilers if the CPU is 1st Gen Bulldozer or Piledriver from the `GROMACS` easybuild, or we have to make `GROMACS` to use `-xHost` instead of individual CPU instruction subsets in the case of `Intel` compilers.

**Comment by verdurin** [comment]
Worth noting that I've submitted #2580 for those without Intel.

**Comment by boegel** [comment]
@hajgato: ping on this?

**Comment by hajgato** [comment]
@boegel Actually, I do not work on this anymore. Shoud I close this PR?

**Comment by boegel** [comment]
I think it would be interesting to figure out the issue with the tests?

@verdurin: does #2580 also suffer from this?

**Comment by verdurin** [comment]
@boegel: Do you mean the libxml2 problem? If so, yes, that does happen with my version.

This has been brought up on the mailing list, and is due to CMake misbehaviour.

The suggestion is to build libxml2 without Python, zlib or lzma support.

**Comment by boegel** [comment]
@verdurin can you detail on the CMake issue?

**Comment by verdurin** [comment]
@boegel  - see this mailing list thread https://mailman-1.sys.kth.se/pipermail/gromacs.org_gmx-users/2016-February/103558.html and specifically this message https://mailman-1.sys.kth.se/pipermail/gromacs.org_gmx-users/2016-February/103650.html in which the conclusion is:

```
Your suggestions let me

make and make install without errors  gromacs-5.1.1.
For libxml2:
./configure --prefix=/home/ikosh/programs/autotools-bin  --without-python --without-zlib --without-lzma

cmake -DCMAKE_C_COMPILER=mpixlc_r -DCMAKE_CXX_COMPILER=mpixlcxx_r -DCMAKE_TOOLCHAIN_FILE=BlueGeneQ-static-XL-C -DGMX_SIMD=IBM_QPX     -DBUILD_SHARED_LIBS=OFF -DGMX_XML=OFF -DGMX_PREFER_STATIC_LIBS=ON  -DCMAKE_C_FLAGS="-O3 -qsmp=omp -qarch=qp -qtune=qp" -DCMAKE_INSTALL_PREFIX=/gpfs/vesta-home/ikosh/gromacs_rc/install
```

**Comment by verdurin** [comment]
Hmm - first attempt at requiring a build of `libxml2` with the configure settings listed in the previous comment has not fixed the problem with unit tests.

**Comment by boegel** [comment]
I don't think that building a crippled `libxml2` to dance around an issue with CMake is a very good solution anyway...

**Comment by verdurin** [comment]
Agreed. 

Up to you how you wish to proceed, @boegel

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2160.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/94e2ee7c045dca60bc52e6e716c4e90b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2543.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/51b189877c7fd9ab8f749c5298245249 for a full test report.

**Comment by boegel** [comment]
@hajgato please merge https://github.com/hajgato/easybuild-easyconfigs/pull/34 to sync this with `develop` (& trigger Travis)?

I looked into the problem with libxml2 & the GROMACS tests, and it seems it can be fixed by making sure that CMake also uses `-lz -llzma` when it checks for `libmxl2`, it seems to assume these are statically linked into the `libxml2.a` but they're not (maybe they should be...).

Currently, we're not listing `XZ` as a dependency for `libxml2`, but it'll be happily picked up from the OS if it's there (and dynamically linked, by default).

I don't think this problem should block the PR though, it should be handled via a separate issue.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2040.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/61ab9de7cfcfe35dc064805e0a328f7d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2040.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d1f6b18264c67f51c821aa90169b25c5 for a full test report.

**Comment by boegel** [comment]
tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/960, good to go, thanks @hajgato!

**Pull request merged**
