### PR TITLE
A few new easyconfig files added 

### PR DESCRIPTION
**Pull request by robqiao**
easyconfig added:
Picard 2.2.4 
PyOpenGL
lynx
prodigal

### CODE REVIEW

**Comment by boegel** [comment]
@robqiao Do you mind updating the PR title to better reflect what is included in this PR?

Also, are these applications related somehow? If not, that's fine, but let's not make this PR any bigger and get it merged (getting moving target merged is a bit difficult ;-)).

@migueldiascosta Are you up for giving this a thorough review?

**Comment by robqiao** [comment]
@boegel PR title renewed, there are most independent, sorry about the mess, will contribute in a new PR.

**Comment by boegel** [comment]
@robqiao Are you up for looking into the style remarks?

**Comment by robqiao** [comment]
@boegel surely will try to get it up in the next couple of days :) sorry for the delay

**Comment by robqiao** [comment]
@boegel @migueldiascosta format updated, thanks for the review. thumb up

**Comment by robqiao** [comment]
@boegel will you be able to merge this PR?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2677.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/68ab5f9f7ef7bec58e45d5dbac0918b7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2003.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1db1a9381966fb266d2bc02100b9dec6 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @robqiao!

**Pull request merged**
