### PR TITLE
Update picard to 2.1.0 including move to GitHub

### PR DESCRIPTION
**Pull request by verdurin**
Update dependency to Java 1.8.0.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/375a9d8ef7d06e007736 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Comment by boegel** [comment]
For some reason this is failing on me now...

```
Sanity check failed: no file of ('picard-2.1.0.jar',) in ...
```

with:

```
$ ls $EASYBUILD_PREFIX/software/picard/2.1.0
htsjdk-2.1.0.jar  libIntelDeflater.so  picard.jar  picard-lib.jar
```

This probably means that this PR was tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/796, which is currently not merged yet into `develop`...

Thoughts @verdurin? Did you test this on your end?

**Comment by verdurin** [comment]
@boegel - hmm. Looks like this is one I didn't test locally. Bah.

It fails for me too.

How would you like me to proceed?

**Comment by boegel** [comment]
@verdurin: I'll get https://github.com/hpcugent/easybuild-easyblocks/pull/796 merged ASAP, which is the proper fix. No harm done.

**Pull request merged**
