### PR TITLE
use --with-verbs rather than the deprecated --with-openib for OpenMPI

### PR DESCRIPTION
**Pull request by boegel**
fix for #712

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2c5d1027a57931fdc397 for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
The wpoely86 seal of approval has been attached to this PR :white_check_mark:

**Comment by boegel** [comment]
Thanks @wpoely86! :cookie:

**Pull request merged**
