### PR TITLE
{vis}[foss-2015b] X11 WIP

### PR DESCRIPTION
**Pull request by verdurin**
First run at providing X11 for foss-2015b, as required by #2653

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by verdurin** [comment]
Okay, what's the best way to proceed here, @boegel? I fixed an inconsistency with `ncurses` 5.9 versus 6.0, but now that problem is occurring throughout `foss-2015b` when testing this PR.

Ought I to re-work them all to use 5.9?

**Comment by boegel** [comment]
@verdurin we switched to ncurses 6.0 in the `2016a` toolchains; for `foss/2015b` you should stick to 5.9...

**Comment by boegel** [comment]
@verdurin Do you think this is still relevant/useful?

**Comment by verdurin** [comment]
@boegel - no, this has been superseded now. Closing.

**Pull request closed without merging**
