### PR TITLE
{compiler}[dummy] GCC 4.9.4 w/ binutils 2.25

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2408.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c76854db6650d4692429ef4a0b7ed1c7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1595917217094314738c99f882e8dc79 for a full test report.

**Comment by boegel** [comment]
@wpoely86 please review

**Comment by wpoely86** [comment]
there is still the unresolved issue with flex but that shouldn't hold this back

**Comment by boegel** [comment]
@wpoely86 what issue exactly?

**Comment by wpoely86** [comment]
See #3405 (needs static linking)

**Comment by boegel** [comment]
@wpoely86 ah, wait, you mean #3409 ?

**Comment by wpoely86** [comment]
a yes

**Comment by boegel** [comment]
@wpoely86 OK, I agree that this shouldn't block this PR, so going in, thanks for the review!

**Pull request merged**
