### PR TITLE
{bio}[foss/2015a, intel/2015a] Minimac 3 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
@pescobar: please review/test

### CODE REVIEW

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/69c23bb3128d02d395df for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ca1e8fcfa3f88046d1b8 for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/243f1ce4e096f227582e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/15c1626500722b867f44 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/22eeb0668d7f4d4ac22e for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 2 out of 11 (2 easyconfigs in this PR)
Linux centos 6.6, Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz, Python 2.6.6
See https://gist.github.com/3e08b5e8321f6fea9fa0 for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos 6.6, Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz, Python 2.6.6
See https://gist.github.com/b07d7bf86abc6e8e9a7d for a full test report.

**Comment by boegel** [comment]
Going in, thanks for testing everyone!

**Pull request merged**
