### PR TITLE
{devel}[intel/2015a] libX11 + deps (REVIEW)

### PR DESCRIPTION
**Pull request by gjbex**
Latest versions of
* libX11
* inputproto
* kbproto
* libXau
* libpthread-stubs
* libxcb
* xcb-proto
* xextproto
* xproto
* xtrans

### CODE REVIEW

**Comment by gjbex** [comment]
Test report by @gjbex
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.6
See https://gist.github.com/2e5be67e3e93a54fb0aa for a full test report.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@gjbex: this overlaps quite a bit with #1323, which is on hold due to build issues with `libxcb` in #1321 where `Autoconf`/`Automake` were added a build deps, since `autogen.sh` was being run before running `./configure` (via `preconfigopts`)

The `preconfigopts` line is no longer in your `libxcb` easyconfig, so I assume you removed it? I must admit I'm not 100% sure anymore why the `autogen.sh` is there, maybe it's OK to just drop it, I'd have to dive into the logs...

**Comment by gjbex** [comment]
No, I didn't remove the preconfigopts line.  This file was probably adapted from its 2014b counterpart, so somebody else must have done so.

**Comment by boegel** [comment]
OK, I'll try to track it down when/where it's really needed.

I'd prefer dropping it if we can, so your PR is likely to go in before #1323 (since I can fix the latter myself after this one is merged).

**Comment by boegel** [comment]
@wpoely86: care to look into this, and give this a test run?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/0418309ac1e833b30dde for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c4a381ca490345191e66 for a full test report.

**Comment by boegel** [comment]
OK, looking good, seems like the `autogen.sh` isn't needed indeed.

Thanks for tackling this @gjbex, and for review/testing @wpoely86!

**Pull request merged**
