### PR TITLE
{tools}[intel/2015a] IPython 3.2.1 w/ Python 2.7.10 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
cc @ehiggs

### CODE REVIEW

**Comment by ehiggs** [comment]
:+1: :snake:

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a0e52d928b076d9771ed for a full test report.

**Comment by boegel** [comment]
@ehiggs: one of the tests run by `iptest` fails with

```
======================================================================
ERROR: test that `ipython console` starts a terminal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gpfs/scratch/projects/project_gpilot/vsc40023/software/Python/2.7.10-intel-2015a/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/gpfs/scratch/projects/project_gpilot/vsc40023/software/IPython/3.2.1-intel-2015a-Python-2.7.10/lib/python2.7/site-packages/IPython/testing/decorators.py", line 225, in skipper_func
    return f(*args, **kwargs)
  File "/gpfs/scratch/projects/project_gpilot/vsc40023/software/IPython/3.2.1-intel-2015a-Python-2.7.10/lib/python2.7/site-packages/IPython/terminal/console/tests/test_console.py", line 29, in test_console_starts
    p, pexpect, t = start_console()
  File "/gpfs/scratch/projects/project_gpilot/vsc40023/software/IPython/3.2.1-intel-2015a-Python-2.7.10/lib/python2.7/site-packages/IPython/terminal/console/tests/test_console.py", line 77, in start_console
    idx = p.expect([r'In \[\d+\]', pexpect.EOF], timeout=t)
  File "/gpfs/scratch/projects/project_gpilot/vsc40023/software/IPython/3.2.1-intel-2015a-Python-2.7.10/lib/python2.7/site-packages/IPython/external/pexpect/_pexpect.py", line 1451, in expect
    timeout, searchwindowsize)
  File "/gpfs/scratch/projects/project_gpilot/vsc40023/software/IPython/3.2.1-intel-2015a-Python-2.7.10/lib/python2.7/site-packages/IPython/external/pexpect/_pexpect.py", line 1466, in expect_list
    timeout, searchwindowsize)
  File "/gpfs/scratch/projects/project_gpilot/vsc40023/software/IPython/3.2.1-intel-2015a-Python-2.7.10/lib/python2.7/site-packages/IPython/external/pexpect/_pexpect.py", line 1568, in expect_loop
    raise TIMEOUT(str(err) + '\n' + str(self))
TIMEOUT: Timeout exceeded.
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2bf9173078f9f30bc5c5 for a full test report.

**Comment by boegel** [comment]
Works fine on top of https://github.com/hpcugent/easybuild-framework/pull/1366

**Comment by boegel** [comment]
Thanks for the review @ehiggs!

**Comment by boegel** [comment]
When trying to install this in production, I ran into failing test in `iptest`, like:

```
ERROR: Can notebook names include accents?
----------------------------------------------------------------------
Traceback (most recent call last):
   File "/apps/gent/SL6/sandybridge/software/IPython/3.2.1-intel-2015a-Python-2.7.10/lib/python2.7/site-packages/IPython/nbconvert/tests/test_nbconvertapp.py", line 189, in test_accents_in_filename
     self.create_empty_notebook(u'nb1_análisis.ipynb')
   File "/apps/gent/SL6/sandybridge/software/IPython/3.2.1-intel-2015a-Python-2.7.10/lib/python2.7/site-packages/IPython/nbconvert/tests/base.py", line 105, in create_empty_notebook
     with io.open(path, 'w', encoding='utf-8') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 6: ordinal not in range(128)
```

It seems that using `export LC_ALL=en_US.UTF-8` fixed this (was `LC_ALL=C`).

**Comment by boegel** [comment]
Very relevant to the issue above: https://bugs.python.org/issue19977

**Pull request merged**
