### PR TITLE
{lang}[intel/2015b] Python 2.7.11 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
all Python packages included as extensions have been updated to the latest version

(I stuck to v1.x for mpi4py, since mpi4py 2.0 has API changes)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ffea4b1ace1f29cfbdac for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/371ed314a88697c6d33c for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6ff41a21612c81257c78 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/72ac09b9297f4d627f35 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0e87c353ad6ca6675f4d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/05eaa283ae855275515c for a full test report.

**Comment by wpoely86** [comment]
looks fine but, I would wait for the `2016a` toolchains and then use `ncurses` 6.

**Comment by boegel** [comment]
@wpoely86: hmm, yeah, maybe that's better indeed...

**Comment by boegel** [comment]
@wpoely86: or, well, it doesn't really matter?

this can go in, and we can use ncurses 6 in the `2016a` easyconfigs?

**Comment by wpoely86** [comment]
Well, it's not impossible but didn't we have a policy to stick to a version for a toolchain version?

**Comment by boegel** [comment]
We agreed on switching to ncurses 6 with the `2016a` toolchains, yes, this PR is not breaking that?

**Comment by wpoely86** [comment]
no, but I meant python itself.

**Comment by boegel** [comment]
@wpoely86: no, there's no such policy, we just go with latest and greatest there, there are good reasons to switch to Python 2.7.11 (bug fixes, performance improvements)

**Comment by hajgato** [comment]
@boegel: do not forget the python-2.7.9-python-2.7.10 dependency hell in the case of 2015a toolchain. 
If we put pyhton-2.7.11 with intel-2015b, then none of my `OpenFOAM` pull request will be accepted without bumping them to `Python 2.7.11`, which is a considerable amount of work.
So I think we can wait 20 days with 2.7.11 and put in with a `2016a` toolchain.

**Comment by boegel** [comment]
@hajgato: sure we'll accept the PR, but only requesting people to bump to 2.7.11 for 2016a & co makes sense

for 2015a (or b?), we asked to bump to 2.7.10 because that was added a lot earlier

**Comment by boegel** [comment]
I feel this is important enough to go in, it doesn't mind people will be forced to pick up on it yet, we can wait with switching to using Python 2.7.11 as a dep when we have the `2016a` toolchains.

**Pull request merged**
