### PR TITLE
add easyconfig files for IMa2

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by JensTimmerman** [comment]
@boegel good to go!

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/edcdfb8f519ac589a428 for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @JensTimmerman!

**Pull request merged**
