### PR TITLE
Orca 3.0.3

### PR DESCRIPTION
**Pull request by scintimandrion**
New easyconfig for ORCA 3.0.3.

### CODE REVIEW

**Comment by scintimandrion** [comment]
Yes.

**Comment by boegel** [comment]
@scintimandrion: you're renaming/adjusting an existing easyconfig file, please just add a *new* easyconfig file instead

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by scintimandrion** [comment]
Ah, I had split ORCA-3.0.3 off from ORCA-3.0.2 rather than starting it from develop. I'll see if I can rectify that.

**Comment by scintimandrion** [comment]
In fact, I'll just close this PR and start over.

**Pull request closed without merging**
