### PR TITLE
include missing libxml2 dep in GLib easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
fix for issue uncovered in #1661

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 14 out of 34 (28 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6897b92989f98d6c346e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 17 out of 29 (23 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8f2dd050a8d421f88b7d for a full test report.

**Comment by boegel** [comment]
failure because #1576 isn't merged in yet

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 23 out of 23 (23 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2b7be97e5bab6e6a4eba for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review, and maybe submit a test report for one of the GLib easyconfigs touched in here on Debian?

Should be good to go imho.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/2a2d4b65bfb1ca96f0b1 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/75bc7531deebd5ca06f6 for a full test report.

**Comment by boegel** [comment]
Thanks @wpoely86!

Going in...

**Pull request merged**
