### PR TITLE
{chem}[intel/2015a] PSI 4.0b5 w/ higher max. angular momentum + Python 2.7.10, Boost 1.59.0 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires #1854

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/078c5ac640db3f77e3f0 for a full test report.

**Comment by boegel** [comment]
The `-D` syntax doesn't work here, since CMake is not being used here yet...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/65158d7ad0b902de520f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/cc36f15f910a5a0defcb for a full test report.

**Comment by boegel** [comment]
@wpoely86: PSI 4.0b5 with Boost 1.59.0 works fine...

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks for the review & help with this @wpoely86!

**Pull request merged**
