### PR TITLE
add bioarchive source URL as backup for Bioconductor pkgs

### PR DESCRIPTION
**Pull request by boegel**
@pescobar: please review?

cc @ehiggs

### CODE REVIEW

**Comment by rjeschmi** [comment]
looks fine. I don't have a good way to test this right now though...

**Comment by boegel** [comment]
@rjeschmi: please review?

**Comment by boegel** [comment]
@rjeschmi: since this only adds another source URL, I don't think this needs a lot of testing?

**Comment by boegel** [comment]
The extra source URL doesn't seem to make much of a difference...

Since these easyconfigs for Bioconductor 3.1 have been merged in, the following packages have been version-bumped:

* S4Vectors:, 0.6.3 (was 0.6.1)
* Biostrings: 2.36.2 (was 2.36.1)
* BiocInstaller: 1.18.4 (was 1.18.3)
* limma: 3.24.14 (was 3.24.13)
* BSgenome: 1.36.3 (was 1.36.2)

(see also #1828)

But the sources are not available through https://bioarchive.galaxyproject.org either...
So, there's little point in adding this extra source URL.

cc @pescobar

**Pull request closed without merging**
