### PR TITLE
{lang}[intel/2015b] R 3.2.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
depends on #1725 for libreadline, zlib, Tcl, Tk, ncurses easyconfigs

### CODE REVIEW

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 5 out of 8 (6 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/148091133c6027263b93 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5145541bacb9b18161aa for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 7 out of 8 (6 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/88801013aa834e7fd5af for a full test report.

**Comment by backelj** [comment]
Test report by @backelj
**FAILED**
Build succeeded for 4 out of 8 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/c7fefc7ed1ab50a90422 for a full test report.

**Comment by boegel** [comment]
download link for BiocInstaller 1.16.3 is broken...

see https://support.bioconductor.org/p/69175/

**Comment by backelj** [comment]
Test report by @backelj
**FAILED**
Build succeeded for 2 out of 4 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/45cbfefbc51bf04d0ed3 for a full test report.

**Comment by boegel** [comment]
@hajgato, @backelj: bumped version of BiocInstaller extension (again), to 1.16.5 (cfr. https://support.bioconductor.org/p/69175), please retest?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/82351dd76c24919fa237 for a full test report.

**Comment by backelj** [comment]
Test report by @backelj
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/016dbf0359bfcca5980a for a full test report.

**Comment by boegel** [comment]
@backelj: this should be looked into:

```
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: Tcl/Tk support is not available on this system
Error : package ‘tcltk’ could not be loaded
ERROR: lazy loading failed for package ‘widgetTools’
```

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 8 out of 8 (6 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/6ee7be09fe7662b9d2da for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6f8cb85c6f5cad112924 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1e6d83ade87ae47fe0ab for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 10 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/1b2bb13b85e62631e624 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3820df56f80e3b1054c9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/16d9db9d3fa255f7a04a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/100f9fb75b03e52294d2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/95d5b5c31ca6ef43bc23 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7b8284fac0e546d594b7 for a full test report.

**Comment by boegel** [comment]
Fail on the RHEL6@Haswell systems:

```
checking for X... libraries , headers 
checking GL/gl.h usability... no
checking GL/gl.h presence... no
checking for GL/gl.h... no
checking GL/glu.h usability... no
checking GL/glu.h presence... no
checking for GL/glu.h... no
configure: error: missing required header GL/gl.h
ERROR: configuration failed for package ‘rgl’
```

**Comment by boegel** [comment]
Failed build on RHEL6@Haswell system is caused by missing OpenGL/Mesa required for rgl package, since it's not provided by the OS there.

I've opened #1935 to discuss this and figure out the best solution (I'm no longer 100% convinced that we should be spending time on building Mesa, and including it as a dep for R, for example), I won't block PR over this.

**Comment by boegel** [comment]
Thanks for reviewing/testing this everyone!

**Comment by backelj** [comment]
Test report by @backelj
**SUCCESS**
Build succeeded for 13 out of 13 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/dfa51878e130e8841555 for a full test report.

**Pull request merged**
