### PR TITLE
enable pic option in expat easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 17 out of 18 (18 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/b41ced5565b042f0f39f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6fe28b644e1b4bf6eaa4 for a full test report.

**Comment by fgeorgatos** [comment]
just for the record: what triggered the change?

**Comment by boegel** [comment]
@fgeorgatos: #1529

**Comment by boegel** [comment]
going in, just a minor hickup in the test report, but all is well, thanks for the review @wpoely86!

**Pull request merged**
