### PR TITLE
New EasyConfig for freetype2.6.2 with the foss-2015a toolchain

### PR DESCRIPTION
**Pull request by valtandor**
Required as part of the GRASS 7.0.2 dependency tree. Depends on libpng, an EasyConfig for which is included to reduce false failures during testing.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@valtandor: needs sync with `develop` now that #2416 is merged

**Comment by valtandor** [comment]
Synced with develop.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/92991bf8c67d8e9ee74a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
