### PR TITLE
Added new Go versions 1.4.2 and 1.5

### PR DESCRIPTION
**Pull request by cfenoy**
1.4.2 is needed to compile the latest (1.5) version

### CODE REVIEW

**Comment by cfenoy** [comment]
Needs hpcugent/easybuild-easyblocks#683

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
OK, these look perfect, I'll test them as soon as the changes to the Go easyblock are finalised, thanks @cfenoy!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3aaa90b42efc02b14d9f for a full test report.

**Comment by boegel** [comment]
Good to go now https://github.com/hpcugent/easybuild-easyblocks/issues/683 is merged, thanks @cfenoy!

**Pull request merged**
