### PR TITLE
{bio}(foss/2015b) Samtools 1.3 (REVIEW)

### PR DESCRIPTION
**Pull request by nathanhaigh**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/78191c2ad551873df6d1 for a full test report.

**Comment by boegel** [comment]
Test build is failing on my end with:

```
gcc  -o misc/ace2sam misc/ace2sam.o -lz -ldl 
gcc -g -Wall -O2 -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc  -o misc/maq2sam-long misc/maq2sam-long.o -lz -ldl 
misc/ace2sam.c:94: error: undefined reference to 'gzopen64'
collect2: error: ld returned 1 exit status
make: *** [misc/ace2sam] Error 1
gcc -g -Wall -O2 -I.  -c -o cram/cram_decode.o cram/cram_decode.c
make: *** Waiting for unfinished jobs....
misc/maq2sam.c:193: error: undefined reference to 'gzopen64'
collect2: error: ld returned 1 exit status
make: *** [misc/maq2sam-long] Error 1
```

Other SAMtools v1.x easyconfigs have `parallel = 1` included, but this one does not, maybe that's the culprit?

**Comment by nathanhaigh** [comment]
I think the culprit is the way SAMtools uses/finds zlib. SAMtools <= 1.1 have a different `Makefile` to which a easybuild applies a patch.

Can you also test PR #2255?

These are probably relevant:
  * easybuild patch for SAMtools 1.1: https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/s/SAMtools/SAMtools-1.1_Makefile.patch
  * SAMtools bug report: https://github.com/samtools/samtools/issues/493

**Comment by boegel** [comment]
test for #2255 is on it's way
we're using the 1.2 version of that patch for SAMtools 1.2, so you may be right

if the 1.2 version of the patch still applies for 1.3, just use that?

**Comment by nathanhaigh** [comment]
Just having a look at the SAMtools 1.3 release notes. It has this to say:

> Samtools now has a configure script which checks your build environment and facilitates choosing which HTSlib to build against. See INSTALL for details.

I'll take a closer look on Monday as the 1.2 patch may not apply.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f9276daf2e571008f42f for a full test report.

**Comment by boegel** [comment]
@nathanhaigh: last test report is one a system with a more recent zlib, which seems to confirm your suspicion

**Comment by nathanhaigh** [comment]
Just having a look at the Makefile in 1.3. Are there any general guidelines on what sort of stuff might need to be changed so it plays more nicely with the easybuild system?

**Comment by boegel** [comment]
If they support using `./configure` now, we should definitely try that. If you want to patch the Makefile, take a look at the existing patches for older versions?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d158dfd124c037185446 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/546bb3cda497d62f22a4 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @nathanhaigh!

**Pull request merged**
