### PR TITLE
{data} [foss-2014b] Netcdf C, C++, Fortran (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 4 out of 50 (13 easyconfigs in this PR)
Linux centos 6.6, Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz, Python 2.6.6
See https://gist.github.com/02306559177a1977a91a for a full test report.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@rjeschmi: up for retesting this? You submitted a failed test report at some point.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e6c66128158fb5d3ee5b for a full test report.

**Comment by boegel** [comment]
@hajgato: please sync with current `develop`, and also apply the patch in the netCDF 4.3.2 easyconfig that uses `foss/2015a`

Looks good to go otherwise.

**Comment by hajgato** [comment]
@boegel synced with current develop, foss/2015a version updated

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (14 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8a6812940b1501631d6b for a full test report.

**Comment by boegel** [comment]
Looking great, merging it, thanks @hajgato!

**Pull request merged**
