### PR TITLE
{lib}[GCC/4.9.3-2.25] Guile v2.0.11 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2476.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0c552708622ac782b2c35a2b766c2087 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/54862f4416e57e2d95599104f961d49d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2476.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/961325837e6ee530263fc073f79cd187 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/387015e09019026f5f2b465ed2ab3db0 for a full test report.

**Comment by wpoely86** [comment]
why dummy?

**Comment by boegel** [comment]
@wpoely86 It intend to use this as a dependency for Guix, where the intention is to (maybe) use it to run EasyBuild in an isolated environment. So, we should be able to combine it with any other toolchain...

**Comment by wpoely86** [comment]
Did we create gcccore for this?

**Comment by boegel** [comment]
@wpoely86 GCCcore doesn't allow to combine with *any* toolchain

**Comment by wpoely86** [comment]
Well, then we should adjust it. I don't like using dummy for something like this.

**Comment by boegel** [comment]
Adjust what & how?

Either you rely on the system compiler by using the `dummy` toolchain and you get a build that should be compatible with any toolchain being used, or you don't, and you match the (sub)toolchain.

There's no way in between?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 21 (4 easyconfigs in this PR)
centos6 - Linux centos 6.5, AMD Opteron(tm) Processor 6136, Python 2.6.6
See https://gist.github.com/1c6fcf2c0cb46ff329cba9a29dd0c8ab for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 21 (4 easyconfigs in this PR)
centos7 - Linux centos linux 7.1.1503, AMD Opteron(tm) Processor 6136, Python 2.7.5
See https://gist.github.com/faa33cc4fed54536b09ce7b338734488 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2ff9fd3cff6f94109dcf0c088ffa19ec for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2525.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b15ee49437c59cdcf27c2b3ff5a05278 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
centos6 - Linux centos 6.5, AMD Opteron(tm) Processor 6136, Python 2.6.6
See https://gist.github.com/b7d9752ed0ad0a000163d5f5944a5212 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
centos7 - Linux centos linux 7.1.1503, AMD Opteron(tm) Processor 6136, Python 2.7.5
See https://gist.github.com/3d99d02990f76f9752cfbad5e5d35fac for a full test report.

**Comment by boegel** [comment]
Updated to use proper toolchain and retested, so good to go.

Thanks for the review @wpoely86, and good point on pointing out that we shouldn't use `dummy` here...

**Pull request merged**
