### PR TITLE
remove custom exts_filter in various easyconfigs for (bundles of) Python packages

### PR DESCRIPTION
**Pull request by boegel**
similar fix to #2683, but lower impact since a Python dependency is actually included for these

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
node2090.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6ddb398b534fa1b1094d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2668.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a77fe6a9a68b5d4696a2 for a full test report.

**Comment by boegel** [comment]
The issue with Sphinx on SL6 is not caused by the changes made here, see also https://github.com/hpcugent/easybuild-easyconfigs/issues/644 .

So, going in, thanks for the review @wpoely86!

**Pull request merged**
