### PR TITLE
{vis}[intel/2015b] Nipye 0.11.0 + traits 4.5.0 w/ Python 2.7.10 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f29cc28701a46c034630 for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
