### PR TITLE
clean up libxml2 easyconfigs according to updated libxml2 easyblock

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-easyblocks/pull/984

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 please review ;)

**Comment by wpoely86** [comment]
@
:+1:

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
daint103 - Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/34b499afc1ccdef90f0608e72080b074 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 22 out of 22 (16 easyconfigs in this PR)
node2494.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e5b21d914d9432d80c33799361804d2f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 63 out of 63 (62 easyconfigs in this PR)
node2028.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/618d275bddbc94afec53b14dbd8a3455 for a full test report.

**Comment by boegel** [comment]
tested  all existing easyconfigs on top of https://github.com/hpcugent/easybuild-easyblocks/pull/984, good to go, thanks @wpoely86!

**Pull request merged**
