### PR TITLE
Add jupyterhub (depends on IPython 5.0.0).

### PR DESCRIPTION
**Pull request by gatagat**
Add easybuild support for jupyterhub.

This script depends on the IPython 5.0.0 in #3368.

### CODE REVIEW

**Comment by gatagat** [comment]
Just realized this still misses the configurable-http-proxy. I'll be adding it in a minute.

**Comment by boegel** [comment]
@gatagat please review/merge https://github.com/gatagat/easybuild-easyconfigs/pull/3 which deals with some style issues

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2408.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/74a18d997806c1638b60e450a6b1f1fa for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2009.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8361b925f20d2a7c68c442b15b9b6fe1 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @gatagat!

**Pull request merged**
