### PR TITLE
Update OpenSSL to 1.0.1r

### PR DESCRIPTION
**Pull request by verdurin**
Required by a new EB I'm working on.

I needed to increase the download timeout when testing locally, possibly because I have IPv6 and that download was particularly slow.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: OK to test

**Comment by boegel** [comment]
Note that we recommend to rely on the OpenSSL provided by the OS, so packages benefit from from security fixes/updates. Doesn't mean this can't go in though.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2bddde06f69c29153f1b for a full test report.

**Comment by boegel** [comment]
hmm, download fail?

**Comment by verdurin** [comment]
As I said in the opening comment, I had to increase the download timeout when testing at home. Maybe it's slow for everything, not just IPv6.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6dccc368f46b3bbc0386 for a full test report.

**Comment by boegel** [comment]
OK, seems to work, going in, thanks @verdurin!

**Pull request merged**
