### PR TITLE
tabix 0.2.6 easyconfigs

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**FAILED**
Build succeeded for 1 out of 2
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/9e586a8399d8a18c7d3d for a full test report.

**Comment by fgeorgatos** [comment]
@pescobar: please look at #1059 for possible adjustments...

**Comment by fgeorgatos** [comment]
minor changes needed here, put this in REVIEW plz!

**Comment by verdurin** [comment]
Isn't this redundant, given that `tabix` is provided by `HTSLib`?

**Comment by boegel** [comment]
(open/close to trigger Travis)

**Comment by boegel** [comment]
@verdurin well, doesn't hurt to have this stand-alone too, in case people can use it stand-alone?

**Comment by verdurin** [comment]
@boegel no harm, of course, but I don't know why you'd do that.

Anyway, I was just on an "old PR" binge.

**Comment by boegel** [comment]
@pescobar this needs a sync with current `develop`...

**Comment by pescobar** [comment]
ups, I messed up something with git while merging dev. I opened a new PR https://github.com/hpcugent/easybuild-easyconfigs/pull/3164

closing this one

**Pull request closed without merging**
