### PR TITLE
{math}[intel/2015b] numpy 1.10.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-easyblocks/pull/757

cc @gppezzi

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c012d1469785c43c36a0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/299c643eae68e479a12f for a full test report.

**Comment by boegel** [comment]
tests for scipy fail when built on top of this numpy...

I'll flesh out the scipy easyconfig (and report the test issue upstream).

**Comment by boegel** [comment]
scipy easyconfigs fleshed out into #2181

**Comment by boegel** [comment]
going in, thanks for the review @wpoely86!

**Pull request merged**
