### PR TITLE
STREAM builds using ~56GiB and ~111GiB

### PR DESCRIPTION
**Pull request by itkovian**

### CODE REVIEW

**Comment by boegel** [comment]
@itkovian can you add an easyconfig using `intel/2016b` too while you're at it?

**Comment by itkovian** [comment]
As in a different file?

**Comment by boegel** [comment]
@itkovian yes, copy the existing one, tweak filename and `toolchain` spec

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2623.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e97bbf2f90f95682c9ef2c87ec35430b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
gligar03.gligar.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e9e88a14319309c32987dbffb8d0e394 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2623.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/733af146382b18f3f3140e9da7465111 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
gligar03.gligar.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/15858ed4efd8543b86b6a6eea5e39051 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @itkovian!

**Pull request merged**
