### PR TITLE
New EasyConfig for the GCC core -- GCC 4.9.2 compiler

### PR DESCRIPTION
**Pull request by valtandor**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
@valtandor I wouldn't have mind if you had included the easyconfigs from #2911 - #2917 in a single PR, since they're easy to review (using `eb --review-pr`), but we'll make it work the way you've tackled it here, no problem. :-)

**Comment by boegel** [comment]
@valtandor Also, out of curiosity, any particular reason you're sticking to GCC 4.9.2 rather than using the latest 4.9.3?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2614.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/eab52b482a97befbebc1f6d29ddb5283 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/36d2d767142f425fc0546da9640fa937 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Comment by valtandor** [comment]
@boegel: Regarding the use of 4.9.2 instead of 4.9.3, I'm asking my colleagues, but we're often one or two releases behind as upgrading can sometimes be a bit of a nuisance.

**Pull request merged**
