### PR TITLE
{lang}[intel/2015b] Python 2.7.10 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires #1696

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86, @gjbex, @backelj, @hajgato: please test?

**Comment by backelj** [comment]
Test report by @backelj
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/af94ace3c67660314fc0 for a full test report.

**Comment by boegel** [comment]
@backelj:

```
mv -f .deps/sqlite3.Tpo .deps/sqlite3.Plo
mv: kan status van ‘.deps/sqlite3.Tpo’ niet opvragen: Bestand of map bestaat niet
make: *** [sqlite3.lo] Fout 1
```

Hmmm, maybe `make -j 20` is too parallel for SQLite?

Can you try building only the SQLite easyconfig, and setting `parallel = 1`?

This should do it:

```
eb --from-pr 1725 SQLite-3.8.10.2-intel-2015b.eb -dfr --try-amend=parallel=1
```

**Comment by backelj** [comment]
@boegel: if I use --try-amend=parallel=1, I get the following error:

    eb-github --from-pr=1725 SQLite-3.8.10.2-intel-2015b.eb -dfr --try-amend=parallel=1
    ERROR: Irresolvable dependencies encountered: intel/2015b

If I add this line to the eb-file, then it works properly...

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/e4d8dca22f8b27e236dd for a full test report.

**Comment by backelj** [comment]
Test report by @backelj
**SUCCESS**
Build succeeded for 1 out of 1 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/c9cdd182785cb88fcf48 for a full test report.

**Comment by backelj** [comment]
@hajgato: I got the same error when building SQLite. See the solution above...

**Comment by boegel** [comment]
@backelj, @hajgato: issue fixed in SQLite easyconfig, please retry submitting a full test report?

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/466e068bc30379308548 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e106d65f120871fabc3b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/58181c1adabace55bb95 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b0b0722538daab2410ab for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/5fac543c20e675142505 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c03d0f911ab402fae0d6 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/de00bb4a287fc891e7f6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fdd7ef3c0ffc1d8e252e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/7ed465dc9f7d962d695c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8a0955a4403edada7893 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ba0b6224caa7a0cb0345 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3b7667085ee61be798f8 for a full test report.

**Comment by boegel** [comment]
I feel this is ready to go in, now that `intel/2015b` is considered to be fixed.

It has been tested on CentOS7@Haswell, RHEL6@Haswell and 2 different SL6@SandyBridge systems.

Thanks to everyone for reviewing/testing/contributing to this!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/836da337e6b223bdcb7d for a full test report.

**Comment by backelj** [comment]
Test report by @backelj
**SUCCESS**
Build succeeded for 3 out of 3 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/5a0d8948f019b7d293dd for a full test report.

**Pull request merged**
