### PR TITLE
{toolchain}[dummy] foss/2016.04

### PR DESCRIPTION
**Pull request by boegel**
requires ~~#2524~~

note: this is the first version of the `foss` toolchain that uses GCC 5.x (5.3, to be exact)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in this PR)
node2018.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/95a909981d0b83822695fcb7f5a5629f for a full test report.

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in this PR)
node2417.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0f07993491dd64c243c5f8d8c0ba9cb1 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
basically just all version bumps

I consider this a good candidate for `foss/2016b`, especially since the GCC & binutils versions are aligned with `intel/2016.03-GCC-5.3` (cfr. #3009) (but needs further testing)

thanks for the review @wpoely86, going in!

**Pull request merged**
