### PR TITLE
Theano with foss2016a

### PR DESCRIPTION
**Pull request by RvDijk**

### CODE REVIEW

**Comment by RvDijk** [comment]
Depends on #3387

**Comment by boegel** [comment]
@RvDijk how does this depend on #3387? Travis is not reporting missing easyconfigs to resolve deps...

**Comment by RvDijk** [comment]
@boegel it did, but I adjusted the easyconfig to be more consistent with #3579

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2564.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c6a3399d53a5dbbf98af6b356b066904 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2009.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/009d92f76844227bd63a8bb11062804c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @RvDijk!

**Pull request merged**
