### PR TITLE
added Java dependencies to EMBOSS easyconfigs

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**SUCCESS**
Build succeeded for 5 out of 5
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/eeffcaf18594754e7685 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c4bd6f080aa721536be8 for a full test report.

**Comment by boegel** [comment]
working great, going in, thanks @pescobar!

**Comment by fgeorgatos** [comment]
thanks for letting this stay hpcbios-compatible!

at some point in the future, when most of @pescobar's PRs get in, I'm all in favour of advancing the hell out of bioinformatics (and deps) versions, as an experimental new candidate bundle...

**Pull request merged**
