### PR TITLE
sync Bowtie2 easyconfigs, consistently use Bowtie2 easyblock

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-easyblocks/pull/1146

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 19 out of 19 (19 easyconfigs in this PR)
node2005.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/93732bd7033f164a0155c5d43f75d65c for a full test report.

**Comment by verdurin** [comment]
@boegel could we have a `foss-2016b` version too? This makes me realise I never submitted my local one...

**Comment by boegel** [comment]
@verdurin Sure, but let's do that in a separate PR...

**Comment by verdurin** [comment]
@boegel - okay, otherwise looks fine to me, and a nice improvement.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 19 out of 19 (19 easyconfigs in this PR)
node2055.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/47f11aa561eec9f75abec2d546f97b3d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2524.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/bb1ead71c848c853438377eea9e0dda7 for a full test report.

**Comment by boegel** [comment]
tested on top of latest revision of https://github.com/hpcugent/easybuild-easyblocks/pull/1146, so good to go, thanks for the feedback everyone!

**Pull request merged**
