### PR TITLE
{bio}[goolf/1.4.10] Trim_Galore 0.3.7 (REVIEW)

### PR DESCRIPTION
**Pull request by wpoely86**
Mergeable version of #1781

### CODE REVIEW

**Comment by wpoely86** [comment]
lgtm, ready to merge?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 9 out of 9 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2ed0e766871c7e4efed7 for a full test report.

**Comment by boegel** [comment]
Looks fine, but I'll need to get Jenkins to approve the PR first...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/aab67a590e33e32faf99 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins approves, good to go in, thanks @tloizou and @wpoely86!

**Pull request merged**
