### PR TITLE
{tools}[dummy/dummy] ack v2.14

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2724.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/364bbccd3c1ab459ae5b9346cff78320 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2055.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5245ebef1180e99c4ab0e4ca959f2ba2 for a full test report.

**Comment by boegel** [comment]
@verdurin please review?

**Comment by verdurin** [comment]
@boegel - looks good, though `ag` is better of course.

Runs fine here.

**Comment by boegel** [comment]
Link for `ag`?

**Comment by boegel** [comment]
Thanks for the review @verdurin!

**Pull request merged**
