### PR TITLE
{vis}[intel/2016a] OpenCV v2.4.12

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2523.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d59254d81fe5b13e1a0e7870ea125100 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2ff0f734d1e846cc502216c8160c2dc5 for a full test report.

**Comment by boegel** [comment]
basically just a version bump...

**Comment by SebastianAchilles** [comment]
The test report above from boegelbot was triggered by a test to add support for asking the bot to generate test reports for EasyBlock PRs. By mistake, the bot posted the review to this EasyConfig PR 2996 instead of the EasyBlock PR 2996.

**Pull request merged**
