### PR TITLE
{bio}[intel/2017a] NCBI-Toolkit 18.0.0

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2157.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/19e2ff0c4e310162e40d7add3fc7df39 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2641.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a66a775c284a5e3ad87224af2b24d01a for a full test report.

**Comment by vanzod** [comment]
@boegel Missing easyconfig: `Boost-1.58.0-intel-2017a.eb`

**Comment by boegel** [comment]
@vanzod Hmm, thanks for the reminder. This is @boegelbot's work though, I need to check why it didn't pick up on this.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2071.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/35924a418b5b6f5cf2e3984738a13c2f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2409.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b16c4d1c69fd4fa901e50800114d62d4 for a full test report.

**Comment by boegel** [comment]
@vanzod please rereview? ;)

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
cermis - Linux debian 8.8, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.9
See https://gist.github.com/a7b5c35282d17d3ff4547a033575f553 for a full test report.

**Comment by boegel** [comment]
@vanzod Can you check the full debug log why `table2asn` didn't get built? The partial log that's part of the test report is missing that bit...

**Comment by vanzod** [comment]
The reason is that the BerkleleyDB dependency is missing. You probably have it installed in the system and it picked it up there.

```checking for Berkeley DB libraries... no
[...]
make[4]: *** No rule to make target '/mnt/ramdisk/NCBIToolkit/18.0.0/intel-2017a/ncbi_cxx--18_0_0/ICC1701-ReleaseMTDLL64/status/BerkeleyDB.enabled', needed by 'requirements'.  Stop.
make[4]: Leaving directory '/mnt/ramdisk/NCBIToolkit/18.0.0/intel-2017a/ncbi_cxx--18_0_0/ICC1701-ReleaseMTDLL64/build/app/table2asn'
NOTE:  skipping project "table2asn" due to unmet requirements```

**Comment by boegel** [comment]
@vanzod DB dep added, please retest?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2095.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3f28141688e3972f78a530ceb9b8fb5b for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 8.8, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.9
See https://gist.github.com/73f57565b126b37012b64f190828452a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2722.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/df96665db77f5255afa5826303ece1d7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
node2095.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/74d01e3442c9d053e9b496c05be8d696 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2095.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/85ac61270387975b4a95001ca8f27f56 for a full test report.

**Comment by boegel** [comment]
@vanzod bumped to latest `DB` version, please rerereview?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2722.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4d3a7c37747626c608f253cc5ea7b40b for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 8.8, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.9
See https://gist.github.com/35c34cc783d4540d07c12bda2e3eb21c for a full test report.

**Comment by boegel** [comment]
Thanks for reviewing and testing @vanzod!

**Pull request merged**
