### PR TITLE
drop gpfs versionsuffix and use no longer existing --enable-gpfs configopt for recent HDF5 versions

### PR DESCRIPTION
**Pull request by boegel**
fix for #1577

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5afca7937b28c52e2ae4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/555198fd264f1510bc49 for a full test report.

**Comment by boegel** [comment]
@wpoely86, @JensTimmerman: please review?

**Comment by JensTimmerman** [comment]
why is this no longer needed?

**Comment by boegel** [comment]
Well, it's wrong, since `--enable-gpfs` as a configure option was dropped in HDF5 v1.8.13.

**Comment by JensTimmerman** [comment]
ok

**Comment by boegel** [comment]
Thanks for the review @JensTimmerman!

**Pull request merged**
