### PR TITLE
{system}[intel/2016a] file 5.25 + enhance sanity check (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2140.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ce4fd4099663c43cde4706620e5f0593 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2632.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/679578b739d302ea909b9153c0e7bca3 for a full test report.

**Comment by rjeschmi** [comment]
Looks good.

**Comment by boegel** [comment]
Thanks for the review @rjeschmi!

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
crick - Linux centos 6.6, AMD Opteron(tm) Processor 6380, Python 2.7.8
See https://gist.github.com/319ba48d1ee64d6af14c673e46eca740 for a full test report.

**Comment by rjeschmi** [comment]
well that was useless, but we'll pretend it worked

**Pull request merged**
