### PR TITLE
{tools}[*] parallel: add required Perl dep (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
complete version of #1425 by @JensTimmerman

this include an important bugfix w.r.t. having two subdirs for `parallel`: one named `parallel`, and another named `Parallel`

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 9 out of 11 (11 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/22723c311e66e53c45b3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a7e57ffd29845c53306b for a full test report.

**Comment by JensTimmerman** [comment]
good enought for me :-)

**Comment by boegel** [comment]
yeah, +1, I spent quite a bit of time figuring out why the Perl 5.16.3 with `ictce/4.0.6` doesn't work, turns out the Intel compiler included in there basically isn't correctly compiling `miniperl`, cfr. https://gist.github.com/boegel/ef07f85fd6f334862ae5#comment-1404816

**Comment by boegel** [comment]
going in, thanks for initiating this @JensTimmerman!

**Pull request merged**
