### PR TITLE
Version of GTK+ using the foss 2016a toolchain.

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
The config is based on the intel 2016a version.

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2601.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ac1472c3f3059e64536ac19fd383e4e2 for a full test report.

**Comment by FokkeDijkstra** [comment]
I find a remaining issue myself now. When I have built this locally the following X libraries are pulled in:

	libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x0000003b96c00000)
	libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x0000003b96400000)
	libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x0000003b97000000)
	libXcomposite.so.1 => /usr/lib64/libXcomposite.so.1 (0x0000003b9a400000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x0000003b99800000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x0000003b96000000)

So maybe these should become dependencies. For libXcomposite there is no config yet, though.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2011.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a6b1894a662936f1be95bf81ed21a784 for a full test report.

**Comment by boegel** [comment]
@FokkeDijkstra for `foss/2016b`, this can be easily solved with the new `X11` bundle, see https://github.com/hpcugent/easybuild-easyconfigs/pull/3440 (which also includes libXcomposite)

Using the same approach here is tricker though, since there already are several (separate) X11 dependencies in this dep graph...

**Comment by FokkeDijkstra** [comment]
Then I would suggest to keep it as it is now, and improve things for 2016b and later versions.

**Comment by boegel** [comment]
@FokkeDijkstra ok, fine by me, going in, thanks!

**Pull request merged**
