### PR TITLE
Cppcheck easyconfig

### PR DESCRIPTION
**Pull request by damianam**
This needs https://github.com/hpcugent/easybuild-easyblocks/pull/983

Using 2015b because it is the only toolchain with Qt5, but it should work with Qt4 as well.

### CODE REVIEW

**Comment by boegel** [comment]
@damianam looks good, but did you test this with this toolchain? a quick test shows a ton of compiler errors, for example:

```
In file included from lib/astutils.cpp(21):
lib/astutils.h(53): error: identifier "nullptr" is undefined
  const Token * astIsVariableComparison(const Token *tok, const std::string &comp, const std::string &rhs, const Token **vartok=nullptr);
```

**Comment by damianam** [comment]
Well, no. And that's why pushing easyconfigs for us is a pain, we are not deploying the same toolchains and easyconfigs, so testing them requires having a separate EB installation, or pushing all the subtree of dependencies as well. I'll take a look at the error or move it to a GCC based toolchain, where it might work better.

**Comment by boegel** [comment]
@damianam I think the main issue is the *minimal toolchains* aspect, i.e. that the easyconfigs you use only work (w.r.t. dependency resolution) when `--minimal-toolchains` is enabled, we need to find a good way to deal with that

You should be able to contribute back the easyconfig as you used them (except for site-specific customisations), contributing with different toolchains is indeed going to be a PITA.

For this particular one: how about using `foss/2016a`, for which `Qt5-5.6.0` and `PCRE-8.38` is available?

**Comment by damianam** [comment]
That is one of the aspects. The other one is that we have customized versions, so pushing something simple like this with our setup might require pushing the whole tree of dependencies. Anyway, it should work now, with the latest commit on the easyblock side

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2028.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/60cc823d956d601c9bdd591713c049bc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2647.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d31caff3f4ae8acd3ef59b39bc13a9f3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2112.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d8161ad5ad1e60b6bb4bac6bed19c986 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @damianam!

**Pull request merged**
