### PR TITLE
add PyYAML as dependency for ClusterShell

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
ClusterShell 1.7.x has an optional dependency on PyYAML, see http://clustershell.readthedocs.io/en/latest/release.html#file-based-node-groups

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2448.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/21d0c162198d5d8dd7bc58a6667a181b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2159.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/66fe8146a88cfde561cad08714e2ffad for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
gast039a.ugent.be - Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz, Python 2.7.10
See https://gist.github.com/87aac7fa60aa6e468acf125b90bb4731 for a full test report.

**Comment by boegel** [comment]
@thiell This makes sense, right?

**Comment by thiell** [comment]
@boegel yep PyYAML is highly recommended with CS 1.7+ so you can use .yaml files to easily describe your cluster node groups.

**Comment by boegel** [comment]
Thanks for the review @thiell!

**Pull request merged**
