### PR TITLE
{bio} [dummy] IGVTools-2.3.72

### PR DESCRIPTION
**Pull request by verdurin**
Update IGVTools to 2.3.72.

### CODE REVIEW

**Comment by verdurin** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/dacc8040517efd24951650be3996848b for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
