### PR TITLE
add patch for Boost 1.60.0 to fix bug resulting in TypeError

### PR DESCRIPTION
**Pull request by boegel**
cfr. https://github.com/boostorg/python/issues/56, patch grabbed from https://github.com/boostorg/python/pull/59

This fixes a problem that occurs with Yade:

```
Traceback (most recent call last):
  File "HPC_Yade_Oedometer_Funk.py", line 319, in <module>
    OedometerMasterFunk(packing = 'Random',frictionAngle_Soil=frictionAngle_Soil,limit = limit)                         # SINGLE NODE
  File "HPC_Yade_Oedometer_Funk.py", line 81, in OedometerMasterFunk
    TopSpheres=pack.regularOrtho(pack.inAlignedBox(B_Corner,T_Corner),radius=TopRadius,gap=TopRadius*0.0,color=(1,1,0),material=FricMat6)
  File "/apps/gent/SL6/sandybridge/software/Yade/1.20.0-intel-2016a-Python-2.7.11/lib64/yade-1.20.0/py/yade/pack.py", line 264, in regularOrtho
    if predicate(xyz,radius): ret+=[utils.sphere(xyz,radius=radius,**kw)]
  File "/apps/gent/SL6/sandybridge/software/Yade/1.20.0-intel-2016a-Python-2.7.11/lib64/yade-1.20.0/py/yade/utils.py", line 206, in sphere
    _commonBodySetup(b,V,Vector3(geomInert,geomInert,geomInert),material,pos=center,dynamic=dynamic,fixed=fixed)
  File "/apps/gent/SL6/sandybridge/software/Yade/1.20.0-intel-2016a-Python-2.7.11/lib64/yade-1.20.0/py/yade/utils.py", line 123, in _commonBodySetup
    if resetState: b.state=b.mat.newAssocState()
TypeError: No to_python (by-value) converter found for C++ type: N5boost10shared_ptrI5StateEE
```

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 please review?

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2014.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ae07fa0ee2daea9fb3ce978037bf23f3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 21 out of 21 (6 easyconfigs in this PR)
node2437.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8da1b0e2a3b57907aa30dd7d14edcc0f for a full test report.

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Comment by boegel** [comment]
@jrbosch FYI: one of our users reported a problem with Yade, see the error mentioned in the description

The problem was fixed by rebuilding Boost with this patch included, and then also rebuilding Yade on top of the rebuilt Boost.

**Comment by jrbosch** [comment]
Thanks @boegel I'm sorry  I didn't notice before.

**Comment by boegel** [comment]
@jrbosch Don't worry about that, it probably only pops up with a particular way of using Yade.

**Pull request merged**
