### PR TITLE
update source URLs in libpciaccess easyconfigs

### PR DESCRIPTION
**Pull request by iotaka**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by iotaka** [comment]
Changed source_url and removed extra option not needed for the packages from https://www.x.org/releases/individual/lib/

**Comment by boegel** [comment]
@iotaka Do you mind making this change consistent in all 12 `libpciaccess` easyconfig files?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in this PR)
node2130.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6d54d60ab620d02f5003c30638e71261 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @iotaka!

**Pull request merged**
