### PR TITLE
{lib}[intel/2016b] MXNet 0.9.3 core library with Python-2.7.12 (WIP)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by hajgato** [comment]
compilation ends without problems, however when I try to import the `Python` module I get the following error:
```
>>> import mxnet as mx 
[14:25:33] /tmp/hajgato/build/MXNet/0.9.3/intel-2016b/mxnet/dmlc-core/include/dmlc/logging.h:300: [14:25:33] include/mxnet/operator.h:514: Check failed: this->name == type (BatchNorm vs. Activation) Register Name and TypeString mismatch, name="BatchNorm", but TypeString="Activation"
```

I am afraid to solve this problem is beyond my capabilities...

**Comment by boegel** [comment]
@hajgato That's a pretty weird problem... This doesn't occur with `foss/2016b`? (#4127)?

**Comment by hajgato** [comment]
@boegel with `GCC` is fine. It might be `c++std` difference. 
I have found something on `MXNet` github page, but this error is rather long and it is not corrected.
see:
https://github.com/dmlc/mxnet/issues/413
and around there

**Comment by hajgato** [comment]
tried with `--std=c++14` and `--stc=gnu++11`, same result

**Comment by hajgato** [comment]
better version:
https://github.com/hpcugent/easybuild-easyconfigs/pull/4346

**Pull request closed without merging**
