### PR TITLE
rename patch files for OpenFOAM according to (our) 'standards'

### PR DESCRIPTION
**Pull request by boegel**
workaround for https://github.com/hpcugent/easybuild-framework/issues/1516, so #2023 and #2048 can be properly tested via `--from-pr`

### CODE REVIEW

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Comment by ocaisa** [comment]
Why were the patches not copied rather than renamed? This breaks working eb files for us...and took a while to solve

**Comment by boegel** [comment]
@ocaisa: at some point, we need to clean up mistakes we made in the past and work towards something 'uniform'...

Thanks for bringing this up though. How did the problem manifest itself, and why did it take you a while to solve?

This also goes back to your feature request to make sure everything that is needed to reproduce a build is archived somewhere (potentially including the used easyblock(s)...).

**Comment by ocaisa** [comment]
It wasn't a guru like me who was solving it which was maybe why it took a while :)

They tried to reinstall an existing eb file with EB 2.5 but the patch file could no longer be found.

**Comment by boegel** [comment]
Where did you get the easyconfig file from? The easyconfig archive maintained by EasyBuild itself? Or an existing install directory?

**Comment by ocaisa** [comment]
Custom easyconfig with custom toolchain and configuration (used for a previous installation)

**Comment by boegel** [comment]
In that case, either never removing the patch files or copying them next to the sources could have saved you...

**Comment by ocaisa** [comment]
Yup, exactly

**Pull request merged**
