### PR TITLE
don't hardcode CC/CXX in OpenMPI easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by pescobar** [comment]
if you don't do this mpifort wrapper would use gfortran instead of ifort. Try to compile without those flags and then run "mpifort" and you will get gfortran output

A user in my cluster reported the issue

**Comment by boegel** [comment]
OK, that's very weird... I checked the configure output and the generated `Makefile`, and they both  mention (only) `icc`:
```
$ grep gcc openmpi_configure.log 
checking for gcc... icc
checking dependency style of icc... gcc3
checking for gcc... (cached) icc
checking dependency style of icpc... gcc3
checking dependency style of icpc... (cached) gcc3
checking dependency style of icc -std=gnu99... gcc3
checking dependency style of icc -std=gnu99... (cached) gcc3
checking for gcc... icc
checking dependency style of icc... gcc3
checking dependency style of icc -std=gnu99... gcc3
checking for gcc... icc
checking dependency style of icc... gcc3
checking dependency style of icpc... gcc3
checking dependency style of icc... gcc3
checking dependency style of icpc... gcc3
checking for gcc... icc
checking dependency style of icc... gcc3
```

```
$ grep icc Makefile
	$(top_srcdir)/config/ompi_check_icc.m4 \
CC = icc -std=gnu99
CCAS = icc -std=gnu99
CPP = icc -E
OMPI_CXX_ABSOLUTE = /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/icc/2015.3.187-GNU-4.9.3-2.25/bin/icpc
OPAL_CC_ABSOLUTE = /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/icc/2015.3.187-GNU-4.9.3-2.25/bin/icc
OPAL_CXX_ABSOLUTE = /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/icc/2015.3.187-GNU-4.9.3-2.25/bin/icpc
WRAPPER_CC = icc
ac_ct_CC = icc
```

`gfortran` is nowhere to be found:

```
-bash-4.1$ grep gfortran Makefile
-bash-4.1$ grep gfortran openmpi_configure.log 
-bash-4.1$ 
```


@pescobar: maybe this was because the EasyBuild framework wasn't defining `$FC` yet (which was fixed in EasyBuild v2.4.0, see https://github.com/hpcugent/easybuild-framework/pull/1394

**Comment by pescobar** [comment]
probably now it works because $FC is defined and not back then in Feb 2015

anyway it would be nice to do a sanity check to be sure mpifort is using ifort in this toolchain

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f3091c5783bc766f762d for a full test report.

**Comment by boegel** [comment]
@pescobar: sanity check commands added

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 18 out of 22 (9 easyconfigs in this PR)
Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/99609b41d83533acba98 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 9 (9 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d19ddcf1183161eb1ed9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 9 (9 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4eea808d67c24492cc6f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 8 out of 9 (9 easyconfigs in this PR)
Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/20e272746f6de3ca9876 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/dcb5612ceaf4cee35ccc for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @pescobar!

**Pull request merged**
