### PR TITLE
Corrected source filename

### PR DESCRIPTION
**Pull request by nathanhaigh**

### CODE REVIEW

**Comment by boegel** [comment]
How did this pass the test report before?!

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by nathanhaigh** [comment]
Commit 467c04d was made after the test(s) were run. This is where an error was introduced.

**Comment by boegel** [comment]
Ah, ok. I should have payed closer attention... Thanks @nathanhaigh!

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/99209db28bcc0e4cb09f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @nathanhaigh!

**Pull request merged**
