### PR TITLE
New EasyConfig for KEALib 1.4.4 with the foss-2015a toolchain

### PR DESCRIPTION
**Pull request by valtandor**
Required as part of the GRASS 7.0.2 dependency tree. Depends on HDF5, an EasyConfig for which is included in order to reduce false errors during testing.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@valtandor: needs sync with `develop` now that #2415 is merged

**Comment by valtandor** [comment]
Synced with develop.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/72c26aa3943fee9ff489 for a full test report.

**Comment by boegel** [comment]
@valtandor: missing `CMake` build dep:

```
/bin/bash: cmake: command not found
```

**Comment by valtandor** [comment]
I've put an explicit build dependency in the easyconfig, for what that's worth. Curiously, it didn't seem to be necessary any more.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/68f606a2aadfe9ff256e for a full test report.

**Comment by boegel** [comment]
lgtm

@valtandor: the `CMake` build dep *is* required, but that's not something Jenkins/@hpcugentbot can check on (they don't perform the actual build)

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
