### PR TITLE
new CrayGNU files for 2015.11-XC

### PR DESCRIPTION
**Pull request by gppezzi**

### CODE REVIEW

**Comment by gppezzi** [comment]
Test report by @gppezzi
**SUCCESS**
Build succeeded for 42 out of 42 (42 easyconfigs in this PR)
Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.7.7
See https://gist.github.com/f9d5ae7934022f53357c for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**FAILED**
Build succeeded for 34 out of 42 (42 easyconfigs in this PR)
Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/42589ab300ea2d5d66c9 for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**FAILED**
Build succeeded for 38 out of 42 (42 easyconfigs in this PR)
Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/6d369c1c2ca2bfa56222 for a full test report.

**Comment by gppezzi** [comment]
Test report by @gppezzi
**SUCCESS**
Build succeeded for 59 out of 59 (42 easyconfigs in this PR)
Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.7.7
See https://gist.github.com/68a75096e633d27519c6 for a full test report.

**Comment by gppezzi** [comment]
Test report by @gppezzi
**SUCCESS**
Build succeeded for 60 out of 60 (42 easyconfigs in this PR)
Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.6
See https://gist.github.com/af4743c88a0dff308eed for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**FAILED**
Build succeeded for 12 out of 42 (42 easyconfigs in this PR)
Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/89266334db84aa6617be for a full test report.

**Pull request closed without merging**
