### PR TITLE
{bio} [{intel,foss}-2015a] HTSlib 1.2.1 (REVIEW) 

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato: please use `(WIP)` in the subject until this is finished

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by hajgato** [comment]
@boegel forget to push it. Anyway, it is better to leave WIP as I have to change to fit to the BCF-SAMtools PR.

**Comment by boegel** [comment]
@hajgato: ok, please issue a comment when you feel this is ready (we don't get notified of a change PR title)

**Comment by hajgato** [comment]
Changed to review status

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/354b3d975555a77adbba for a full test report.

**Comment by boegel** [comment]
looking great, going in, thanks @hajgato!

**Pull request merged**
