### PR TITLE
consistently use https for PyPI URLs in homepage/source_urls

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-framework/pull/1286 to avoid breaking currently working downloads (where https was already being used)

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 78 out of 78 (78 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/06f59d9880509d7de72c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 127 out of 127 (127 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1c9d1826f2f427d24a3d for a full test report.

**Comment by boegel** [comment]
retested downloading for all affected easyconfigs (on top of https://github.com/hpcugent/easybuild-framework/pull/1286), all is well

Thanks for the review @wpoely86!

**Pull request merged**
