### PR TITLE
{lang} [foss/2016b] MXNet/0.9.3 (REVIEW)

### PR DESCRIPTION
**Pull request by wpoely86**
Split of MXNet/0.9.3 with foss/2016b from #4346

The foss one works, the intel one currently doesn't.

Needs hpcugent/easybuild-easyblocks#1135

### CODE REVIEW

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic81 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/40287d93ee6481acf8180434040d73ec for a full test report.

**Comment by boegel** [comment]
@wpoely86 Please fix these minor style issues:

```
$ eb --from-pr 4765 --check-style
== temporary log file in case of crash /tmp/eb-sdR_GV/easybuild-71oh1c.log

*** WARNING: Using easyconfigs from unstable (pending/failed tests or merge conflict) PR #4765 ***

Running style check on 1 easyconfig(s)...
/tmp/eb-sdR_GV/files_pr4765/m/MXNet/MXNet-0.9.3-foss-2016b-Python-2.7.12.eb:16:27: E261 at least two spaces before inline comment
/tmp/eb-sdR_GV/files_pr4765/m/MXNet/MXNet-0.9.3-foss-2016b-Python-2.7.12.eb:20:71: E261 at least two spaces before inline comment
[FAIL] /tmp/eb-sdR_GV/files_pr4765/m/MXNet/MXNet-0.9.3-foss-2016b-Python-2.7.12.eb
ERROR: One or more style checks FAILED!
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2050.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5b5f3fb17a1326b8ac2e2c93b2fc29cd for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2441.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/226f25ea5e20055204efae2851cc4218 for a full test report.

**Comment by boegel** [comment]
@wpoely86 Please fix filename (or `versionsuffix`):

```
AssertionError: Filename '/home/travis/build/hpcugent/easybuild-easyconfigs/easybuild/easyconfigs/m/MXNet/MXNet-0.9.3-foss-2016b-Python-2.7.12.eb' of parsed easyconfig matches expected filename 'MXNet-0.9.3-foss-2016b-Python-2.7.12-R-3.3.3.eb'
```

**Comment by boegel** [comment]
Going in, thanks @wpoely86!

**Pull request merged**
