### PR TITLE
ENH: add easyconfig for WPS3.8

### PR DESCRIPTION
**Pull request by andreas-h**
easyconfig for WPS3.8, using intel-2016a.

This also includes fixes for all _known problems_ as published on http://www2.mmm.ucar.edu/wrf/users/wpsv3.8/known-prob-3.8.html as of 27 Jul 2016

depends on https://github.com/hpcugent/easybuild-easyblocks/pull/974

### CODE REVIEW

**Comment by andreas-h** [comment]
can someone please tell me what the travis errors mean?  the message

    ======================================================================
    FAIL: test__parse_easyconfig_WPS-3.8-intel-2016a-dmpar.eb  (test.easyconfigs.easyconfigs.EasyConfigTest)
    
    Test for parsing of easyconfig WPS-3.8-intel-2016a-dmpar.eb
    
    ----------------------------------------------------------------------
    
    Traceback (most recent call last):
    
    File "<string>", line 1, in innertest
    
    File "/home/travis/build/hpcugent/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 246, in template_easyconfig_test
    
        self.assertTrue(os.path.isfile(patch_full), msg)
    
    AssertionError: Patch file /home/travis/build/hpcugent/easybuild-easyconfigs/easybuild/easyconfigs/w/WPS/WPS-3.8_netCDF-Fortran_seperate_path.patch is available for WPS-3.8-intel-2016a-dmpar.eb
    
    
doesn't tell me anything ... Thanks!

**Comment by boegel** [comment]
@andreas-h the easyconfig file requires a patch named `WPS-3.8_netCDF-Fortran_seperate_path.patch`, but it is not included in this PR (and not available yet)

**Comment by boegel** [comment]
@andreas-h note that other (older) existing easyconfigs need the patch named `WPS_netCDF-Fortran_seperate_path.patch`

you should either try to reuse the patch named `WPS-3.5.1_netCDF-Fortran_seperate_path.patch` if it still applies to WPS v3.8, or create an equivalent patch based on the sources for WPS 3.8

**Comment by boegel** [comment]
@andreas-h patch issue is fixed in https://github.com/andreas-h/easybuild-easyconfigs/pull/1, but it seems there are missing dependencies to take care of too?

**Comment by boegel** [comment]
@andreas-h ping on reviewing/merging https://github.com/andreas-h/easybuild-easyconfigs/pull/1 to update this PR?

**Comment by andreas-h** [comment]
okay, again I screwed up :-( the new try is at #3970. I sincerely need to work on my git-fu ...

**Pull request closed without merging**
