### PR TITLE
{bio}[intel/2015a] BEDTools 2.23.0

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/44ed1c63a314b45fd123 for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/06f65cba32a268bfa643 for a full test report.

**Comment by pescobar** [comment]
the easyconfig looks fine for me. The only tiny remark, I would add folder "tutorial" to files_to_copy

```
files_to_copy = ["bin", "docs", "data", "genomes", "scripts", "test", "tutorial"]
```

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/394605cb2a8327b79f55 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4596f7f7919a1b314cea for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ebd5bd9c744a880cbf22 for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @pescobar!

**Pull request merged**
