### PR TITLE
Add SVG and Statistics::Basic to recent Perl versions

### PR DESCRIPTION
**Pull request by SethosII**
This adds two extensions to Perl for consistency. See #4790.

### CODE REVIEW

**Comment by boegel** [comment]
@SethosII You skipped `Perl-5.24.0-foss-2016b.eb` by accident?

**Comment by SethosII** [comment]
@boegel `Perl-5.24.0-foss-2016b.eb` is already included in #4790 or should I remove it from #4790 and add it to this one?

**Comment by boegel** [comment]
@SethosII Ah, no, fine to leave as is, thanks for clarifying!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in this PR)
node2157.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/da9b1414686388b3a0ea1ab2d820b363 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Pull request merged**
