### PR TITLE
{tools}[dummy] GC3Pie 2.4.0 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz, Python 2.7.6
See https://gist.github.com/e890a43f7422e46b3a60 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/012ee478da536b316cfc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/86c03f0204e4a2c3481d for a full test report.

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks @wpoely86!

**Pull request merged**
