### PR TITLE
stop relying on $MKLROOT in ROOT easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/576

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f5817ceda1884118140a for a full test report.

**Comment by fgeorgatos** [comment]
not against it, but what is the justication? (because the practice has a big side-effect)

**Comment by boegel** [comment]
This change is required because of https://github.com/hpcugent/easybuild-easyblocks/pull/576, where we fix the definition of `$MKLROOT` (it should include the `mkl` subdir, as specified by the Intel documentation)

**Comment by boegel** [comment]
Thanks for the review @fgeorgatos!

**Pull request merged**
