### PR TITLE
{phys}[intel/2015a] FDS r17534 + rr22681

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@JensTimmerman: please review (test report coming up)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0d4ef7c70a08b5307b9f for a full test report.

**Comment by JensTimmerman** [comment]
looks ok, however, a lot of deviation from a normal build procedure, might warrant a dedicated EasyBlock?

**Comment by boegel** [comment]
@JensTimmerman: I don't think this deviates too much? Compared to some other easyconfigs that use a generic easyblock, this is actually pretty 'clean'...

Thanks for the review!

**Pull request merged**
