### PR TITLE
New EasyConfig for flex 2.6.0 with the foss-2015a toolchain

### PR DESCRIPTION
**Pull request by valtandor**
Required as part of the GRASS 7.0.2 dependency tree. Depends on Bison, an EasyConfig for which has been included in order to reduce the risk of false errors during testing.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@valtandor: needs sync with `develop` now that #2410 is merged

**Comment by valtandor** [comment]
Synced with develop.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a43e6e58e4207933dbfc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
