### PR TITLE
{bio}[intel/2015b] Trinity 2.1.1 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
Needs https://github.com/hpcugent/easybuild-easyblocks/pull/802

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato: I ran into this problem, I wonder why you didn't...

I'll try and figure out what the problem is, but I wanted to check with you: does it work for you?

```
configure:3682: gcc -o conftest   -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/icc/2015.3.187-GNU-4.9.3-2.25/lib/intel64 -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/imkl/11.2.3.187-iimpi-7.3.5-GNU-4.9.3-2.25/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/imkl/11.2.3.187-iimpi-7.3.5-GNU-4.9.3-2.25/mkl/lib/intel64 -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/imkl/11.2.3.187-iimpi-7.3.5-GNU-4.9.3-2.25/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Java/1.8.0_66/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/ant/1.9.6-Java-1.8.0_66/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/ncurses/5.9-GNU-4.9.3-2.25/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/zlib/1.2.8-GNU-4.9.3-2.25/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Perl/5.20.3-intel-2015b/lib conftest.c -liomp5 -lpthread >&5
configure:3686: $? = 0
configure:3693: ./conftest
./configure: line 3695: ./conftest: cannot execute binary file
configure:3697: $? = 126
configure:3704: error: in `/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Trinity/2.1.1-intel-2015b/trinityrnaseq-2.1.1/trinity-plugins/tmp.jellyfish':
configure:3706: error: cannot run C compiled programs.
```

**Comment by boegel** [comment]
Ah, it's using `gcc` and linking with `-liomp5`, that's probably not a very good idea...

**Comment by boegel** [comment]
@hajgato: fix for the issue I ran into is in https://github.com/hajgato/easybuild-easyconfigs/pull/31, which also making the workaround of undefining `$CFLAGS` & co not required

**Comment by hajgato** [comment]
@boegel: merged

**Comment by hajgato** [comment]
@boegel: and yes, for me it worked, I dunno why....

**Comment by hajgato** [comment]
@boegel: as I wrote at the Trinity Easyblock (https://github.com/hpcugent/easybuild-easyblocks/pull/802) I have a small problem with the mixed `Intel`/`GCC` compiler approach, and as a consequence with the dependencies as well. Trinity is a `Perl` script, so Perl should be a dependency for sure, but we have a bunch of functionality which only works if `Bowtie` and/or `Bowtie2` and/or `STAR` and/or `RSEM` and/or `Python` present. `Bowtie` , `Bowtie2`, and `STAR` are not an issue, as they have no deps, `RSEM` has `zlib` and `ncurses` deps, and currently I use `GNU-4.9.3-2.25` version (and also for `Trinity` ro able to work together). However, If I want to use `Python` as well, we need  `zlib` and `ncurses`  with either `foss` or `intel`, as we have Python with only those toolchains (and it make no sense to make it with `GNU`).  Is there a way to solve this conflict? (Maybe I have to do `RSEM` with `Intel` and make `Trinity` to use the `Intel` version of `zlib` and `ncurses`, although I am not sure whether `RSEM` would work correctly with `Intel`

**Comment by boegel** [comment]
@hajgato: I would indeed look into compiling `RSEM` with `intel`. In my experience, this tends to work well with recent Intel compilers, I rarely run into problems anymore there, even if the software is not "aware" of Intel compilers...

**Comment by boegel** [comment]
Also relevant to mention: once the support for `--minimal-toolchains` is considered stable (and it may also become the default), this will not be an issue anymore. See http://easybuild.readthedocs.org/en/latest/Manipulating_dependencies.html#minimal-toolchains for more information.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9e2d10c8736118273f5f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f08f20e7bc960da0076e for a full test report.

**Comment by boegel** [comment]
For some reason, when installing Trinity with the install path on GPFS, you can run into this for Chrysalis:

```
 ./checkLock: ./checkLock: cannot execute binary file
```

This error is ignored by the build process though, but the sanity check fails to find `Chrysalis/Chrysalis`...

Testing with an install path on local disk is just fine though, see test reports above.

I suspect this is due to some kind of weird bug in GPFS.

**Comment by boegel** [comment]
Tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/802, good to go, thanks @hajgato!

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
