### PR TITLE
{numlib} [goolf/1.4.10] NLopt-2.4.2-goolf-1.4.10.eb (REVIEW)

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
Nlopt should be a dependency for R-3.3.1. Ken @boegel  can we merge this PR and fix R-3.3.1

I am running into issue with my builds if I don't have this package.

I am using R-3.3.1 with intel-2017.01
```
== installing extension ipred 0.9-5 (280/414)...
== installing extension statmod 1.4.24 (281/414)...
== installing extension miscTools 0.6-16 (282/414)...
== installing extension maxLik 1.3-4 (283/414)...
== installing extension mlogit 0.2-4 (284/414)...
== installing extension getopt 1.20.0 (285/414)...
== installing extension gsalib 2.1 (286/414)...
== installing extension optparse 1.3.2 (287/414)...
== installing extension klaR 0.6-12 (288/414)...
== installing extension neuRosim 0.2-12 (289/414)...
== installing extension locfit 1.5-9.1 (290/414)...
== installing extension GGally 1.2.0 (291/414)...
== installing extension beanplot 1.2 (292/414)...
== installing extension clValid 0.6-6 (293/414)...
== installing extension matrixStats 0.50.2 (294/414)...
== installing extension DiscriMiner 0.1-29 (295/414)...
== installing extension ellipse 0.3-8 (296/414)...
== installing extension leaps 2.9 (297/414)...
== installing extension nloptr 1.0.4 (298/414)...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/easybuild/build/R/3.3.1/intel-2017.01): build failed (first 300 chars): cmd "R CMD INSTALL /dev/shm/easybuild/sources/r/R/extensions/nloptr_1.0.4.tar.gz   --library=/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/R/3.3.1/lib64/R/library --no-clean-on-error" exited with exitcode 1 and output:
* installing *source* package 
== Results of the build can be found in the log file(s) /dev/shm/tmp/eb-3Nh9ZM/easybuild-R-3.3.1-20170403.125633.SBeTT.log, /dev/shm/tmp/eb-3Nh9ZM/easybuild-R-3.3.1-20170403.125633.SBeTT.log.1, /dev/shm/tmp/eb-3Nh9ZM/easybuild-R-3.3.1-20170403.125633.SBeTT.log.2
ERROR: Build of /hpc/hpcswadm/easybuild/R/R-3.3.1-intel-2017.01.eb failed (err: 'build failed (first 300 chars): cmd "R CMD INSTALL /dev/shm/easybuild/sources/r/R/extensions/nloptr_1.0.4.tar.gz   --library=/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/R/3.3.1/lib64/R/library --no-clean-on-error" exited with exitcode 1 and output:\n* installing *source* package \xe2')

```

```
[hpcswadm@amrndhl1157 easybuild]$ tail /dev/shm/tmp/eb-3Nh9ZM/easybuild-R-3.3.1-20170403.125633.SBeTT.log
  #include "nlopt.h"
                    ^

compilation aborted for nloptr.c (code 4)
make: *** [nloptr.o] Error 4
ERROR: compilation failed for package ‘nloptr’
 (at easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/run.py:449 in parse_cmd_output)
== 2017-04-03 14:50:32,425 easyblock.py:2518 WARNING build failed (first 300 chars): cmd "R CMD INSTALL /dev/shm/easybuild/sources/r/R/extensions/nloptr_1.0.4.tar.gz   --library=/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/R/3.3.1/lib64/R/library --no-clean-on-error" exited with exitcode 1 and output:
* installing *source* package 
== 2017-04-03 14:50:32,425 easyblock.py:276 INFO Closing log for application name R version 3.3.1
[hpcswadm@amrndhl1157 easybuild]$ tail -n 10 /dev/shm/tmp/eb-3Nh9ZM/easybuild-R-3.3.1-20170403.125633.SBeTT.log
  #include "nlopt.h"
                    ^

compilation aborted for nloptr.c (code 4)
make: *** [nloptr.o] Error 4
ERROR: compilation failed for package ‘nloptr’
 (at easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/run.py:449 in parse_cmd_output)
== 2017-04-03 14:50:32,425 easyblock.py:2518 WARNING build failed (first 300 chars): cmd "R CMD INSTALL /dev/shm/easybuild/sources/r/R/extensions/nloptr_1.0.4.tar.gz   --library=/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/R/3.3.1/lib64/R/library --no-clean-on-error" exited with exitcode 1 and output:
* installing *source* package 
== 2017-04-03 14:50:32,425 easyblock.py:276 INFO Closing log for application name R version 3.3.1
[hpcswadm@amrndhl1157 easybuild]$ tail -n 20 /dev/shm/tmp/eb-3Nh9ZM/easybuild-R-3.3.1-20170403.125633.SBeTT.log
In untar(tarfile = "nlopt-2.4.2.tar.gz") :
  '/bin/gtar -zxf 'nlopt-2.4.2.tar.gz'' returned error code 2
configure: Starting to install library to /dev/shm/tmp/eb-3Nh9ZM/RtmppwVd5x/R.INSTALL41510bcdcf92/nloptr/nlopt-2.4.2
configure: Done installing library to /dev/shm/tmp/eb-3Nh9ZM/RtmppwVd5x/R.INSTALL41510bcdcf92/nloptr/nlopt-2.4.2
configure: creating ./config.status
config.status: creating src/Makevars
** libs
icpc -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/R/3.3.1/lib64/R/include -DNDEBUG  -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/imkl/2017.1.132/mkl/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/libreadline/6.3/include -I/nfs/grid/software/RHEL7/easybuild/software/Compiler/GCCcore/5.4.0/ncurses/6.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/bzip2/1.0.6/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/XZ/5.2.2/include -I/nfs/grid/software/RHEL7/easybuild/software/Compiler/GCCcore/5.4.0/zlib/1.2.8/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/SQLite/3.13.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/PCRE/8.38/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/libpng/1.6.23/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/libjpeg-turbo/1.5.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/LibTIFF/4.0.6/include -I/nfs/grid/software/RHEL7/easybuild/software/Core/Java/1.8.0_92/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/Tcl/8.6.5/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/Tk/8.6.5/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/cURL/7.49.1/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/libxml2/2.9.4/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/GDAL/2.1.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/PROJ/4.8.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/GMP/6.1.1/include    -fpic  -O2 -xHost -ftz -fp-speculation=safe -fp-model source  -c dummy.cpp -o dummy.o
icc -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/R/3.3.1/lib64/R/include -DNDEBUG  -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/imkl/2017.1.132/mkl/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/libreadline/6.3/include -I/nfs/grid/software/RHEL7/easybuild/software/Compiler/GCCcore/5.4.0/ncurses/6.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/bzip2/1.0.6/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/XZ/5.2.2/include -I/nfs/grid/software/RHEL7/easybuild/software/Compiler/GCCcore/5.4.0/zlib/1.2.8/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/SQLite/3.13.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/PCRE/8.38/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/libpng/1.6.23/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/libjpeg-turbo/1.5.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/LibTIFF/4.0.6/include -I/nfs/grid/software/RHEL7/easybuild/software/Core/Java/1.8.0_92/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/Tcl/8.6.5/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/Tk/8.6.5/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/cURL/7.49.1/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/libxml2/2.9.4/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/GDAL/2.1.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/PROJ/4.8.0/include -I/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/GMP/6.1.1/include   -I/dev/shm/tmp/eb-3Nh9ZM/RtmppwVd5x/R.INSTALL41510bcdcf92/nloptr/nlopt-2.4.2/include -fpic  -O2 -xHost -ftz -fp-speculation=safe -fp-model source  -c nloptr.c -o nloptr.o
nloptr.c(42): catastrophic error: cannot open source file "nlopt.h"
  #include "nlopt.h"
                    ^

compilation aborted for nloptr.c (code 4)
make: *** [nloptr.o] Error 4
ERROR: compilation failed for package ‘nloptr’
 (at easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/run.py:449 in parse_cmd_output)
== 2017-04-03 14:50:32,425 easyblock.py:2518 WARNING build failed (first 300 chars): cmd "R CMD INSTALL /dev/shm/easybuild/sources/r/R/extensions/nloptr_1.0.4.tar.gz   --library=/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/R/3.3.1/lib64/R/library --no-clean-on-error" exited with exitcode 1 and output:
* installing *source* package 
== 2017-04-03 14:50:32,425 easyblock.py:276 INFO Closing log for application name R version 3.3.1

```

**Comment by boegel** [comment]
(open/close to trigger Travis)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2117.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d31f84c91bda0cfb5655baabf8cd4e22 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pescobar!

**Comment by boegel** [comment]
@shahzebsiddiqui fixed in #4481 (for the R 3.3.3 easyconfig)

**Pull request merged**
