### PR TITLE
{devel}[intel/2015a] Boost 1.59.0 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
on hold until #1858 is merged in

### CODE REVIEW

**Comment by wpoely86** [comment]
looks good

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/66709a0cf229c1cb7c18 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 3 out of 5 (1 easyconfigs in this PR)
Linux debian 8.1, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.9
See https://gist.github.com/401b1e662856fe3c1e74 for a full test report.

**Comment by boegel** [comment]
@wpoely86: missing GMP on your end for `pycrypto` extension included in the Python 2.7.10 easyconfig... I didn't know about this one. :-/

**Comment by boegel** [comment]
@wpoely86: please retest now that #1858 is merged?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 3 out of 5 (1 easyconfigs in this PR)
Linux debian 8.1, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.9
See https://gist.github.com/da3e4d3732849eab143e for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in this PR)
Linux debian 8.1, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.9
See https://gist.github.com/72b8fdd096355cc248e0 for a full test report.

**Comment by boegel** [comment]
Hooray!

Thanks @wpoely86!

**Pull request merged**
