### PR TITLE
rename GenomeAnalysisTk easyconfigs to GATK

### PR DESCRIPTION
**Pull request by boegel**
@fgeorgatos: please review

### CODE REVIEW

**Comment by fgeorgatos** [comment]
the filename of the 2nd file has not been collapsed maybe?

**Comment by fgeorgatos** [comment]
ok!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c5f01cfd78414880c650 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f30cc18526a0e8739d3e for a full test report.

**Comment by boegel** [comment]
finally :)

going in, thanks @fgeorgatos!

**Pull request merged**
