### PR TITLE
Updates for various EasyConfigs (WIP)

### PR DESCRIPTION
**Pull request by backelj**
- changed source_urls and homepage for Qt

### CODE REVIEW

**Comment by backelj** [comment]
Jenkins: ok to test

**Comment by backelj** [comment]
@boegel: I guess I cannot trigger Jenkins to start testing, could you start it? If it's okay like this, we'll be adding more modules tomorrow.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@backelj: try and keep PRs small in terms of touching multiple easyconfig files, otherwise they're too hard to test/review/get merged

In it's current state, this one is focused on Qt easyconfigs, let's keep it that way, and open a separate PR for changes to other easyconfigs.

See also 2nd-to-last paragraph in https://github.com/hpcugent/easybuild/wiki/Policy-for-easyconfig-pull-requests#open-a-pr-as-soon-as-you-start-working-on-something

**Comment by boegel** [comment]
@backelj: please update the title too for this one, to better reflect which changes are being made, and that it only touches Qt

**Comment by boegel** [comment]
@backelj: did you mean to close this?

**Comment by backelj** [comment]
@boegel: Found it again (thanks, Jenkins). I have renamed this branch to "modules/qt" to keep the QR small. So this one can be closed.

**Pull request closed without merging**
