### PR TITLE
{devel}[*] CMake: Set CMAKE_PREFIX_PATH to ncurses install directory

### PR DESCRIPTION
**Pull request by geimer**
Also, include ccmake in sanity check.

This fixes https://github.com/hpcugent/easybuild-easyconfigs/issues/4171 for 28 configurations (2016 toolchains).  Fixing the remaining 64 configurations is left as an exercise for someone who wants to (re-)install CMake with older toolchains.

### CODE REVIEW

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 15 out of 15 (15 easyconfigs in this PR)
swatc03 - Linux debian 8.7, Six-Core AMD Opteron(tm) Processor 2427, Python 2.7.9
See https://gist.github.com/f7cb72fe2808deffde80f7901ffadf41 for a full test report.

**Comment by boegel** [comment]
lgtm, although I'd really prefer to make this change a bit more consistent, at least for say CMake 3.4.x and up or something like that...

**Comment by geimer** [comment]
@boegel Here you go - 11 more easyconfigs.  Now CMake 3.4.0 and up should be covered.

**Comment by boegel** [comment]
Thanks @geimer!

I'll look into a test report for this bunch...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 37 out of 37 (37 easyconfigs in this PR)
node2104.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8bff2ae6e00ab68f16db8a7d824412a4 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @geimer!

**Pull request merged**
