### PR TITLE
{bio}[intel/2015a] AFNI 20141023 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
depends on ~~#1528~~, ~~#1562~~

### CODE REVIEW

**Comment by fgeorgatos** [comment]
looks good overall, no comments, just suggesting a retest

**Comment by fgeorgatos** [comment]
@boegel : retest

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3f27a51a16bafd134a6d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7c6ad1be5de6f693c559 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/91a08c3a1240c4e23cd1 for a full test report.

**Comment by boegel** [comment]
(finally) good to go, thanks for the review @fgeorgatos!

**Pull request merged**
