### PR TITLE
New EasyConfig for GMP 6.1.0 with the foss-2015a toolchain

### PR DESCRIPTION
**Pull request by valtandor**
Required for GRASS 7.0.2 dependency tree.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5ae16cf0a1ebe5c187fa for a full test report.

**Comment by boegel** [comment]
@valtandor: please merge https://github.com/valtandor/easybuild-easyconfigs/pull/5 to sync up this GMP easyconfig with the others we already have

**Comment by valtandor** [comment]
Merge done.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/aa4a629cadaaf5906ff3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
