### PR TITLE
wxPython with foss2016a

### PR DESCRIPTION
**Pull request by RvDijk**

### CODE REVIEW

**Comment by RvDijk** [comment]
Dependencies on #3353 #3352 #3351 #3350

**Comment by boegel** [comment]
@RvDijk tests detected conflicts:

```
Conflict found for dependencies of wxPython-3.0.2.0-foss-2016a-Python-2.7.11: NASM-2.12.01-foss-2016a vs NASM-2.12.02-foss-2016a 
	NASM-2.12.01-foss-2016a as dep of: FFmpeg-2.8.7-foss-2016a, FFmpeg-3.0.2-foss-2016a, GConf-3.2.6-foss-2016a, GTK+-2.24.30-foss-2016a, Gdk-Pixbuf-2.35.1-foss-2016a, OpenCV-3.1.0-foss-2016a, libjpeg-turbo-1.4.2-foss-2016a-NASM-2.12.01, wxPython-3.0.2.0-foss-2016a-Python-2.7.11
	NASM-2.12.02-foss-2016a as dep of: R-3.3.1-foss-2016a, libjpeg-turbo-1.5.0-foss-2016a, wxPython-3.0.2.0-foss-2016a-Python-2.7.11
Conflict found for dependencies of wxPython-3.0.2.0-foss-2016a-Python-2.7.11: libjpeg-turbo-1.4.2-foss-2016a-NASM-2.12.01 vs libjpeg-turbo-1.5.0-foss-2016a 
	libjpeg-turbo-1.4.2-foss-2016a-NASM-2.12.01 as dep of: GConf-3.2.6-foss-2016a, GTK+-2.24.30-foss-2016a, Gdk-Pixbuf-2.35.1-foss-2016a, OpenCV-3.1.0-foss-2016a, wxPython-3.0.2.0-foss-2016a-Python-2.7.11
	libjpeg-turbo-1.5.0-foss-2016a as dep of: R-3.3.1-foss-2016a, wxPython-3.0.2.0-foss-2016a-Python-2.7.11
```

**Comment by RvDijk** [comment]
version of GST-plugin and GStreamer has to be 0.10, including these as deps for foss2016a.

**Comment by boegel** [comment]
@RvDijk it seems like the branch on which you based is way behind on `develop`, cfr. the failing tests reported by Travis (e.g. https://travis-ci.org/hpcugent/easybuild-easyconfigs/jobs/160383723)...

It's kind of strange this occurs though, since Travis is supposed to test your PR after merging it with `develop`...

@RvDijk can you try syncing your branch here with current `develop`?

Maybe you should start using `--new-pr` instead? Cfr. http://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html

**Comment by boegel** [comment]
@RvDijk hmm, no, something else is wrong, since the tests for `develop` are suddenly failing too now, must be a bug that crept in via a merged PR in `easybuild-framework`...

So, no need to sync your branch at all, I need to fix this in `develop` (either in `easybuild-framework` or in `easybuild-easyconfigs`).

**Comment by boegel** [comment]
@RvDijk failing tests will be fixed once https://github.com/hpcugent/easybuild-framework/pull/1913 is merged, I'll retrigger testing for this PR then

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2461.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8142a6b34ddc9300d795bfe7d65a5dd2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2071.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/06dd5bc458f4551c389543d503ab1247 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @RvDijk!

**Pull request merged**
