### PR TITLE
{math}[intel/2015a] numpy 1.9.2 + scipy 0.15.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a72a0b4c500366e69211 for a full test report.

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks for the review!

**Pull request merged**
