### PR TITLE
{toolchain}[dummy/dummy] CrayGNU v2016.04

### PR DESCRIPTION
**Pull request by gppezzi**
Tested on Piz Daint and Titan (to build EBs from https://github.com/hpcugent/easybuild-easyconfigs/pull/3219)

### CODE REVIEW

**Comment by boegel** [comment]
@gppezzi please include an HPL easyconfig + submit test reports?

**Comment by gppezzi** [comment]
Test report by @gppezzi
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
daint101 - Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.6
See https://gist.github.com/e2bdb9a3ec8c3ebe682f7da4a4d1ea48 for a full test report.

**Comment by gppezzi** [comment]
@boegel Done

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @gppezzi!

**Pull request merged**
