### PR TITLE
{bio}[foss/2015a} PhyloCSF 20150118 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires #2016

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c1c2201d0a2fb9a65a9c for a full test report.

**Comment by rjeschmi** [comment]
looks fine except for the release tag.

I wonder if the version as the date is better than the release...

**Comment by rjeschmi** [comment]
and I don't have a better solution than using the commit id, so it is fine

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/961d9b95bf63989b83ab for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @rjeschmi!

**Pull request merged**
