### PR TITLE
added spglib for cray

### PR DESCRIPTION
**Pull request by gppezzi**

### CODE REVIEW

**Comment by pforai** [comment]
Test report by @pforai
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/6cb4909c0c005ad2970c for a full test report.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/d6f91a6e43be191ad77f for a full test report.

**Comment by pforai** [comment]
LGTM!

**Comment by boegel** [comment]
Good to go, thanks @gppezzi! Keep up the pace. ;-)

**Pull request merged**
