### PR TITLE
{lang}[foss/2015a] Python 2.7.10 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
(synced up with #1638)

### CODE REVIEW

**Comment by JensTimmerman** [comment]
see remarks in https://github.com/hpcugent/easybuild-easyconfigs/pull/1639

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5a158f055ee3cdc0baf8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/46e3032e5752c287fb97 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8bfd6d6b7ce6661b927c for a full test report.

**Comment by boegel** [comment]
Thanks for reviewing @JensTimmerman!

**Pull request merged**
