### PR TITLE
{lang}[goolf/1.5.14] Python 2.7.9 + deps (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review/test? (my test report is on it's way)

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SL 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a4155159cf5cb053297e for a full test report.

**Comment by boegel** [comment]
going in, thanks for the review @wpoely86!

**Pull request merged**
