### PR TITLE
{chem}[dummy/dummy] ADF v2014.02

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5dc0186d104b96ce3eb5 for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @wpoely86!

**Pull request merged**
