### PR TITLE
{lib}[GCCcore/5.4.0] nettle v3.2

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Fix for #4696

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2453.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/67841a9998d87465e05947407ac9d346 for a full test report.

**Comment by boegel** [comment]
lgtm, please look into a follow-up PR to make `sanity_check_paths` consistent in the existing `nettle` easyconfigs @vanzod

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2061.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2165bf1ed8381ded0f36c4608d3008af for a full test report.

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
