### PR TITLE
{lib}[intel/2016b] libspatialindex v1.8.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2617.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d1456c27f8a144bcad5c7255f4b98f7f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2127.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/693ccef046850f75807feb2e3b444f89 for a full test report.

**Comment by boegel** [comment]
@verdurin please review? (trivial imho)

**Comment by verdurin** [comment]
@boegel looks good.

**Comment by boegel** [comment]
Thanks for the review @verdurin!

**Pull request merged**
