### PR TITLE
fix mpi4py source_urls in Python easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
fixes remark made by @wpoely86 in #1291

### CODE REVIEW

**Comment by wpoely86** [comment]
looks fine, only 1 remark: use `BITBUCKET_DOWNLOADS` :wink:

**Comment by boegel** [comment]
actually, I don't think that trick works for extensions...

**Comment by boegel** [comment]
@wpoely86: doesn't work (yet):

== 2015-01-15 22:49:28,075 main.filetools DEBUG Trying to download mpi4py-1.3.1.tar.gz from http://bitbucket.org/%(namelower)s/%(namelower)s/downloads/mpi4py-1.3.1.tar.gz to /Users/kehoste/.local/easybuild/sources/p/Python/extensions/mpi4py-1.3.1.tar.gz

**Comment by boegel** [comment]
opened https://github.com/hpcugent/easybuild-framework/issues/1138, not blocking this PR because of that

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
