### PR TITLE
{lib,vis}[intel/2015a] GeoIP 1.3.2 + vincent 0.4.4 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
cc @ehiggs

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 5 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/dac7991e292cc5fa0247 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 10 (3 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c6cabfa9be240a909c3f for a full test report.

**Comment by boegel** [comment]
failed tests are due to a bug in framework `develop`, which gets triggered by the extra easyconfig parameter that is defined in the `numpy` easyblock (cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/757);
installing numpy as an extension is now broken, working on a fix

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d69c619c4db9f19da24f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5eb66248a4eece42ed2e for a full test report.

**Comment by rjeschmi** [comment]
looks fine

**Comment by boegel** [comment]
just a toolchain bump, going in

**Comment by boegel** [comment]
@rjeschmi: thanks for the review! :)

**Pull request merged**
