### PR TITLE
{tools,vis}[intel/2015a] Ghostscript 9.16 + cairo 1.14.2 + GLib 2.44.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
synced with #1705 by @npklein, equivalent easyconfigs with `intel/2015a`

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 8 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c01f8076838495d0c587 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7fd98262872f3f606c5b for a full test report.

**Comment by JensTimmerman** [comment]
ok

**Comment by boegel** [comment]
Thanks @JensTimmerman!

**Pull request merged**
