### PR TITLE
{bio}[intel/2015a] GROMACS 5.0.4 (mt, hybrid) (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/513

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

GROMACS 5.0.4 doesn't seem to suffer from the problems discussed at https://mailman-1.sys.kth.se/pipermail/gromacs.org_gmx-users/2014-September/091975.html and http://permalink.gmane.org/gmane.science.biology.gromacs.user/76485 anymore \o/

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
well, the combination of GROMACS 5.0.4 and `intel/2015a` is fine, but the hybrid build still fails with `ictce/7.1.2`...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2514d825ce8ecfdb6f1c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f6b2b54b2ed16ff218dd for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/d997a6938d530fd1385b for a full test report.

**Comment by boegel** [comment]
tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/513, looking good

Thanks @wpoely86 for the review/testing!

**Pull request merged**
