### PR TITLE
enable -fPIC in all zlib 1.2.8 easyconfigs 

### PR DESCRIPTION
**Pull request by boegel**
required for https://github.com/hpcugent/easybuild-easyconfigs/pull/2133

(and remove optarch=True, since it's the default)

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 32 out of 32 (32 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/aedc3b4b4ab85fbc98c0 for a full test report.

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
