### PR TITLE
add patch for XZ 5.2.2 to include 5.1.2alpha symbols required by 'rpm' command on CentOS 7.x

### PR DESCRIPTION
**Pull request by boegel**
fix for #4036

cc @verdurin, @hajgato: please test whether this also fixes the problem for you?

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in this PR)
node2107.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0dc26e0eb246e5c5b9a85752b2ed4d5a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node2521.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/01681049b92a8c6fa232f2257a2b4079 for a full test report.

**Comment by boegel** [comment]
I've validated that this indeed fixes the issue reported in #4036, and I didn't notice any fallout after rebuilding all `intel/2016b` easyconfigs that use XZ 5.2.2 as a dependency, so going in!

**Comment by hajgato** [comment]
@boegel I know it is a bit late, but this `XZ` patch solved the  problem with `R` and `CentOS 7.3`

**Comment by boegel** [comment]
:+1: Thanks for the feedback @hajgato!

**Comment by JensTimmerman** [comment]
This breaks xz  (or at least rpm, that is linked with the system xz) on newer systems. e.g. fedora > 27 and centos8
 removing this patch again makes things work there.

**Pull request merged**
