### PR TITLE
{mpi}[GCC/6.3.0-2.27] OpenMPI v2.0.2

### PR DESCRIPTION
**Pull request by henkela**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by henkela** [comment]
A version for OmniPath instead of ib

**Comment by akesandgren** [comment]
Change the comment "needed for --with-verbs" to match what it really is about.

**Comment by boegel** [comment]
@henkela I can't test this, since we don't have any Omnipath systems...

Can you look into submitting a test report? Cfr. http://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#github-upload-test-report

**Comment by henkela** [comment]
Test report by @henkela
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login23 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/65e61c32b996a3890698b5d62f50dc5b for a full test report.

**Comment by boegel** [comment]
Excellent, thanks @henkela!

Don't hesitate to also submit test reports for other PRs! :)

**Pull request merged**
