### PR TITLE
ABINIT 7.6.2 w/ patches

### PR DESCRIPTION
**Pull request by AFCJamie**
An EasyConfig for ABINIT version 7.6.2 using the foss 2015a toolchain. This includes two patches which were needed to get Fortran to co-operate. The patches derive from the solutions obtained at these locations:
 https://lists.debian.org/debian-mentors/2014/08/msg00475.html and
 http://forum.abinit.org/viewtopic.php?f=3&t=2656.

EDIT: Also, there is Open MPI 2.0.0 and the dependencies hwloc 1.11.3 and numactl 2.0.11 all with the toolchain GCC 5.2.0.

### CODE REVIEW

**Comment by boegel** [comment]
@AFCJamie can you open a separate PR for the easyconfigs for OpenMPI 2.0.0 & deps, since they're unrelated to ABINIT?

**Comment by AFCJamie** [comment]
Okay, will do.

**Comment by AFCJamie** [comment]
Would it be easier to close this pull request and make two new ones (one for ABINIT and one for Open MPI) or just make one new one for the Open MPI easyconfigs?

**Comment by boegel** [comment]
@AFCJamie opening two new PRs will be cleaner since removing the OpenMPI easyconfigs here could potentially lead to a mess (i.e. the easyconfigs may be gone after both this PR and the OpenMPI one get merged)

**Pull request closed without merging**
