### PR TITLE
{lib}[foss/2016b,intel/2016b] libdrm v2.4.70 - add missing deps (libpthread-stubs, libpciaccess)

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Depends on #4029 and #4031

**Comment by boegel** [comment]
@verdurin please fix the subject for this one?

**Comment by boegel** [comment]
@verdurin: these are still missing?

```
ERROR: Irresolvable dependencies encountered: libpthread-stubs/0.3-foss-2016b, libpciaccess/0.13.4-intel-2016b
```

**Comment by verdurin** [comment]
Fixed in #4034

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2585.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ca5509efb0d2beae412d189d3ddd5b72 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2005.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5fff3265d06969bc42e1e8ab583554a5 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
