### PR TITLE
{lang}[foss/2015b] R 3.2.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
depends on #1724 for libreadline, zlib, Tcl, Tk, ncurses easyconfigs

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1918da287624f3c9bc66 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 7 out of 8 (6 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/82c63dbddd44900a7b8a for a full test report.

**Comment by boegel** [comment]
download link for BiocInstaller 1.16.3 is broken...

see https://support.bioconductor.org/p/69175/

**Comment by boegel** [comment]
@hajgato, @backelj: bumped version of BiocInstaller extension (again), to 1.16.5 (cfr. https://support.bioconductor.org/p/69175), please retest?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/89401f4961fc7f5fd2d6 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 8 out of 8 (6 easyconfigs in this PR)
Linux SL 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/23e4f3ae41872c58ba0b for a full test report.

**Comment by backelj** [comment]
Test report by @backelj
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/384a95b61e5b79638aeb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5d302601da1330636b43 for a full test report.

**Comment by boegel** [comment]
@backelj: here's what I get from your test report:

```
gcc -Wl,--export-dynamic -fopenmp  -L../../lib -L/apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64
-L/apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib
-L/apps/antwerpen/easybuild/test/software/OpenBLAS/0.2.14-GNU-5.1.0-2.25-LAPACK-3.5.0/lib
-L/apps/antwerpen/easybuild/test/software/ScaLAPACK/2.0.2-gompi-2015b-OpenBLAS-0.2.14-LAPACK-3.5.0/lib
-L/apps/antwerpen/easybuild/test/software/FFTW/3.3.4-gompi-2015b/lib -L/apps/antwerpen/easybuild/test/software/libreadline/6.3-foss-2015b/lib
-L/apps/antwerpen/easybuild/test/software/ncurses/5.9-foss-2015b/lib -L/apps/antwerpen/easybuild/test/software/libpng/1.6.17-foss-2015b/lib
-L/apps/antwerpen/easybuild/test/software/libjpeg-turbo/1.4.0-foss-2015b/lib -L/apps/antwerpen/easybuild/test/software/Java/1.7.0_80/lib
-o R.bin Rmain.o  -lR 
../../lib/libR.so: undefined reference to `inflateReset'
../../lib/libR.so: undefined reference to `inflateEnd'
../../lib/libR.so: undefined reference to `compress'
../../lib/libR.so: undefined reference to `deflate'
../../lib/libR.so: undefined reference to `inflateInit2_'
../../lib/libR.so: undefined reference to `inflate'
../../lib/libR.so: undefined reference to `crc32'
../../lib/libR.so: undefined reference to `deflateEnd'
../../lib/libR.so: undefined reference to `zlibVersion'
../../lib/libR.so: undefined reference to `deflateInit2_'
../../lib/libR.so: undefined reference to `uncompress'
```

It seems like we're missing a (direct) dependency on zlib? It's a weird problem, since zlib is listed as a dependency for `libpng`, and so the corresponding module *is* loaded...

@backelj: can you locate `libR.so` in the R build directory, and show us the output of `ldd` on it? Preferably after loading the modules that R depends on

**Comment by backelj** [comment]
Here's the list of (non-intel related) modules in our test-environment:

    $ module av 2>&1 | grep -v intel
    ------------------ /apps/antwerpen/easybuild/test/modules/all ------------------
    Autoconf/2.69-GNU-5.1.0-2.25
    Automake/1.15-GNU-5.1.0-2.25
    Autotools/20150215-GNU-5.1.0-2.25
    binutils/2.25
    binutils/2.25-GCC-5.1.0-binutils-2.25
    bzip2/1.0.6-foss-2015b
    FFTW/3.3.4-gompi-2015b
    foss/2015b
    GCC/5.1.0-binutils-2.25
    GNU/5.1.0-2.25
    gompi/2015b
    HPL/2.1-foss-2015b
    hwloc/1.11.0-GNU-5.1.0-2.25
    icc/2015.3.187-GNU-5.1.0-2.25
    iccifort/2015.3.187-GNU-5.1.0-2.25
    ifort/2015.3.187-GNU-5.1.0-2.25
    iimpi/7.3.5-GNU-5.1.0-2.25
    imkl/11.2.3.187-iimpi-7.3.5-GNU-5.1.0-2.25
    impi/5.0.3.048-iccifort-2015.3.187-GNU-5.1.0-2.25
    Java/1.7.0_80
    Java/1.8.0_25
    libjpeg-turbo/1.4.0-foss-2015b
    libpng/1.6.16-foss-2015b
    libpng/1.6.17-foss-2015b
    libreadline/6.3-foss-2015b
    libtool/2.4.6-GNU-5.1.0-2.25
    M4/1.4.17-GNU-5.1.0-2.25
    NASM/2.11.06-foss-2015b
    ncurses/5.9-foss-2015b
    numactl/2.0.10-GNU-5.1.0-2.25
    OpenBLAS/0.2.14-GNU-5.1.0-2.25-LAPACK-3.5.0
    OpenMPI/1.8.6-GNU-5.1.0-2.25
    Perl/5.20.2-foss-2015b-bare
    Perl/5.22.0-foss-2015b-bare
    Python/2.7.10-foss-2015b
    ScaLAPACK/2.0.2-gompi-2015b-OpenBLAS-0.2.14-LAPACK-3.5.0
    SQLite/3.8.10.2-foss-2015b
    Tcl/8.6.4-foss-2015b
    Tk/8.6.4-foss-2015b-no-X11
    zlib/1.2.8
    zlib/1.2.8-foss-2015b
    zlib/1.2.8-GCC-5.1.0-binutils-2.25

These are the dependencies for R-3.2.0:

    dependencies = [
        ('libreadline', '6.3'),
        ('ncurses', '5.9'),
        ('libpng', '1.6.17'),  # for plotting in R
        ('libjpeg-turbo', '1.4.0'),  # for plottting in R
        ('Java', '1.7.0_80', '', True)

Loading the dependencies:

    $ module load libreadline/6.3-foss-2015b
    $ module load libpng/1.6.17-foss-2015b
    $  module load libjpeg-turbo/1.4.0-foss-2015b
    $ module load Java/1.7.0_80

Now check with ldd for the libR.so files in our build-directory:

    cd /apps/antwerpen/easybuild/build/R
    $ for file in `find . -name libR.so | grep foss` ; do echo "----- $file -----" ; ldd $file ; done

    ----- ./3.2.0/foss-2015b-bare/R-3.2.0/src/main/libR.so -----
    	linux-vdso.so.1 =>  (0x00007fff067ff000)
    	libopenblas.so.0 =>     /apps/antwerpen/easybuild/test/software/OpenBLAS/0.2.14-GNU-5.1.0-2.25-LAPACK-3.5.0/lib/libopenblas.so.0 (0x00002b12ebecb000)
    	libgfortran.so.3 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64/libgfortran.so.3 (0x00002b12ecd3e000)
    	libreadline.so.6 => /apps/antwerpen/easybuild/test/software/libreadline/6.3-foss-2015b/lib/libreadline.so.6 (0x00002b12ed05f000)
    	libncurses.so.5 => /apps/antwerpen/easybuild/test/software/ncurses/5.9-foss-2015b/lib/libncurses.so.5 (0x00002b12ed2a7000)
    	librt.so.1 => /lib64/librt.so.1 (0x00002b12ed502000)
    	libdl.so.2 => /lib64/libdl.so.2 (0x00002b12ed70a000)
    	libm.so.6 => /lib64/libm.so.6 (0x00002b12ed90f000)
    	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b12edb93000)
    	libgomp.so.1 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64/libgomp.so.1 (0x00002b12eddb0000)
    	libc.so.6 => /lib64/libc.so.6 (0x00002b12edfd2000)
    	/lib64/ld-linux-x86-64.so.2 (0x00002b12eb66a000)
    	libquadmath.so.0 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib/../lib64/libquadmath.so.0 (0x00002b12ee366000)
	libgcc_s.so.1 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib/../lib64/libgcc_s.so.1 (0x00002b12ee5a5000)

    ----- ./3.2.0/foss-2015b-bare/R-3.2.0/lib/libR.so -----
    	linux-vdso.so.1 =>  (0x00007fff715ff000)
    	libopenblas.so.0 => /apps/antwerpen/easybuild/test/software/OpenBLAS/0.2.14-GNU-5.1.0-2.25-LAPACK-3.5.0/lib/libopenblas.so.0 (0x00002b3017a4d000)
   	libgfortran.so.3 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64/libgfortran.so.3 (0x00002b30188c0000)
    	libreadline.so.6 => /apps/antwerpen/easybuild/test/software/libreadline/6.3-foss-2015b/lib/libreadline.so.6 (0x00002b3018be1000)
    	libncurses.so.5 => /apps/antwerpen/easybuild/test/software/ncurses/5.9-foss-2015b/lib/libncurses.so.5 (0x00002b3018e29000)
    	librt.so.1 => /lib64/librt.so.1 (0x00002b3019084000)
    	libdl.so.2 => /lib64/libdl.so.2 (0x00002b301928c000)
    	libm.so.6 => /lib64/libm.so.6 (0x00002b3019491000)
    	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b3019715000)
    	libgomp.so.1 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64/libgomp.so.1 (0x00002b3019932000)
    	libc.so.6 => /lib64/libc.so.6 (0x00002b3019b54000)
    	/lib64/ld-linux-x86-64.so.2 (0x00002b30171ec000)
    	libquadmath.so.0 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib/../lib64/libquadmath.so.0 (0x00002b3019ee8000)
    	libgcc_s.so.1 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib/../lib64/libgcc_s.so.1 (0x00002b301a127000)

    ----- ./3.1.3/foss-2015b/R-3.1.3/src/main/libR.so -----
    	linux-vdso.so.1 =>  (0x00007fff6fdff000)
    	libopenblas.so.0 => /apps/antwerpen/easybuild/test/software/OpenBLAS/0.2.14-GNU-5.1.0-2.25-LAPACK-3.5.0/lib/libopenblas.so.0 (0x00002ab001052000)
    	libgfortran.so.3 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64/libgfortran.so.3 (0x00002ab001ec5000)
    	libreadline.so.6 => /apps/antwerpen/easybuild/test/software/libreadline/6.3-foss-2015b/lib/libreadline.so.6 (0x00002ab0021e6000)
    	libncurses.so.5 => /apps/antwerpen/easybuild/test/software/ncurses/5.9-foss-2015b/lib/libncurses.so.5 (0x00002ab00242e000)
    	librt.so.1 => /lib64/librt.so.1 (0x00002ab002689000)
    	libdl.so.2 => /lib64/libdl.so.2 (0x00002ab002891000)
    	libm.so.6 => /lib64/libm.so.6 (0x00002ab002a96000)
    	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ab002d1a000)
    	libgomp.so.1 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64/libgomp.so.1 (0x00002ab002f37000)
    	libc.so.6 => /lib64/libc.so.6 (0x00002ab003159000)
    	/lib64/ld-linux-x86-64.so.2 (0x00002ab00087a000)
    	libquadmath.so.0 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib/../lib64/libquadmath.so.0 (0x00002ab0034ed000)
    	libgcc_s.so.1 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib/../lib64/libgcc_s.so.1 (0x00002ab00372c000)

    ----- ./3.1.3/foss-2015b/R-3.1.3/lib/libR.so -----
    	linux-vdso.so.1 =>  (0x00007fff11b9f000)
    	libopenblas.so.0 => /apps/antwerpen/easybuild/test/software/OpenBLAS/0.2.14-GNU-5.1.0-2.25-LAPACK-3.5.0/lib/libopenblas.so.0 (0x00002b84a08cb000)
    	libgfortran.so.3 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64/libgfortran.so.3 (0x00002b84a173e000)
    	libreadline.so.6 => /apps/antwerpen/easybuild/test/software/libreadline/6.3-foss-2015b/lib/libreadline.so.6 (0x00002b84a1a5f000)
    	libncurses.so.5 => /apps/antwerpen/easybuild/test/software/ncurses/5.9-foss-2015b/lib/libncurses.so.5 (0x00002b84a1ca7000)
    	librt.so.1 => /lib64/librt.so.1 (0x00002b84a1f02000)
    	libdl.so.2 => /lib64/libdl.so.2 (0x00002b84a210a000)
    	libm.so.6 => /lib64/libm.so.6 (0x00002b84a230f000)
    	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b84a2593000)
    	libgomp.so.1 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib64/libgomp.so.1 (0x00002b84a27b0000)
    	libc.so.6 => /lib64/libc.so.6 (0x00002b84a29d2000)
    	/lib64/ld-linux-x86-64.so.2 (0x00002b84a00f3000)
    	libquadmath.so.0 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib/../lib64/libquadmath.so.0 (0x00002b84a2d66000)
    	libgcc_s.so.1 => /apps/antwerpen/easybuild/test/software/GCC/5.1.0-binutils-2.25/lib/../lib64/libgcc_s.so.1 (0x00002b84a2fa5000)

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 8 out of 9 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3a78a5c43f5bc3ff43ce for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/88574db7f6113e24bf68 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8ad243eeea63f8267bd2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 6 out of 9 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/1daf6640085371cce685 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/84f22a0be8d8a120299e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/d7aa13d0b4d30f7c3b97 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9051a7e1022891c67ad0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7b95ca55d6581de05ab7 for a full test report.

**Comment by boegel** [comment]
Failed build on RHEL6@Haswell system is caused by missing OpenGL/Mesa required for rgl package, since it's not provided by the OS there.

I've opened #1935 to discuss this and figure out the best solution (I'm no longer 100% convinced that we should be spending time on building Mesa, and including it as a dep for R, for example), I won't block PR over this.

**Comment by boegel** [comment]
Going in, thanks for reviewing/testing everyone!

**Comment by backelj** [comment]
Test report by @backelj
**FAILED**
Build succeeded for 11 out of 14 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/ed18689bc22f6bf10439 for a full test report.

**Comment by boegel** [comment]
@backelj: missing 'source' tarball for Java?

**Comment by backelj** [comment]
Test report by @backelj
**SUCCESS**
Build succeeded for 3 out of 3 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/bef3dd91c141c4438599 for a full test report.

**Pull request merged**
