### PR TITLE
{debugger}[GCC/4.9.2] GDB 7.8.2 (OK)

### PR DESCRIPTION
**Pull request by gjbex**
Add easyconfig for latest GDB version.

### CODE REVIEW

**Comment by gjbex** [comment]
Test report by @gjbex
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.6
See https://gist.github.com/13416e50a8ae2ad14012 for a full test report.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2da9e4fb00a5cbe9774c for a full test report.

**Comment by boegel** [comment]
@gjbex: Jenkins isn't happy with the filename, since it doesn't match the used toolchain, please fix?

**Comment by gjbex** [comment]
Test report by @gjbex
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.4, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.6
See https://gist.github.com/d7da876064f10a139e7c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0d1b6e254a02f26932c8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @gjbex!

**Pull request merged**
