### PR TITLE
add sanity check paths for FPM

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-easyblocks/pull/667 (see also https://github.com/hpcugent/easybuild-easyblocks/issues/646)

### CODE REVIEW

**Comment by boegel** [comment]
@rjeschmi: please review

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3e852b297f7e88a02292 for a full test report.

**Comment by boegel** [comment]
Good to go now is merged in, thanks for the review @wpoely86!

**Pull request merged**
