### PR TITLE
{perf}[*] Cube update (REVIEW)

### PR DESCRIPTION
**Pull request by geimer**
* Add easyconfig for latest Cube release which no longer includes the Java reader (now distributed as a separate package) and therefore doesn't require the `configopts` trickery anymore
 * Added checksums
 * Fixed sanity checks for Cube 4.x (lib vs. lib64)
 * Cosmetics

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/619f59cc7c444b141770 for a full test report.

**Comment by geimer** [comment]
Unfortunately, I can't provide a test report for the other configurations, as
they all depend on
`Qt-4.8.4-gompi-1.4.12-no-OFED`, which depends on
`GLib-2.34.3-gompi-1.4.12-no-OFED`, which depends on
`Python-2.5.6-gompi-1.4.12-no-OFED-bare`, which doesn't build on my system...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 23 out of 23 (6 easyconfigs in this PR)
Linux RHEL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a3cfb13db0dc3a7b5e61 for a full test report.

**Comment by boegel** [comment]
reviewed, looks fine, full test report turns out fine on my end, so good to go

Thanks @geimer!

**Pull request merged**
