### PR TITLE
rename R bundles so they don't conflict on each other

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@ehiggs: please review

**Comment by ehiggs** [comment]
This is v. much needed. Good fix. +1.

**Comment by boegel** [comment]
I had to include custom `sanity_check_paths` too, because of https://github.com/hpcugent/easybuild-easyblocks/pull/627

**Comment by boegel** [comment]
Thanks for the review @ehiggs!

**Pull request merged**
