### PR TITLE
{devel}[foss-/intel-2017a,GCCcore-6.3.0] pkg-config: Work around build failure with GCC 6

### PR DESCRIPTION
**Pull request by geimer**
While this isn't needed by anything yet, I'm sure people will run into this rather sooner than later...

### CODE REVIEW

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
swat - Linux debian 7.11, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/a5cd706c915b48e084728f1ab5e2d5c4 for a full test report.

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
swat - Linux debian 7.11, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/e78448909f752840235fe2d412114d8a for a full test report.

**Comment by geimer** [comment]
I've added configurations for `GCCcore-6.3.0` and `intel-2017a`.  This should cover full toolchains as well as a hierarchy with minimal toolchains.

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
swat - Linux debian 7.11, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/e559281a5ba4365e9a1e00d377e3e43b for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2605.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/320a32288b7e0ce4433f4a61afcff71f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2086.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7879cc30034e0fcad2184b5e749db499 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @geimer!

**Pull request merged**
