### PR TITLE
added NFFT for cray

### PR DESCRIPTION
**Pull request by gppezzi**

### CODE REVIEW

**Comment by pforai** [comment]
Test report by @pforai
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/e1105e93ea7d6c9f247c for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/bd15ec08c31785568707 for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/47b5f7e97dde457569bc for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/7f3acc409dcda760f268 for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/f97eda9bceb14b8dc0a5 for a full test report.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/5ebb0706dd80d69c79c1 for a full test report.

**Comment by boegel** [comment]
Looking great, going in.

Congratulations on your first official contribution @gppezzi!

**Pull request merged**
