### PR TITLE
New EasyConfig for LLVM 3.7.0 with the foss-2015b toolchain

### PR DESCRIPTION
**Pull request by iotaka**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
duplicate of #2459

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
oops, different toolchain, sorry @iotaka!

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@iotaka: please mention why you're closing a PR; in this case, it's because you're looking into a PR for LLVM 3.7.1 instead, right?

**Comment by iotaka** [comment]
Closed because I'm working on LLVM 3.7.1

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2460
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8006 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/5eb534d54cfa84cd22ae168fa4f6f6af for a full test report.

**Pull request closed without merging**
