### PR TITLE
{data}[intel/2015a] nco v0.0.2 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
(close/open to trigger Travis tests)

**Comment by boegel** [comment]
good to go no imho

@wpoely86 please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2028.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9d04938db8650eb39dc64846bb6a9fc1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 15 out of 15 (4 easyconfigs in this PR)
node2485.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d72af58fee9fe568f10cbdd794aced7f for a full test report.

**Comment by wpoely86** [comment]
Toolchain/versions bumps?

**Comment by boegel** [comment]
@wpoely86 this is a very old PR, I'd rather get this merged as is (as opposed to closing it)

**Comment by wpoely86** [comment]
:+1:

**Pull request merged**
