### PR TITLE
{lib} [*] Drop the `-shared` flag passed when building zlib (REVIEW)

### PR DESCRIPTION
**Pull request by wpoely86**
For some unknown reason, we pass the -shared flag to CC
when building GCC. This overwrites some stuff in the configure script
which we don't want to override. The zlib.map is not being used when
build the so file.

I think this can solve some of the `no version information available` warnings.

### CODE REVIEW

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, AMD Opteron(tm) Processor 6380, Python 2.6.6
See https://gist.github.com/dea38add20c80645f84d for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos 6.5, AMD Opteron(tm) Processor 6380, Python 2.6.6
See https://gist.github.com/f54944ec1a8a8d69a4f3 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/0a47dad39f937d65ad7a for a full test report.

**Comment by ocaisa** [comment]
Tested this in an instance where we build zlib with `dummy` and make it a dependence of all compilers. Afterwards, no longer reported any warnings with `emacs`

**Comment by pescobar** [comment]
this is working fine for me. I no longer see the "no version information available" warnings.

**Comment by wpoely86** [comment]
Great success

@boegel ready to merge

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 14 out of 24 (21 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4435a24343686e2ad2ec for a full test report.

**Comment by wpoely86** [comment]
@boegel holy crap. What did you do? A failed `cp`? :confused:

**Comment by pescobar** [comment]
please merge this one.... thanks @wpoely86 !!

**Comment by boegel** [comment]
The failed `cp` for `zlib-1.2.5-ictce-4.0.6.eb` signals a problem caused by this change: `libz.so` is no longer built. Same problem for the other `zlib-1.2.5` easyconfigs.

For `zlib-1.2.7-ictce-3.2.2.u3.eb`, the sanity check fails with `libz.so` not being there anymore, but `zlib-1.2.7-foss-2014b.eb` is OK.

So, we have figured out why the `LDSHARED` line is there in the easyconfigs...

It seems to be needed for zlib v1.2.5 with any (Intel-based) toolchain, and when building zlib v1.2.7 with ictce v3.x (the easyconfigs for ictce v4.x and later don't have the `LDSHARED` line, and are not showing issues).

@wpoely86: excluding the line is required because the zlib Makefile includes something extra in `LDSHARED` which gets overwritten, right? In any case, we need to figure out how to get the `libz.so` built for the older zlib versions without it being broken w.r.t. the version stuff...

The `iqacml` builds failed because of toolchain issues, that's my bad.

**Comment by wpoely86** [comment]
@boegel Okay, I think I've nailed it. Try again?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 19 out of 24 (21 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/04c64228c3ffc2f22bbe for a full test report.

**Comment by wpoely86** [comment]
@boegel Fixed, I hope. Not quite sure if the `iqacml` will need the patch or not.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, AMD Opteron(tm) Processor 6136, Python 2.6.6
See https://gist.github.com/fa5216973dd58d04f563 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, AMD Opteron(tm) Processor 6136, Python 2.6.6
See https://gist.github.com/5c892ef772e45dc451e8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 19 out of 19 (19 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c9c99bb9097fb22fada7 for a full test report.

**Comment by wpoely86** [comment]
Everybody happy :smiley:

**Comment by boegel** [comment]
Going in, thanks a lot for tackling this @wpoely86!

**Pull request merged**
