### PR TITLE
Boost 1.52.0 with foss 2015a

### PR DESCRIPTION
**Pull request by AFCJamie**
An easyconfig for Boost 1.52.0 built with the toolchain foss 2015a.

I know there are many versions of Boost already, but I noticed this one was missing.

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2539.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f548ccbbc2ec22ee4027f19bee7fbcd9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2130.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d7f16b3a3a78ea6f2f3996689a4462d1 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @AFCJamie!

**Comment by AFCJamie** [comment]
Thanks!

**Pull request merged**
