### PR TITLE
rename libint2 easyconfigs as Libint v2 easyconfigs, fix homepage

### PR DESCRIPTION
**Pull request by boegel**
wraps around #1145: updated with current `develop`, fix `easyblock` spec, also sync `homepage` spec

depends on https://github.com/hpcugent/easybuild-easyblocks/pull/536

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review

@hajgato: this builds on top of your PR #1145, more things needed to be changed since there also was a custom easyblock for `libint2` (see https://github.com/hpcugent/easybuild-easyblocks/pull/536)

**Comment by wpoely86** [comment]
Looks fine.

@tovrstra You probably wanna know see this :wink:

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 18 out of 19 (19 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/51bf1d43f6f2e5af5278 for a full test report.

**Comment by boegel** [comment]
tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/536

the single build that failed failed due to some fluke, it works fine when I tested it stand-alone

so, merge https://github.com/hpcugent/easybuild-easyblocks/pull/536 and this

Thanks for the review @wpoely86!

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 14 out of 19 (19 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/205b5fd85b95d3634aab for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/dc18b9e61f1e214e5856 for a full test report.

**Comment by boegel** [comment]
For some reason, getting all of these builds to pass in a singe go is difficult... There's nothing really broken though.

And CP2K v2.5.1 (see #1144) and v2.6.0 work fine on top of this.

I'll give it one last try, but this should be good to go in.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 15 out of 19 (19 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a8542441188c6fe05228 for a full test report.

**Comment by boegel** [comment]
Going in regardless of the occasionally failing tests, there's really no issue when I'm running these individually.

Thanks for the review @wpoely86!

**Pull request merged**
