### PR TITLE
{devel}[GNU-4.9.3-2.25] Autotools 20150215 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires ~~#1836~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9d02ec06aaa6798950c2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4c14a2b64cf43fe2fedc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/9f140c5023ca934a6ffa for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9fa144d531971c0b103e for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.6.6
See https://gist.github.com/95a063a6f26528c78827 for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review/test this too on Debian? Thoroughly testing the things related to 2015b doesn't hurt imho...

**Comment by wpoely86** [comment]
looks fine, I've haven't installed the whole new toolchain yet, so cannot test this. But it should be fine.

**Comment by boegel** [comment]
OK, let's go ahead and merge this one too, so we can make some progress.

**Comment by boegel** [comment]
Thanks for testing/reviewing @hajgato and @wpoely86!

**Pull request merged**
