### PR TITLE
{lib}[intel/2016b] gdc-client v1.0.1, libxslt v1.1.29, libyaml v0.1.6 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2577.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/824849b0c7187509fe2d802c674021b5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/93e17b8a11c58f7e58ad576e6e9efed9 for a full test report.

**Comment by boegel** [comment]
@verdurin please review?

**Comment by verdurin** [comment]
Looks fine to me and it builds without any problems.

**Comment by boegel** [comment]
Thanks for the review @verdurin!

**Pull request merged**
