### PR TITLE
{math}[intel/2015a] MUMPS 5.0.1 w/ METIS/ParMETIS (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
test case for ~~https://github.com/hpcugent/easybuild-easyblocks/pull/657~~ https://github.com/hpcugent/easybuild-easyblocks/pull/686

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/04eac0312eb4ae1d59fe for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8e20e7c15af96285bacb for a full test report.

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Comment by boegel** [comment]
Good to go now https://github.com/hpcugent/easybuild-easyblocks/pull/686 is merged in.

**Pull request merged**
