### PR TITLE
{math}[intel/2015a] sympy 0.7.6 w/ Python 2.7.10 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
For some reason unclear to me, making sympy pass the test suite on top of Python 2.7.10 on CentOS 7 requires the patch included, while it's not required on SL6...

### CODE REVIEW

**Comment by tovrstra** [comment]
I checked the patch and it is actually surprising that it worked without it. I will try it as well, just to be sure.

**Comment by tovrstra** [comment]
I just have one comment. Compared to the older eb files, you have extended the CPATH variable for the tests. I believe this is redundant. I quickly checked by letting easybuild stop after the build phase:

    eb sympy-0.7.6-intel-2015a-Python-2.7.10.eb -s build

Then I just ran the problematic test manually without altering CPATH:

    Python 2.7.10 (default, Jun 29 2015, 11:54:45) 
    [GCC Intel(R) C++ gcc 4.9 mode] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sympy
    sympy.test('sympy/external/tests/test_autowrap.py')
    >>> sympy.test('sympy/external/tests/test_autowrap.py')
    ======================================================================== test process starts =========================================================================
    executable:         /apps/gent/CO7/haswell-ib/software/Python/2.7.10-intel-2015a/bin/python  (2.7.10-final-0) [CPython]
    architecture:       64-bit
    cache:              yes
    ground types:       python 
    random seed:        17139957
    hash randomization: on (PYTHONHASHSEED=1822511612)

    sympy/external/tests/test_autowrap.py[11] ...........                                                                                                             [OK]

    ============================================================ tests finished: 11 passed, in 62.48 seconds =============================================================
    True
    >>> 

That seems to work fine. I'll remove the CPATH from the eb and test it.

**Comment by boegel** [comment]
@tovrstra: you're right, the `$CPATH` thing isn't needed, it's a previous attempt of mine to fix the issue you were running into, I'll kick it out

**Comment by boegel** [comment]
I'm running into the same problem with Python 2.7.9 on CentOS 7... Still no clue why this doesn't occur on SL6.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/75e6ce43d8ecd8c4a2db for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/03fbb7ebfdd2d892fb0d for a full test report.

**Comment by tovrstra** [comment]
Just to confirm: my build without `CPATH` in the test line just finished successfully on golett (centos 7.1.1503). Thank you for fixing this problem!! Are you still interested in understanding what went wrong in the first place? If so, we should figure out why it did compile properly on SL6. It shouldn't have worked and the patch fixes something that is clearly a mistake.

**Comment by boegel** [comment]
Well, turns out the explanation is rather simple:

On SL6:
```
$ locate arrayobject.h
/usr/include/python2.6/bytearrayobject.h
/usr/lib64/python2.6/site-packages/numpy/core/include/numpy/arrayobject.h
/usr/lib64/python2.6/site-packages/numpy/core/include/numpy/ndarrayobject.h
$ rpm -q --whatprovides /usr/lib64/python2.6/site-packages/numpy/core/include/numpy/arrayobject.h
numpy-1.4.1-9.el6.x86_64
```

The numpy RPM is not installed on CentOS 7.

So, basically, we need this patch in all other sympy easyconfigs too...

**Comment by boegel** [comment]
For some reason, this fix is not needed in sympy 0.7.2, seems to work just fine on CentOS7...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0b7d9ba1d444d0f9d86c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/bfc0b97452d380faecda for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @tovrstra!

**Pull request merged**
