### PR TITLE
Add warning about Tk and X

### PR DESCRIPTION
**Pull request by wpoely86**
To build Tk, you need an X11 stack. All current python easyconfig need
X11 to build. Follow up in
https://github.com/hpcugent/easybuild-easyconfigs/issues/2261

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by backelj** [comment]
@wpoely86 @boegel : I have the same issue when building Tk-8.6.6-intel-2017a.eb, it needs X11, but there's no warning in those easyconfig files — what's the reasoning behind this? Should this not be a (os)-dependency?

**Comment by wpoely86** [comment]
@backelj No particular reason other then we haven't done it yet :wink:
Add a dep to the X11 bundle in `Tk-8.6.6-intel-2017a.eb` and you should be fine.

I think X11 is a bit too much to drag in as a OS dep.

**Comment by jrbosch** [comment]
builddependencies or dependencies??. boegel suggests builddependencies in issue #2261 . See [https://github.com/hpcugent/easybuild-easyconfigs/issues/2261#issuecomment-196709139]

**Pull request merged**
