### PR TITLE
{geo}[intel/2015b] ALADIN 36t1_op2bf1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires ~~#2203~~

requires https://github.com/hpcugent/easybuild-easyblocks/pull/764

patch files was updated because recent versions of `patch` commands flag relative paths like `../arp/climate/updcpl.F90` potentially harmful, and refuse to apply the patch file

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/883d068647c769449f85 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/194f2f359dedd4dd71bd for a full test report.

**Comment by boegel** [comment]
good to go now https://github.com/hpcugent/easybuild-easyblocks/pull/764 is merged in

**Pull request merged**
