### PR TITLE
[intel/2015a] Perl v5.20.1 (bare) (ready)

### PR DESCRIPTION
**Pull request by boegel**
cc @hpcleuven, @gjbex, @sbecuwe, @hajgato

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8ac97b0cd55aae8e2903 for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
looks fine but why not add the 'full' version too?

**Comment by boegel** [comment]
@wpoely86: because then I need to bump all extension versions, I don't have time for that now...

A bare Perl module is something we agreed upon in the VSC, to have that available everywhere.

So, this is a first step, the 'full' version can be tackled later.

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
