### PR TITLE
{bio} [foos/2014b] cutadapt (REVIEW)  

### PR DESCRIPTION
**Pull request by pescobar**
download urls updated

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**FAILED**
Build succeeded for 13 out of 19
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/3238ceee1d3d902e2026 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5368db596d1eef8abada for a full test report.

**Comment by boegel** [comment]
Looks fine, going in, thanks @fgeorgatos!

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 4 out of 19 (5 easyconfigs in this PR)
Linux centos 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fdd43993a8d8e95f6a04 for a full test report.

**Pull request merged**
