### PR TITLE
Adjust PSI4 easyconfigs for updated easyblock

### PR DESCRIPTION
**Pull request by wpoely86**
hpcugent/easybuild-easyblocks#967

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 why close this?

**Comment by wpoely86** [comment]
Oeps, I thought his was merged. Why wasn't it?

**Comment by boegel** [comment]
@wpoely86 because https://github.com/hpcugent/easybuild-easyblocks/pull/967 isn't merged yet (which needs to be tested with existing PSI4 easyconfigs)

**Comment by wpoely86** [comment]
@boegel all changes in that PR are behind an if that will never be true with any of the old easyconfigs...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2047.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f73af07ce3cfe26142531def61b264d8 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2636.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/813a9b83582b69882ac09ae3d3c5b481 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @wpoely86!

**Pull request merged**
