### PR TITLE
{lang}[goolf/1.5.14] R 3.1.2 + deps (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review/test? (my test report is on it's way)

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/64e84a43792db0d8702d for a full test report.

**Comment by boegel** [comment]
going in, thanks for the review @wpoely86!

cc @Bart-CER: this is a cleaned up version of your R easyconfig included in #1280

**Pull request merged**
