### PR TITLE
EasyConfig for GROMACS 3.3.3 (old version with functionality that has since been removed)

### PR DESCRIPTION
**Pull request by valtandor**
New EasyConfig for GROMACS 3.3.3. This EasyConfig includes support for MPI parallelisation only as OpenMP is apparently not properly supported until a later version.

### CODE REVIEW

**Comment by scintimandrion** [comment]
No.

**Comment by scintimandrion** [comment]
An updated GROMACS EasyBlock is required before this config file can be properly tested.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2003.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f851894907a1c7c414f734ff75068ad0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2114.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/183e4a6ec91ab0d2053726636ecf98be for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2029.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0a135e4ad05550da3ed0b55926e3dd02 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2029.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8458bbb7e569fd38d9f72c4b9dda2769 for a full test report.

**Comment by boegel** [comment]
tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/960, good to go, thanks @valtandor!

**Pull request merged**
