### PR TITLE
{vis} [intel/2016b] ImageMagick/7.0.3-1 (REVIEW)

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 lgtm, but let's also see some test reports ;)

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
node2001.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8e1286b8eb6b16c48dbbf1d0e047faee for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
node2447.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0171b5272559773d9356917d77901289 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2084.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fa26ef972b965d7ea2c6ca9112a6956c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @wpoely86!

**Pull request merged**
