### PR TITLE
{devel}  QT changed urls (REVIEW)

### PR DESCRIPTION
**Pull request by backelj**
- changed source_urls and homepage

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by backelj** [comment]
@boegel: Trying to keep the PR's small, I've renamed my previous branch "modules/various" to "modules/qt". I got your message about the previous PR (1671) but I cannot find it here anymore, but you may close that one and we'll use this one instead.

**Comment by boegel** [comment]
@backelj: ok, makes sense, thanks

#1671 was closed by you removing the branch (and the comment is at https://github.com/hpcugent/easybuild-easyconfigs/pull/1671#issuecomment-108924607 ;-))

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 12 out of 13 (13 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f6933dd9afd8723427bc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/aac9353850d2e91df9b8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @backelj!

**Comment by backelj** [comment]
@boegel: Should I change anything to the title here?

**Comment by boegel** [comment]
@backelj: no, closed PRs are closed ;)

**Pull request merged**
