### PR TITLE
add patch for Tk 8.6.4 to fix problem with tk.tcl not being found

### PR DESCRIPTION
**Pull request by boegel**
fix for

```
    window = Tk.Tk()
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/2.7.10-intel-2015b/lib/python2.7/lib-tk/Tkinter.py", line 1814, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Tcl/8.6.4-intel-2015b/lib/tcl8.6/tk8.6 /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Tcl/8.6.4-intel-2015b/lib/tk8.6 /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/2.7.10-intel-2015b/lib/tk8.6 /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/lib/tk8.6 /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/2.7.10-intel-2015b/library
```

see also https://github.com/hpcugent/easybuild-easyblocks/issues/728#issuecomment-152257327

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
I verified that this patch indeed fixes the problem.

Thanks for the review @wpoely86!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/da1b23866cc9b235007a for a full test report.

**Pull request merged**
