### PR TITLE
Easyconfig for installing hub 2.2.2

### PR DESCRIPTION
**Pull request by nathanhaigh**

### CODE REVIEW

**Comment by boegel** [comment]
@nathanhaigh: any particular reason you closed this?

**Comment by nathanhaigh** [comment]
Sorry, i was testing hub for issuing the pull request from the command line and this didn't do exactly what i wanted.

**Comment by boegel** [comment]
@nathanhaigh: what aspect isn't exactly like you wanted? Seems to work OK? Just wondering...

If you close a PR, please mention why, for future reference.

**Comment by boegel** [comment]
Alternative PR for hub is in #2249

**Pull request closed without merging**
