### PR TITLE
Feature/autohell

### PR DESCRIPTION
**Pull request by gjbex**
EBs for autotools (autoconf, automake, m4) based on GCC 4.9.2

### CODE REVIEW

**Comment by wpoely86** [comment]
ok to test

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/cd6a9dd88d7c96317037 for a full test report.

**Comment by boegel** [comment]
Works like a charm, going in, thanks for the review @wpoely86!

**Pull request merged**
