### PR TITLE
Create Lmod-7.3.eb

### PR DESCRIPTION
**Pull request by serge-p**
Lmod 7.3

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

@serge-p Please target the `develop` branch in future pull requests (I'll change it myself for this PR).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2625.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/64d2a1611e4f08d408db0faa4670adb7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2111.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/895b971f73c0c94d1c2ed0127fea0621 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @serge-p!

**Comment by serge-p** [comment]
@boegel  Thanks for a quick merge! srry picked master branch by accident :)

**Pull request merged**
