### PR TITLE
{bio}[intel/2016a] NGS-Python 1.2.3 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
depends on #2803, #2808

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2717.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f0658d00cda51f56f55ae0f3713910c7 for a full test report.

**Comment by boegel** [comment]
@rjeschmi please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2140.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c3bd0c58a579957fac71a244fecc6bfd for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by rjeschmi** [comment]
looks good

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 9 out of 14 (1 easyconfigs in this PR)
maraba - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.7.11
See https://gist.github.com/8a3d0bf82b65edcff655334fdf8656d6 for a full test report.

**Comment by boegel** [comment]
@rjeschmi more downloads problems?

```
gzip: stdin: unexpected end of file
```

**Comment by boegel** [comment]
Thanks for the review @rjeschmi!

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
maraba - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.7.11
See https://gist.github.com/8b7d9c760f88d35b9e878c26f3b58b72 for a full test report.

**Pull request merged**
