### PR TITLE
ictce-5.4.1

### PR DESCRIPTION
**Pull request by valtandor0**
New version of the ictce toolchain with a different MPI version.

### CODE REVIEW

**Comment by fgeorgatos** [comment]
@valtandor0: either make this complete (ie. add/explain missing easyconfigs) or,
if you think this no longer requires attention, simply close the issue.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by valtandor0** [comment]
I don't think we need this branch any more.

**Comment by fgeorgatos** [comment]
if so, whomever owns it, please close it...

On 3 June 2015 at 22:24, valtandor0 <notifications@github.com> wrote:

> I don't think we need this branch any more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-easyconfigs/pull/1123#issuecomment-108619761>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by valtandor0** [comment]
I understand that I just did close the pull request, as well as deleting the branch in my fork. Is there something more I have to do?

**Comment by fgeorgatos** [comment]
ok, ok. all good. If there is anything else that has to be followed up
(from your point of view) just let it be known.

On 3 June 2015 at 22:29, valtandor0 <notifications@github.com> wrote:

> I understand that I just did close the pull request, as well as deleting
> the branch in my fork. Is there something more I have to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-easyconfigs/pull/1123#issuecomment-108620947>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Pull request closed without merging**
