### PR TITLE
{bio}[intel/2016b] SAMtools v1.3.1, HTSlib v1.3.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires https://github.com/hpcugent/easybuild-easyblocks/pull/1048

### CODE REVIEW

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
ottbioinfo.openstacklocal - Linux centos linux 7.2.1511, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/9bbd89cf4e9dc1e5df62c57021bcea2d for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
ottbioinfo.openstacklocal - Linux centos linux 7.2.1511, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/8775a80843f3fb3defc6f69793b2dc5a for a full test report.

**Comment by rjeschmi** [comment]
Works fine under foss-2016a. I'll build foss-2016b as well

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2610.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/419f271a760a1d8ebbc0aa5863c87c94 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node1134.muk.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5f4d74fb5060d6ce9628878028ed0555 for a full test report.

**Comment by boegel** [comment]
Thanks for the review/test @rjeschmi!

**Pull request merged**
