### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by iotaka**
New EasyConfig for LLVM 3.7.0 with the foss-2015b toolchain 

[LLVM-3.7.0-foss-2015b.eb.zip](https://github.com/hpcugent/easybuild-easyconfigs/files/114115/LLVM-3.7.0-foss-2015b.eb.zip)

### CODE REVIEW

**Comment by boegel** [comment]
@iotaka: this is probably not what you intended to do?

**Comment by iotaka** [comment]
New EasyConfig for LLVM 3.7.0 with the foss-2016a
[LLVM-3.7.0-foss-2016a.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/114188/LLVM-3.7.0-foss-2016a.txt)

 toolchain

**Comment by boegel** [comment]
@iotaka: this looks pretty broken to me, should be closed? Especially since #2467 is merged already.

**Comment by iotaka** [comment]
@boegel , yes, we can close it, was a test / mistake

**Pull request closed without merging**
