### PR TITLE
bump Bioconductor 3.1 package versions

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@rjeschmi, @pescobar: please review?

**Comment by boegel** [comment]
@ehiggs: maybe you can review this? I think you mentioned running into problems here?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/027e5768081bc0e38cf9 for a full test report.

**Comment by rjeschmi** [comment]
looks fine I'll test soon

**Comment by boegel** [comment]
Thanks for the review @rjeschmi!

**Pull request merged**
