### PR TITLE
fix software name for OrthoMCL + modernise OrthoMCL easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
I'm deliberately not renaming the patch file since that may have fallback for other OrthoMCL easyconfig not under our control.

### CODE REVIEW

**Comment by boegel** [comment]
@verdurin please review?

**Comment by verdurin** [comment]
Not familiar with the original, but the updated versions look fine to me.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2100.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0b8fc13ff1cb2fb377ba531a828e801a for a full test report.

**Comment by boegel** [comment]
Thanks for the review @verdurin!

**Pull request merged**
