### PR TITLE
bcftools-1.1-goolf-1.4.10.eb

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**SUCCESS**
Build succeeded for 1 out of 1
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/2e854739ec1ec05c80bc for a full test report.

**Comment by rjeschmi** [comment]
deprecated functionality (easyblock not declared).

I'll PR that for @pescobar

**Comment by boegel** [comment]
@rjeschmi: thanks, please mention the PR in here

**Comment by rjeschmi** [comment]
Oh, I forgot to mention the PR @boegel, but @pescobar has merged it now. I think this should test properly (I'll do that soon, I might need coffee first).

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
Linux centos 6.6, Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz, Python 2.6.6
See https://gist.github.com/46f9dcb20d72c1ea6950 for a full test report.

**Comment by boegel** [comment]
@rjeschmi: please use `--force` when testing ;-)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/91611d1f78a03a0fd6f7 for a full test report.

**Comment by boegel** [comment]
OK, it worked for @rjeschmi, so going in.

Thanks @pescobar!

**Pull request merged**
