### PR TITLE
{compiler,tools}[GCCcore/5.4.0,dummy/] PGI v16.7, numactl v2.0.11

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jhein32** [comment]
What is the status on this?  We would be interested to see this build up to a full pomkl (PGI, OpenMP, MKL).    Are the remaining files in another PR?

**Comment by boegel** [comment]
@jhein32 I basically need to get a test report included here. No PR for a full `pomkl` on top of this yet (we don't use a PGI-based toolchain ourselves).

Are you up for looking into that?

**Comment by jhein32** [comment]
I am not sure what you mean with test-report?

As far as I understand git, if you were to merge what there is into “develop”, I could pick it up and see whether I can extend this to a full pomkl.  Alternatively, if you tell me, how I could move what you have into my branch ...

Would we version the pompi and pomkl as 2016.07?

But I am at a loss why to have a numactl if you don’t want to build an MPI for it.

J.


On 30 Aug 2016, at 15:37, Kenneth Hoste <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhein32<https://github.com/jhein32> I basically need to get a test report included here. No PR for a full pomkl on top of this yet (we don't use a PGI-based toolchain ourselves).

Are you up for looking into that?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2646.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ff4057866afc392d6b159f57d5be6f12 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2050.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9e6abfcfb4a0a6a08eac26e8888cf761 for a full test report.

**Comment by boegel** [comment]
trivial version bump, thanks for bringing this back into view @jhein32!

**Comment by boegel** [comment]
@jhein32 now in `develop`, using `2016.07` as toolchain version for `pompi` and `pomkl` makes sense to me!

`numactl` is included as a dependency to PGI to avoid that the one shipped with it is used, cfr. https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/p/pgi.py#L146

**Pull request merged**
