### PR TITLE
{bio}[goolf/1.4.10,Python/2.7.3] MACS2 2.1.0.20150731 (REVIEW)

### PR DESCRIPTION
**Pull request by dominikborkowski**
Created easyconfig for MACS2: Model-based Analysis of ChIP-Seq.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@dominikborkowski: please merge https://github.com/dominikborkowski/easybuild-easyconfigs/pull/2 to fix some style issues here (yes, we can be picky ;-))

**Comment by fgeorgatos** [comment]
just click the merge button here: https://github.com/dominikborkowski/easybuild-easyconfigs/pull/2

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@fgeorgatos: we can issue a wrapper PR for this too, if it's only a matter of style fixes

**Comment by boegel** [comment]
@fgeorgatos: see 1983

**Pull request merged**
