### PR TITLE
{vis}[goolf/1.4.10] Xmipp 3.1

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-easyblocks/pull/630 AND ~~https://github.com/hpcugent/easybuild-easyblocks/pull/631~~

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar: please review/test?

**Comment by boegel** [comment]
@pescobar: please review/test?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux RHEL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/94f5555de3bd9f18ec64 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux RHEL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fce59bffb27c402266a0 for a full test report.

**Comment by pescobar** [comment]
it looks fine for me

**Comment by boegel** [comment]
Thanks for the review @pescobar!

Going in, now https://github.com/hpcugent/easybuild-easyblocks/pull/630 is merged.

**Pull request merged**
