### PR TITLE
fix python 3.5.2 compilation with all toolchains

### PR DESCRIPTION
**Pull request by arif-ali**
Fix the compilation of Python

Had various issues with README file, and realised the patches were not included in 3.5.2, but were for 3.5.1

### CODE REVIEW

**Comment by boegel** [comment]
@arif-ali nice catch, thanks! Do you mind making that same change in the other easyconfigs for `Python` 3.5.2 that we currently have in `develop?

**Comment by arif-ali** [comment]
sure, no worries, I will update the PR in a bit

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2668.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/054ecfc8907d075271175d7555de7aa0 for a full test report.

**Comment by boegel** [comment]
@arif-ali ignore the failed test report, there's probably something wrong in my module stack there... it's not a problem with your PR

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2636.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f547b8e53d3f62763a61603bd8141e42 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @arif-ali!

**Pull request merged**
