### PR TITLE
{vis}[foss/2016a] libXi 1.7.6 (REVIEW) 

### PR DESCRIPTION
**Pull request by jrbosch**
libXi 1.7.6 for foss-2016a toolchain

### CODE REVIEW

**Comment by hajgato** [comment]
@jrbosch check PR #2760

**Comment by hajgato** [comment]
@jrbosch and PRs #2578 #2758

**Comment by jrbosch** [comment]
@boegel In this case should I close my PR?

**Comment by boegel** [comment]
Jenkins: ok to test

@jrbosch I'll take a detailed look at your and @hajgato's PRs (in particular, whether there are any important changes between them), and see how things can be merged.

I'll come back to this later, don't hesitate to poll for an update in case you don't hear back.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2604.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a7716f190fd429d3cb47a7643ddf59c8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
gligar03.gligar.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/bd295c1545b0b4bce589f94b3504600b for a full test report.

**Comment by boegel** [comment]
@hajgato The easyconfigs in this PR are basically identical to the ones in your (bigger) PRs, except that `XORG_LIB_SOURCE` is being used in th `fixesproto` easyconfig (as it should be), so I'll go ahead and merge this, and ask you to sync up your branches where needed.

Thanks @jrbosch!

**Pull request merged**
