### PR TITLE
add CMake as missing build dep for MultiNest

### PR DESCRIPTION
**Pull request by boegel**
requires #2167

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: you missed this during review ;-)

I didn't notice either because `cmake` was provided by the OS on the test system.

**Comment by wpoely86** [comment]
@boegel maybe should add a test for this?

**Comment by boegel** [comment]
@wpoely86: patches welcome ;-)

**Comment by wpoely86** [comment]
@boegel I will put it somewhere on my todo list. Might be done by next year :laughing:

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/4da8507042f533bbf4d6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e22e776c6de69b83a860 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Pull request merged**
