### PR TITLE
{bio}[foss-2015a,goolf-1.4.10] Samtools 1.2 update (REVIEW)

### PR DESCRIPTION
**Pull request by rjeschmi**
mainly a version bump

### CODE REVIEW

**Comment by rjeschmi** [comment]
depends on a new easyblock, (incoming)

**Comment by wpoely86** [comment]
ok to test

**Comment by rjeschmi** [comment]
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/562

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fa7fd14226b93384817d for a full test report.

**Comment by boegel** [comment]
tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/562, looks great, so going in, thanks @rjeschmi!

**Pull request merged**
