### PR TITLE
Add style checks

### PR DESCRIPTION
**Pull request by wpoely86**
@boegel @rjeschmi 
Based on pep8. The first test will fail as example. Will push fixes in a moment.

### CODE REVIEW

**Comment by wpoely86** [comment]
retest this please

**Comment by boegel** [comment]
@wpoely86: most of the code supporting the style checks should be added in framework, so we can also use it in `--new-pr`; here, you can import from `easybuild.framework.easyconfig.style` (or whatever)

**Comment by boegel** [comment]
@wpoely86: all PRs that include style checks merged, please sync with `develop`?

**Comment by boegel** [comment]
@wpoely86 replaced by #2506 ?

**Comment by wpoely86** [comment]
Yes, see #2506

**Pull request closed without merging**
