### PR TITLE
{lib}[dummy/dummy] tbb v2017.6.196

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by JackPerdue** [comment]
Looked like low fruit.... and we just had a talk from some Intel guys and some of the things at  http://sdvis.org/  ... looking at updating my builds for Embree and OSPRay in hopes of building a badass ParaView that doesn't necessarily need a GPU.   

Suggestions welcome... I just bumped the version number and reformatted as I find the prettiest.

**Comment by JackPerdue** [comment]
I guess the "'4.0" part could've been left out of the description.

Here was our week:  https://sites.google.com/a/tamu.edu/rcompweek/home/agenda

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2104.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7e0f4fc1b0c2aa0cdf42e5f923b688cd for a full test report.

**Comment by boegel** [comment]
@JackPerdue lgtm, thanks, I'll clean up the '4.0' in the description in a separate PR

**Comment by boegel** [comment]
Going in, thanks @JackPerdue!

**Pull request merged**
