### PR TITLE
{math}[intel/2016a] gdist v1.0.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2688.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/49f6144686116c8d2708f45a3bcd03c9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2149.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/598406886899e70e73494975e41a2163 for a full test report.

**Comment by boegel** [comment]
@wpoely86 please review?

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Thanks @wpoely86!

**Pull request merged**
