### PR TITLE
{bio}[dummy] Coot 0.8.1 (Review)

### PR DESCRIPTION
**Pull request by a-mazur**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz, Python 2.7.6
See https://gist.github.com/45ea178f1c3c33301693 for a full test report.

**Comment by pescobar** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Jenkins is happy, test report is there, so looking great!

Thanks a lot @a-mazur, and welcome to the wonderful world of EasyBuild!

Going in...

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos 6.6, Intel(R) Xeon(R) CPU           E5440  @ 2.83GHz, Python 2.6.6
See https://gist.github.com/16a27cd61d2c91cca6fc for a full test report.

**Comment by rjeschmi** [comment]
whoops, typo test :)

**Pull request merged**
