### PR TITLE
Added missing space in Geant4 configopts

### PR DESCRIPTION
**Pull request by damianam**

### CODE REVIEW

**Comment by boegel** [comment]
nice catch @damianam, lgtm

**Comment by damianam** [comment]
It wasn't mine, a colleague told me ;-)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in this PR)
node2160.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f68ec6291e50e79c76201efe67c524fb for a full test report.

**Comment by boegel** [comment]
Going in, thanks @damianam!

**Pull request merged**
