### PR TITLE
binutils with foss 2016a

### PR DESCRIPTION
**Pull request by RvDijk**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@RvDijk I don't mind merging this, but it's a little bit weird since `binutils` is already part of `foss/2016a` (underneath `GCC`)...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2724.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c2390ca8b79f819d8ae4def11c1b7537 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2078.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d6bbf847470736f0fd62fa36679ce07e for a full test report.

**Comment by RvDijk** [comment]
@boegel in that case this pr does not have to be merged? Can it be closed?

**Comment by boegel** [comment]
@RvDijk Well, it depends... :)

`foss/2016a` provides binutils 2.25 inside, so there's no need to specify `binutils` as a (build) dependency when building with `foss/2016a`.

However, this is an easyconfig for binutils 2.26. If you really need 2.26 together with `foss/2016a`, you may need this easyconfig.

I doubt that's going to work though, I saw some incompatibilities between mixing binutils 2.25 and 2.26 pop up (cfr. https://github.com/hpcugent/easybuild-easyconfigs/pull/2524#issuecomment-186423631).

I would recommend closing this, and sticking to the binutils 2.25 that's included in `foss/2016a`.

**Pull request closed without merging**
