### PR TITLE
New horton easyconfig

### PR DESCRIPTION
**Pull request by tovrstra**
I have not been able to test exactly this version of the horton easyconfig. (LibInt is tested.) I had to modify the h5py dependency, which has evolved a little since I last looked at it.

When I try to install `h5py-2.5.0-intel-2015b-Python-2.7.10-HDF5-1.8.15-patch1-serial.eb` with easybuild 2.6.0 on a delcatty node, I get the following output:

    == temporary log file in case of crash /local/2192208.master15.delcatty.gent.vsc/eb-yLEWO7/easybuild-m0EmkA.log
    == processing EasyBuild easyconfig /vscmnt/gent_vulpix/_/user/data/gent/gvo000/gvo00003/apps_cmm/work/jobs/h5py-2.5.0-intel-2015b-Python-2.7.10-HDF5-1.8.15-patch1-serial.eb
    == building and installing h5py/2.5.0-intel-2015b-Python-2.7.10-HDF5-1.8.15-patch1-serial...
    == fetching files...
    == creating build dir, resetting environment...
    == unpacking...
    == patching...
    == preparing...
    == configuring...
    == building...
    == testing...
    == installing...
    == taking care of extensions...
    == postprocessing...
    == sanity checking...
    == FAILED: Installation ended unsuccessfully (build directory: /user/data/gent/gvo000/gvo00003/apps_cmm/work/builds/delcatty/h5py/2.5.0/intel-2015b-Python-2.7.10-HDF5-1.8.15-patch1-serial): build failed (first 300 chars): Changing environment as dictated by module failed: invalid syntax (<string>, line 1) (stdout: umask 002;
    os.environ['MANPATH'] = '/usr/local/share/man:/usr/share/man'
    os.environ['MODULEPATH'] = '/local/2192208.master15.delcatty.gent.vsc/eb-yLEWO7/tmpJ8PEoS/all:/user/data/gent/gvo000/gvo00003/vsc4001
    == Results of the build can be found in the log file /local/2192208.master15.delcatty.gent.vsc/eb-yLEWO7/easybuild-h5py-2.5.0-20160301.155442.EQmbd.log
    ERROR: Build of /vscmnt/gent_vulpix/_/user/data/gent/gvo000/gvo00003/apps_cmm/work/jobs/h5py-2.5.0-intel-2015b-Python-2.7.10-HDF5-1.8.15-patch1-serial.eb failed (err: "build failed (first 300 chars): Changing environment as dictated by module failed: invalid syntax (<string>, line 1) (stdout: umask 002;\nos.environ['MANPATH'] = '/usr/local/share/man:/usr/share/man'\nos.environ['MODULEPATH'] = '/local/2192208.master15.delcatty.gent.vsc/eb-yLEWO7/tmpJ8PEoS/all:/user/data/gent/gvo000/gvo00003/vsc4001")

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by tovrstra** [comment]
Hmm, ik heb eens gekeken. Ik weet niet goed wat er misloopt. De volgende melding is alvast een misverstand: You may have some typos in your easyconfig file: hdf5versionsuffix -> versionsuffix'. Dat was niet per ongeluk.

**Comment by boegel** [comment]
@tovrstra (we stick to English in this repo ;))

I'm already looking into this, cfr. https://github.com/tovrstra/easybuild-easyconfigs/compare/cmmsoft3...boegel:cmmsoft3

I'm testing that easyconfig now, will issue a PR to your branch when it builds.

**Comment by tovrstra** [comment]
ok. thanks!

**Comment by boegel** [comment]
@tovrstra: see https://github.com/tovrstra/easybuild-easyconfigs/pull/3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/412e91c1b2e1862ca055 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @tovrstra!

**Pull request merged**
