### PR TITLE
add --with-zlib configure argument in libxml easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
cfr. suggestion by @pescobar in #2551

### CODE REVIEW

**Comment by pescobar** [comment]
thanks for the quick fix @boegel  :)

looks good to me but I would suggest a rebuild test because I am not sure if all the libxml2 versions have the ```--with-zlib``` option . I have only tested this with libxml2-2.9.3

**Comment by boegel** [comment]
Thanks for the review @pescobar.

The oldest libmlx2 version we have easyconfigs for supports it:

```
-bash-4.1$ cd libxml2-2.8.0
-bash-4.1$ ./configure --help | grep zlib
  --with-zlib[=DIR]       use libz in DIR
```

Test report on the way.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 46 out of 46 (46 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0ecc79eac892195f99d2 for a full test report.

**Comment by boegel** [comment]
boom!

Going in, thanks @pescobar!

**Pull request merged**
