### PR TITLE
cutadapt-1.4.1-goolf-1.4.10-Python-2.7.5.eb

### PR DESCRIPTION
**Pull request by pescobar**
updated to latest release

updated download url. Now code is on github and no longer in googlecode.

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**FAILED**
Build succeeded for 0 out of 2
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/b66e75629f609646f675 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/aa2f0586ef7cdf524450 for a full test report.

**Comment by boegel** [comment]
bumped into this when handling a recent PR for cutadapt, still working fine, so going in

Thanks @pescobar!

**Pull request merged**
