### PR TITLE
{bio}[intel/2016a] NGS v1.2.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@rjeschmi please review?

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
crick - Linux centos 6.6, AMD Opteron(tm) Processor 6380, Python 2.7.8
See https://gist.github.com/d51ca56cd542a7ba10634a1fa7a2acf4 for a full test report.

**Comment by boegel** [comment]
@rjeschmi Thanks for testing; can you give this a visual review too?

**Comment by rjeschmi** [comment]
Looks good. Are you going to do the Python bindings as well? I don't need them, but might be good for completeness.

**Comment by rjeschmi** [comment]
Also should there be a standard header so we know the maintainer?

**Comment by boegel** [comment]
@rjeschmi The Python bindings are separate, see #2810; I needed to dance around the chicken-egg situation with NGS and ncbi-vdb...

We can discuss a standard header, maybe open a separate issue on that.
I wouldn't track this in each easyconfig file though, maybe in a separate file per software package?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2717.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2d5ae9f00b3b6475ac0ddf8bd3d08559 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2140.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ccb127f565e0a5631357802c966d36ac for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @rjeschmi!

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
maraba - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.7.11
See https://gist.github.com/810e8f14c883c783adc8d7e1ce37c201 for a full test report.

**Pull request merged**
