### PR TITLE
{bio}[intel/2016a] ncbi-vdb v2.5.8-1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
depends on #2803

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2717.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/248da7f4cff8164b760477c16eb4e3c0 for a full test report.

**Comment by boegel** [comment]
@rjeschmi please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2140.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/461d2c1ef86b0b157036aafed2a48047 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by rjeschmi** [comment]
Looks good

**Comment by boegel** [comment]
Going in, thanks for the review @rjeschmi!

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
maraba - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.7.11
See https://gist.github.com/6ddc3a321f6b271a4a38c7f38900a045 for a full test report.

**Pull request merged**
