### PR TITLE
Don't run the Bloom tests for Jellyfish, they can randomly fail

### PR DESCRIPTION
**Pull request by JensTimmerman**

### CODE REVIEW

**Comment by JensTimmerman** [comment]
@fgeorgatos these are actually random tests, that randomly fail. The bloom filter is a data structure with some random properties, the tests test these random properties, but because of randomness they somtimes fail, it's a bad test, the author told me it was, and we can safely skip it. so, good to go?

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@JensTimmerman: test report (re)submitted, ping me when it comes back (I won't be notified)

**Comment by boegel** [comment]
@JensTimmerman: please sync this with `develop`, test report fails because easyconfig file doens't include an `easyblock` line yet (unit tests don't catch this, because they check post merge with develop)

This actually raises an important issue with the test reports... :-/

**Comment by JensTimmerman** [comment]
@boegel rebased on develop

**Comment by boegel** [comment]
Hmm, I saw this same change in another PR (and now I can't find it anymore...)

**Comment by boegel** [comment]
Ah, found it again: #1035.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/fb64b5ea6578d2ca0cc2 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @JensTimmerman!

**Pull request merged**
