### PR TITLE
specify correct MPI target in FDS easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
fix for #3459

TODO: add sanity check command that verifies that `fds` has MPI support?

```
$ fds<enter><enter>

 Fire Dynamics Simulator

 Current Date     : August 26, 2016  19:43:10
 Version          : FDS 6.3.0
 Revision         : unknown
 Revision Date    : unknown
 Compilation Date : unknown

 MPI Enabled; Number of MPI Processes:     1
 OpenMP Disabled

 Consult FDS Users Guide Chapter, Running FDS, for further instructions.

 Hit Enter to Escape...

$ echo '' | fds 2>&1 | grep 'MPI Enabled'
 MPI Enabled; Number of MPI Processes:     1
$ echo $?
0

```

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2539.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/bfb7372643d02c42e569a917a4812c80 for a full test report.

**Comment by lpouillo** [comment]
I'll check that monday morning.
Thanks a lot for the reactivity.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 6 (6 easyconfigs in this PR)
node2051.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/75975fdd0e626f00e8b25eed6f78f8e3 for a full test report.

**Comment by boegel** [comment]
@lpouillo any feedback on this?

**Comment by lpouillo** [comment]
Sorry I am installing a new visualization server this morning, I'll do that ASAP.

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2427.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3f2d28d7634f96a879589a0c31fa25eb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2062.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/50347b2d1b1974beb26625d64b8b443c for a full test report.

**Comment by boegel** [comment]
I added a custom sanity check command to make sure `fds` reports that it is MPI-aware...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2610.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1bfcf0b09e3606074bae12e914071b54 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2001.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ff2abb7de714fc195d87f5da0baae395 for a full test report.

**Comment by boegel** [comment]
with the sanity check commands in place and the above test reports, I consider this good to go

@lpouillo don't hesitate to let us know whether this fix works for you as well!

**Pull request merged**
