### PR TITLE
fix source_urls in QuantumESPRESSO 5.0.2 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
issue uncovered in https://github.com/hpcugent/easybuild-easyconfigs/pull/1644, also relates to https://github.com/hpcugent/easybuild-easyblocks/pull/618

### CODE REVIEW

**Comment by boegel** [comment]
with this in place, downloading the QuantumESPRESSO 5.0.2 source tarballs works (again), even without having https://github.com/hpcugent/easybuild-easyblocks/pull/618 in place

**Comment by JensTimmerman** [comment]
where did the 'wannier90-1.2.tar.gz' go to?

**Comment by boegel** [comment]
The source tarball is still there; I'm only changing the source URLs here, and downloading `wannier90-1.2.tar.gz` now also works via the generic URL.

**Comment by JensTimmerman** [comment]
ok, the comment doesn't make that clear thought.

**Comment by boegel** [comment]
OK, I'll change the comment to something like `# all tarballs except espresso*tar.gz`

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/81a9900bacb918b0e80a for a full test report.

**Comment by boegel** [comment]
Test report shows that redownloading sources still works.

Thanks for the review @JensTimmerman!

**Pull request merged**
