### PR TITLE
{vis}[foss/2016a] libGLU 9.0.0 (WIP)

### PR DESCRIPTION
**Pull request by jrbosch**
This easyconfig file needs mesa 11.1.2 before.
needs PR #2758 by @hajgato

### CODE REVIEW

**Comment by hajgato** [comment]
@jrbosch check PR #2760

**Comment by boegel** [comment]
Jenkins: ok to test

@hajgato libGLU easyconfig in here is identical to the one in #2760, so nothing to worry about

I'll merge both #2760 and this one once #2758 is merged.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0a2b9fdb3fe266d618820b8608592c1b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2604.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7835c0e4087b740ed286b7d333d2d5aa for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jrbosch!

**Pull request merged**
