### PR TITLE
include Tcl and Tk as dependencies in R easyconfig (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
see http://r.789695.n4.nabble.com/Where-is-the-tcltk-package-td3434915.html

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a50436703af28d381e6c for a full test report.

**Comment by boegel** [comment]
@wpoely86 or @pescobar: please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3aa9c88df42e9b96b185 for a full test report.

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
OK, going in, thanks @wpoely86!

**Pull request merged**
