### PR TITLE
Added checksums to GCC easyconfigs

### PR DESCRIPTION
**Pull request by geimer**
Also includes some minor tweaks to for consistency (mostly to improve 'diffability' of easyconfigs)

### CODE REVIEW

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 37 out of 37 (38 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/24af3631d131353b314c for a full test report.

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 38 out of 38 (38 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/53f7d3a7aa77f703fed8 for a full test report.

**Comment by geimer** [comment]
Now with the installed GCC included ;-)

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by geimer** [comment]
Well, checksum verification actually takes place immediately before extracting the source archive. Thus, the tests above didn't verify the checksums. Trying again with `--stop=source`...

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 38 out of 38 (38 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/97793b675028f13637b2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 38 out of 38 (38 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/672968447159f7c876d0 for a full test report.

**Comment by boegel** [comment]
Looking excellent, thanks a lot for looking into this @geimer!

**Pull request merged**
