### PR TITLE
{bio} [foss-2016a] Rosetta-2016.13.58602-foss-2016a

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)
Rosetta 2016.13.58602

### CODE REVIEW

**Comment by verdurin** [comment]
Depends on #2984

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2578.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2b756eb82ad69d09c15f5df5d56bde60 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/18fc2f5c40f12ad75b5bc8c09b7404b1 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
