### PR TITLE
New EasyConfigs for libspatialite - various versions and toolchains

### PR DESCRIPTION
**Pull request by valtandor**
Required as part of the GRASS 7.0.2 dependency tree. Dependencies are included. If problems arise with the dependencies please review their dedicated branches.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@valtandor: needs sync with `develop` as soon as #2422, #2428 are merged

**Comment by boegel** [comment]
@valtandor: missing patch?

**Comment by boegel** [comment]
```
AssertionError: Patch file /data/jenkins/workspace/easybuild-easyconfigs-pr-builder@4/easybuild/easyconfigs/l/libspatialite/libspatialite-configure.ac.patch is available for libspatialite-4.1.1-goolf-1.5.14.eb
```

**Comment by valtandor** [comment]
@boegel, the patch file should now be there.

**Comment by boegel** [comment]
@valtandor: whole mix of toolchains here + missing deps...

I don't think we have PRs around that are going to fix all of those?

```
Irresolvable dependencies encountered:
GEOS/3.3.5-goolf-1.5.14,
GEOS/3.3.9-intel-2015a,
SQLite/3.8.4.3-goolf-1.5.14,
SQLite/3.8.9-intel-2015a,
PROJ/4.8.0-goolf-1.5.14,
PROJ/4.9.1-intel-2015a
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/67426af25eeeda417a3b for a full test report.

**Comment by boegel** [comment]
@valtandor: some minor style fixes in https://github.com/valtandor/easybuild-easyconfigs/pull/10

**Comment by boegel** [comment]
@valtandar: this is awaiting https://github.com/valtandor/easybuild-easyconfigs/issues/10 ...

**Comment by boegel** [comment]
@valtandor ping on merging in https://github.com/valtandor/easybuild-easyconfigs/pull/10?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/702db446080e12658e03 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
