### PR TITLE
First complete fileset for an pomkl, using openmpi 1.10.4 and mkl

### PR DESCRIPTION
**Pull request by jhein32**
Both included HPL give good performance on our local cluster

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2028.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8a2b7ce55c9a0a8f4b14a7ef9c57a221 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2418.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/afd4d66dba15b3433cbf201431c53a23 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @jhein32!

**Comment by jhein32** [comment]
Thanks

J.

Sent from my nanoPad

On 02 Sep 2016, at 20:43, Kenneth Hoste <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #3516<https://github.com/hpcugent/easybuild-easyconfigs/pull/3516>.

-

**Comment by boegel** [comment]
Thank you @jhein32!

**Pull request merged**
