### PR TITLE
The NASM (Netwide Assembler) with no toolchain

### PR DESCRIPTION
**Pull request by valtandor**

### CODE REVIEW

**Comment by boegel** [comment]
Just wondering: do you have a particular use case for this (i.e. using `dummy` toolchain)?

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2463.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b17aaf9b6595c7542025d34248fd7b62 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2137.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/74f6338fc34a63f405c6bd5e3016ea17 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Comment by valtandor** [comment]
@boegel: Regarding the use case, this EasyConfig was supplied by a colleague of mine. I imagine his rationale was that NASM didn't have to be built against a particular toolchain, since it is an assembler (and should therefore generate more or less the same code regardless of what compiler was used to build it).

**Comment by boegel** [comment]
@valtandor OK, thanks for clarifying.

**Pull request merged**
