### PR TITLE
A new easyconfig for Python-3.5.1-foss-2015a

### PR DESCRIPTION
**Pull request by valtandor**

### CODE REVIEW

**Comment by valtandor** [comment]
I don't know if the Python 2.7.11 easyconfig should be updated, but for reasons at this end I wished for the same versions of packages in 3.5.1 as in 2.7.11.

**Comment by boegel** [comment]
@valtandor we refrain from updating extension versions in existing easyconfig files...

In addition, it's weird to have an easyconfig for Python 3.5.1 using an older toolchain that includes newer versions for the extensions, compared to existing easyconfigs for Python 3.5.1.

If you need updates to the included extensions, I suggest you: look into separate easyconfigs for the updated versions, or maybe a bundle of Python packages on top of the Python module that updates all extension versions.

**Comment by valtandor** [comment]
@boegel: OK, I've reverted the versions in the 2.7.11 EasyConfig. As for the 3.5.1 EasyConfig, I'm happy to choose appropriate earlier versions of things. In general, we've kind of been stuck on earlier versions of toolchains at our site (though we plan to upgrade in the next month or so).

**Comment by boegel** [comment]
@valtandor I think it makes sense to copy over the existing easyconfig we have for Python 3.5.1 (https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/p/Python/Python-3.5.1-foss-2016a.eb), and only tweak the toolchain version to `2015a`.

Sticking to the `ncurses` and `SQLite` versions you have in here is probably wise (and is fine by me).

Also, adding more extensions (you have `pytz`, `bitstring` and `virtualenv` extra in here) is fine by me. I would make sense to also include those extra extensions in the existing easyconfig for Python 3.5.1 too, to keep them in sync extension-wise. Just try to add extra extensions at the end (after the last one we have, i.e. `pandas`).

Please also copy over the existing `Python-2.7.11-foss-2015a.eb` easyconfig from `master`, you still have a couple of non-required changes in there that I'd like to avoid.

**Comment by valtandor** [comment]
@boegel I hope this is better.

**Comment by boegel** [comment]
@valtandor let's try and avoid needless changes in existing easyconfigs, see https://github.com/valtandor/easybuild-easyconfigs/pull/15

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 23 out of 23 (2 easyconfigs in this PR)
node2120.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6160a6e1e38e3e371d04e9237aa48414 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 64 out of 64 (2 easyconfigs in this PR)
node2495.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f455142397cfa8e6d235ad3874719992 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
