### PR TITLE
{lang}[dummy] Oracle Java (REVIEW)

### PR DESCRIPTION
**Pull request by gjbex**
Added most recent Java version 1.8u33.

### CODE REVIEW

**Comment by wpoely86** [comment]
ok to test

**Comment by wpoely86** [comment]
looks fine, ready for merge IMHO

**Comment by boegel** [comment]
no test report?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/47681d36821264055741 for a full test report.

**Comment by wpoely86** [comment]
@boegel wish granted

**Comment by boegel** [comment]
Thanks @wpoely86!

Going in, thanks for the contribution @gjbex!

**Pull request merged**
