### PR TITLE
add --enable-gobject for cairo, flesh out sanity_check_paths

### PR DESCRIPTION
**Pull request by boegel**
synced with cairo easyconfig in #2086

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
(close/open to trigger Travis)

**Comment by boegel** [comment]
superseded by #2785, #2995

**Pull request closed without merging**
