### PR TITLE
{tools}[dummy/] ClusterShell v1.7.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
boegel.ugent.be - Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz, Python 2.7.10
See https://gist.github.com/0a1eae16db2ddd5b7da96c985f626560 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2466.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0bc0f55778400a375aedf03c53b7b102 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2075.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fe5f5ff3a2a811cbc282c831f2cecb95 for a full test report.

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

cc @thiell, @degremont ;)

**Comment by thiell** [comment]
Hehe. Thanks @boegel. Was there some kind of demand from users? ClusterShell is usually installed a system package and used by sysadmins. But I have nothing against having it also in EB 👍

**Comment by boegel** [comment]
@thiell This was not by user request, but because I have a need for it myself, since I was asked to also briefly cover ClusterShell in a presentation I'm giving end of this month.

And I'm starting to realise I can use it myself too. :+1:

**Pull request merged**
