### PR TITLE
{lang}[foss/2015a] Perl 5.22.0

### PR DESCRIPTION
**Pull request by valtandor**
New EasyConfigs for Perl 5.22.0 with the foss-2015a toolchain, namely single-threaded and multithreaded versions (either can be removed if not desired).

### CODE REVIEW

**Comment by boegel** [comment]
@valtandor 

```
ERROR: Irresolvable dependencies encountered: DB/6.0.30-foss-2015a, SQLite/3.8.9-foss-2015a
```

**Comment by valtandor** [comment]
@boegel These dependencies should now be present.

**Comment by boegel** [comment]
@valtandor One more missing:

```
EasyBuildError: 'Irresolvable dependencies encountered: libreadline/6.2-foss-2015a'
```

**Comment by boegel** [comment]
@valtandor More missing deps, these should be added via a separate PR, ideally...

```
EasyBuildError: 'Irresolvable dependencies encountered: gimkl/2017a, ncurses/6.0-gimkl-2017a, zlib/1.2.11-gimkl-2017a'
```

Also, patch file `Perl_SamTools_include.patch` is missing?

**Comment by valtandor** [comment]
@boegel I was afraid of that. Apologies for the inconvenience. I've removed the new (gimkl-2017a) files.

**Comment by valtandor** [comment]
@boegel Hopefully this should be good to go now.

**Comment by valtandor** [comment]
@boegel Could this be merged so that #3976 can build?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
node2056.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0fdd3ce0845941ea520a851402be4850 for a full test report.

**Comment by boegel** [comment]
@valtandor When testing this, I quickly ran into download issues for the Perl extensions, which are fixed with https://github.com/valtandor/easybuild-easyconfigs/pull/16 .

With that in place however, the compilation of `Convert-Binary-C` is still failing for me, does that work fine on your end?

```
== 2017-06-08 11:52:44,991 build_log.py:156 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " make -j 16 " exited with exitcode 2 and output:
"/user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/bin/perl" "/user/home/gent/vsc400/vsc40023/eb_phanpyscratch/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/lib/perl5/5.22.0/ExtUtils/xsubpp"  -typemap "/user/home/gent/vsc400/vsc40023/eb_phanpyscratch/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/lib/perl5/5.22.0/ExtUtils/typemap" -typemap "typemap"  C.xs > C.xsc && mv C.xsc C.c
Compiling [gcc -O2] ctlib/fileinfo.c
Compiling [gcc -O2] util/hash.c
Compiling [gcc -O2] util/list.c
Compiling [gcc -O2] util/memalloc.c
cp bin/ccconfig blib/script/ccconfig
Running Mkbootstrap for Convert::Binary::C ()
"/user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/ccconfig
cp lib/Convert/Binary/C.pm blib/lib/Convert/Binary/C.pm
cp lib/Convert/Binary/C/Cached.pm blib/lib/Convert/Binary/C/Cached.pm
"/user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/bin/perl" "-Iblib/arch" "-Iblib/lib" ctlib/arch.pl ctlib/arch.h
"/user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/bin/perl" "-Iblib/arch" "-Iblib/lib" bin/perltypes.PL examples/perltypes.pl
"/user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/bin/perl" "-Iblib/arch" "-Iblib/lib" bin/convert.PL examples/convert.pl
"/user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/bin/perl" "-Iblib/arch" "-Iblib/lib" bin/elf.PL examples/elf.pl
"/user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/sandybridge/software/Perl/5.22.0-foss-2015a/bin/perl" "-Iblib/arch" "-Iblib/lib" bin/memmap.PL examples/memmap.pl
mv: cannot stat ‘t_object.tmp’: No such file or directory
make: *** [util/list.o] Error 1
make: *** Waiting for unfinished jobs....
chmod 644 "C.bs"
mv: cannot stat ‘t_object.tmp’: No such file or directory
make: *** [ctlib/fileinfo.o] Error 1
mv: cannot stat ‘t_object.tmp’: No such file or directory
make: *** [util/hash.o] Error 1
 (at easybuild/tools/run.py:449 in parse_cmd_output)
```

**Comment by valtandor** [comment]
@boegel No, it broke, but I was able to fix it by putting in `maxparallel = 1` (pushed out in the PR).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/02d44dfe4086111f2dbf4d7743c4af16 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @valtandor!

**Pull request merged**
