### PR TITLE
{tools}[intel/2016b] imbalanced-learn 0.2.1 /w Python 2.7.12 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
just a `Python` version change

### CODE REVIEW

**Comment by wpoely86** [comment]
Why not bump it to 2017a?

**Comment by hajgato** [comment]
Because user wants to use with other stuff from `2016b`

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic66 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/da032c35a785bb825fd0b5c844b669b0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2138.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/737f5b41f56351bf79884fe6e8827693 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2451.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/043f3868bcb0099f07b9ac4b9e60cb0a for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
