### PR TITLE
Contribute Perl module Parallel-ForkManager

### PR DESCRIPTION
**Pull request by apanteli**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
@boegel: can you please retry? easyconfig looks OK and source file looks in place, atm.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3df35da3d751193989ed for a full test report.

**Comment by boegel** [comment]
Going in, thanks @apanteli, and @fgeorgatos for blowing of the dust on this one.

**Pull request merged**
