### PR TITLE
{math}[intel/2015b] DOLFIN 1.6.0 w/ Python 2.7.11 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
required ~~#2257~~, ~~#2258~~, ~~#2260~~, ~~#2269~~, ~~#2276~~, ~~#2277~~, ~~#2288~~, ~~#2296~~, ~~#2304~~, ~~#2305~~, ~~#2308~~, ~~#2309~~, ~~#2318~~, ~~#2319~~, ~~#2325~~,~~#2326~~, ~~#2327~~

requires ~~https://github.com/hpcugent/easybuild-easyblocks/pull/804~~ (DOLFIN) and ~~https://github.com/hpcugent/easybuild-easyblocks/pull/805~~ (Trilinos)

### CODE REVIEW

**Comment by boegel** [comment]
test

**Comment by boegel** [comment]
test

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c0d9299ca351b60b5e28 for a full test report.

**Comment by boegel** [comment]
Good to go now https://github.com/hpcugent/easybuild-easyblocks/issues/804 is merged.

Thanks for the review @wpoely86!

**Pull request merged**
