### PR TITLE
{devel}[intel/2015a] Qt 4.8.6 + deps (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.5, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9fab4a57013524fd89e6 for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review (analogue of 1#320)

**Comment by wpoely86** [comment]
same remarks as in #1320

**Comment by boegel** [comment]
going in, thanks for the review @wpoely86!

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/64b9586cc3312c1c7b58 for a full test report.

**Comment by boegel** [comment]
premature merge, but fine... thanks for testing @wpoely86!

**Pull request merged**
