### PR TITLE
add easyconfig files for ncdf/ncdf4 for R 2.15.3 + dep easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by rjeschmi** [comment]
This might be best to just delete, it is against an older version of R now...

**Comment by JensTimmerman** [comment]
it's working, so it's still nice to have it in the repo's, so someone can look at it and quickly adapt it for a more recent R version.

**Comment by JensTimmerman** [comment]
@boegel looks fine to me.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0b9dccf10d26a5153be3 for a full test report.

**Comment by JensTimmerman** [comment]
@boegel good to go?

**Comment by boegel** [comment]
I see no reason not to, thanks for the review/testing everyone!

**Pull request merged**
