### PR TITLE
add patch for installing paycheck as Py3 extension

### PR DESCRIPTION
**Pull request by boegel**
without the patch, installing paycheck with Py3 fails if `$LC_ALL` isn't set to `en_US.utf8`

### CODE REVIEW

**Comment by JensTimmerman** [comment]
ok

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f51a60c1b288cd842acc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ff676f0ad650dc92b629 for a full test report.

**Comment by boegel** [comment]
hah, same issue for `deap`...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/673760bdf069c19c6506 for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the review @JensTimmerman!

**Pull request merged**
