### PR TITLE
{lang} [goolf/1.7.20] Perl-5.22.2 (Review) 

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar I know it's a major PITA, but... no updates for the extensions?

**Comment by pescobar** [comment]
@boegel I got the extensions list from `Perl-5.22.1-foss-2016a.eb` . isn't it up to date enough?

**Comment by boegel** [comment]
@pescobar Well, it's over 2 months old...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/36186c4f3619a0e5238cc31552455dbf for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pescobar!

**Pull request merged**
