### PR TITLE
rename ffmpeg to FFmpeg

### PR DESCRIPTION
**Pull request by boegel**
as discussed on EasyBuild mailing list, (partially) fleshed out from #2425 

cc @valtandor

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Thanks @wpoely86!

**Comment by boegel** [comment]
The `sources` line should have been adjusted accordingly, but this is fixed by @valtandor in #2425.

**Pull request merged**
