### PR TITLE
{bio} [intel-2015a] beagle-lib-20141202 r1261 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
`Autoconf/2.69-intel-2015a` is missing? available somewhere else?

**Comment by hajgato** [comment]
@boegel Opps. forget to mention. It is in the monster https://github.com/hpcugent/easybuild-easyconfigs/pull/1439 Should I insert autoconf & deps here as well?

**Comment by boegel** [comment]
@hajgato: yes, please flesh them out to here, so we can make #1439 a bit lighter

**Comment by hajgato** [comment]
@boegel Done. (plus 2 extra eb configfiles)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e73f0329695ae39655aa for a full test report.

**Comment by boegel** [comment]
Looks great, going in, thanks @hajgato!

**Pull request merged**
