### PR TITLE
{bio,devel}[intel/2017a] bx-python v0.7.4, LZO v2.10

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2663.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bfae8eaa403b0e5de83137eab816ed6a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2141.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/726c7708093aec0c9f32a14383d00f9f for a full test report.

**Comment by boegel** [comment]
@verdurin please review?

**Comment by JensTimmerman** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @JensTimmerman!

**Pull request merged**
