### PR TITLE
Initial version of R bump to 3.2.2 for goolf 1.7.20

### PR DESCRIPTION
**Pull request by verdurin**
This is to facilitate the update of Bioconductor to the 3.2 release, which is being tracked in #1962

### CODE REVIEW

**Comment by wpoely86** [comment]
ok to test

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/75d55c26b5c45f7a9d21 for a full test report.

**Comment by boegel** [comment]
@verdurin: shall we update this one with GDAL/rgdal while we're at it w/ #2364, or shall we just drop it?

**Comment by verdurin** [comment]
@boegel - I'd say drop it and concentrate on #2364

**Comment by boegel** [comment]
@verdurin: ok, let's close this then? (I prefer not closing issues/PRs opened by others)

**Pull request closed without merging**
