### PR TITLE
{data}[intel/2015b] ROOT v5.34.34 + libxml2 2.9.3 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0459a6b1402638d6efc4 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e6447d213a062df1de97 for a full test report.

**Comment by rjeschmi** [comment]
This looks fine.

Is python a runtime dep as well as a build dep? I wonder whether we need to carry the python version in the name if it is just a build-dep (ie it will build with whatever python happens to be available in that toolchain).

**Comment by boegel** [comment]
@rjeschmi: it's a runtime dep (ROOT provides some Python scripts too, which may require Python pkgs not part of the stdlib, etc), otherwise it would be listed via `builddependencies`

**Comment by boegel** [comment]
Thanks for the review @rjeschmi!

**Pull request merged**
