### PR TITLE
{lib,tools}[intel/2016a] pip v8.0.2, testpath v0.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires https://github.com/hpcugent/easybuild-easyblocks/pull/719

### CODE REVIEW

**Comment by boegel** [comment]
cc @pescobar

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a3346de16717903b4bed for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Comment by boegel** [comment]
@pescobar: can you pick this up for your IPython PR (#2457)?

**Pull request merged**
