### PR TITLE
Update to NWChem 6.5

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2f792257a8d71d4b6336 for a full test report.

**Comment by boegel** [comment]
@hajgato: do you think something still needs to be changed here? Looks good to me...

**Comment by hajgato** [comment]
@boegel: The users did not complain, so I think it is fine (the speed as well)

**Comment by boegel** [comment]
OK, going in, thanks @hajgato!

**Pull request merged**
