### PR TITLE
Libxml2 "toolchainopts = {'pic': True}" added 

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
is this a fix for the issue in #1080?

**Comment by hajgato** [comment]
@boegel No. This was fleshed out from the closed PR #1166

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 40 out of 40 (40 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/76c7a61091fe304968a5 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
