### PR TITLE
add patch for OpenMPI 1.7.x and 1.8.x to fix memalign issue (WIP)

### PR DESCRIPTION
**Pull request by boegel**
fixed version of #1785 for OpenMPI 1.7.x and 1.8.x, cfr. #1797 

@besserox: please review?

### CODE REVIEW

**Comment by boegel** [comment]
Hmm, hold on, the Rmpi segfault is still occurring on top of OpenMPI built with this patch... :(

**Comment by fgeorgatos** [comment]
visual review OK; what a spectacular bug was that... it flied in the face of all rpath'ers :)

**Comment by besserox** [comment]
Sorry, I was busy in the last 2 days.

I'm a bit lost now. What is the status of this? 
Is there still a segfault of Rmpi with this patch?

**Comment by boegel** [comment]
@besserox sorry for not getting back... yes, Rmpi still segfaults with this (last time I checked)

**Comment by besserox** [comment]
@boegel If Rmpi crashes with this, that kind of a problem :-( 
Unfortunately I don't have time to look into this.

Regarding this patch itself, it improves the performance code with OpenMPI, but it's still bad compared to other MPIs. So, this patch is no so urgent for me.

That's why I also prefer to focus on other toolchains like ictce/intel or gmvoolf for now.

**Comment by boegel** [comment]
In that case, I suggest we just close this (and any related issues/PRs)...

There's little point in spending time on this if it only slightly helps with the performance of *old* OpenMPI versions.

**Comment by besserox** [comment]
@boegel Yes, this can be closed for now. 

I will check (someday) what is the status with the recent version of OpenMPI.

**Pull request closed without merging**
