### PR TITLE
add CPPFLAGS='-fgnu89-inline' to configopts for M4 v1.4.17 w/ GCCcore/4.9.3

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

Fix for this in #529

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6c16a2116650b4326c56 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2636.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5f90390b6ff39297272b for a full test report.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
This looks OK, and it doesn't seem to break anything, but it would be nice to at least figure out *why* this works (so we can add a comment in the easyconfig to explain why it's required).

@wpoely86 Can you take a quick look?

**Comment by wpoely86** [comment]
It's a bit weird that this still is needed but looks harmless to me.

**Comment by boegel** [comment]
@wpoely86 It fixes the build on CentOS5, see also https://bugs.gentoo.org/show_bug.cgi?id=289757

**Comment by boegel** [comment]
```
The option -fgnu89-inline tells GCC to use the traditional GNU semantics for "inline" functions
when in C99 mode.
This option is accepted and ignored by GCC versions 4.1.3 up to but not including 4.3.
In GCC versions 4.3 and later it changes the behavior of GCC in C99 mode.
Using this option is roughly equivalent to adding the "gnu_inline" function attribute to all inline functions.
```

This doesn't help me a lot in explaining why it fixes the problem, but it does suggest it's harmless to include it.

I'll merge this and #2779 after testing, and then apply this change to all the M4 easyconfigs...

**Comment by boegel** [comment]
Going in, thanks @SimonPinches!

PR to sync up all M4 1.4.17 easyconfigs is at #2816

**Pull request merged**
