### PR TITLE
Velvet: copy the contrib dirs into place so users can use the scripts

### PR DESCRIPTION
**Pull request by ehiggs**

### CODE REVIEW

**Comment by boegel** [comment]
@ehiggs: please do this for all Velvet 1.2.10 easyconfigs (keep things consistent)

**Comment by ehiggs** [comment]
Done.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/11d1789538a32d5636fd for a full test report.

**Comment by boegel** [comment]
Thanks @ehiggs!

**Pull request merged**
