### PR TITLE
{lib}[intel/2015a] pyhull 1.5.4 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: up for giving this a review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/dd0992e7e0c7c70cf383 for a full test report.

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
