### PR TITLE
{numlib}[gompi/2016.07] FFTW 3.3.5

### PR DESCRIPTION
**Pull request by AFCJamie**
A version bump for FFTW to 3.3.5 (otherwise it's the same as FFTW 3.3.4 with gompi 2016b).

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2647.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bce18264c61be6e0b8c8026f6a4b75c9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2112.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f2dd75943f3f24878ec84676f5c75516 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @AFCJamie!

**Comment by AFCJamie** [comment]
Thanks!

**Pull request merged**
