### PR TITLE
{chem}[intel/2015a] TINKER 7.1.2 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/578

### CODE REVIEW

**Comment by JensTimmerman** [comment]
ok

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/2fa5bdb7399853edd430 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8365a89b4665f233224e for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Going in, thanks for the review @wpoely86 and @JensTimmerman!

**Pull request merged**
