### PR TITLE
{bio}[intel/2016b] PyNAST v1.2.2, PyCogent v1.9

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
depends on ~~#3896~~ for UCLUST easyconfig

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2595.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/68c26e71e8b62f8dbeac79355bb6a03f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2130.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/364f357d33edef241fffb5f9bf5e9bba for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
node2595.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/90de01c24eead31eb121729e01b88b50 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
node2130.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1dc956bccd4fe6641f50495fbcc67a7e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2595.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2569be8fc6123cfef0f41c9250f58264 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2130.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f22785b8ca899c8eace3345abe49b1bc for a full test report.

**Comment by boegel** [comment]
@verdurin please review

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
login000.camp.thecrick.org - Linux centos linux 7.2.1511, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/c7efdf917cb352fe9979db9c4a41fafe for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
login000.camp.thecrick.org - Linux centos linux 7.2.1511, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/ac9e4792b30a5e74e8ed0fdd9936c608 for a full test report.

**Comment by verdurin** [comment]
Looks okay to me, and the test build worked.

**Comment by boegel** [comment]
Thanks for the review & test @verdurin!

**Pull request merged**
