### PR TITLE
{numlib}[intel/2015b] SLEPc v3.6.2, PETSc v3.6.3, SuiteSparse v4.4.6

### PR DESCRIPTION
**Pull request by boegel**
(created using --new-pr)
requires https://github.com/hpcugent/easybuild-easyblocks/pull/800

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c3f918ba78088767468f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in this PR)
Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ff6287f0321b79e716db for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
