### PR TITLE
Contributing picard version 1.109

### PR DESCRIPTION
**Pull request by tloizou**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by ocaisa** [comment]
style review ok

**Comment by ocaisa** [comment]
It's no longer possible to download the version of java listed in the eb. Can we change it to 1.7.0_80?

**Comment by boegel** [comment]
I'm fine with either Java version, let me know how you'll handle this @tloizou.

**Comment by tloizou** [comment]
@boegel: Let's keep the current version i.e. 1.7.0_10

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/d6eb99aa7d6d25c91076 for a full test report.

**Comment by rjeschmi** [comment]
The dep is consistent with other merged picards.

I'd just merge this as-is

**Comment by boegel** [comment]
Works fine, going in. Thanks @tloizou, and @ocaisa and @rjeschmi for review/feedback.

**Pull request merged**
