### PR TITLE
Add support for PyGTK with intel/2016a toolchain

### PR DESCRIPTION
**Pull request by ocaisa**
I solved this by following the recipes available for [homebrew](https://github.com/Homebrew/homebrew)

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by ocaisa** [comment]
Obviously there is an implicit dependency on X11 in here since it will write to the screen, for me the lack of a listed dep didn't trigger an error but it might on systems without the dev libs for X11 and friends.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 12 out of 20 (20 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1f2fb31c80189cbea077 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Hmm, somewhere the path to `python` is hard injected. I'm running into this when building GLib:

```
/usr/bin/env: /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.11-intel-2016a/bin/pyth: No such file or directory
```

**Comment by ocaisa** [comment]
Hmm, `GObject-Introspection` has an environment variable set as a pre-config opt `GI_SCANNER_DISABLE_CACHE=true` and I wonder if that should actually be exported as an env var? The error seems to suggest that it is relevant.

**Comment by ocaisa** [comment]
The shebangs are hard set in some scripts in the bin directory of GLib, are these truncated for you?

**Comment by boegel** [comment]
@ocaisa: issue remains when exporting `GI_SCANNER_DISABLE_CACHE`, so something else is going on

The full path to `python` is there:

```
$ grep '^#.*python$' bin/*
bin/gdbus-codegen:#!/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.11-intel-2016a/bin/python
bin/gtester-report:#!/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.11-intel-2016a/bin/python
```

but shebangs have a character limit, so the truncating happens at runtime (yes, urgh).

I'll throw in a post install cmd to change these to `/usr/bin/env python`

**Comment by boegel** [comment]
fixing the shebangs in `GLib` is not enough, I'm finding this in the GObject-Introspection build dir:

```
./g-ir-scanner:#!/usr/bin/env /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.11-intel-2016a/bin/python
./g-ir-annotation-tool:#!/usr/bin/env /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.11-intel-2016a/bin/python
```

That's just... stupid. :)

**Comment by ocaisa** [comment]
There's an environment variable `PYTHON` that you can use to override the value from the configure, just set that you `python`

**Comment by boegel** [comment]
@ocaisa: you mean `buildopts = "PYTHON=python"` ?

**Comment by ocaisa** [comment]
I think it should probably be a `preconfigopts`, from the output of `./configure --help`:
```
Some influential environment variables:
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  LIBS        libraries to pass to the linker, e.g. -l<library>
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>
  CPP         C preprocessor
  PKG_CONFIG  path to pkg-config utility
  PKG_CONFIG_PATH
              directories to add to pkg-config's search path
  PKG_CONFIG_LIBDIR
              path overriding pkg-config's built-in search path
  GLIB_CFLAGS C compiler flags for GLIB, overriding pkg-config
  GLIB_LIBS   linker flags for GLIB, overriding pkg-config
  GOBJECT_CFLAGS
              C compiler flags for GOBJECT, overriding pkg-config
  GOBJECT_LIBS
              linker flags for GOBJECT, overriding pkg-config
  GMODULE_CFLAGS
              C compiler flags for GMODULE, overriding pkg-config
  GMODULE_LIBS
              linker flags for GMODULE, overriding pkg-config
  GIO_CFLAGS  C compiler flags for GIO, overriding pkg-config
  GIO_LIBS    linker flags for GIO, overriding pkg-config
  GIO_UNIX_CFLAGS
              C compiler flags for GIO_UNIX, overriding pkg-config
  GIO_UNIX_LIBS
              linker flags for GIO_UNIX, overriding pkg-config
  CAIRO_CFLAGS
              C compiler flags for CAIRO, overriding pkg-config
  CAIRO_LIBS  linker flags for CAIRO, overriding pkg-config
  SCANNER_CFLAGS
              C compiler flags for SCANNER, overriding pkg-config
  SCANNER_LIBS
              linker flags for SCANNER, overriding pkg-config
  FFI_CFLAGS  C compiler flags for FFI, overriding pkg-config
  FFI_LIBS    linker flags for FFI, overriding pkg-config
  GIREPO_CFLAGS
              C compiler flags for GIREPO, overriding pkg-config
  GIREPO_LIBS linker flags for GIREPO, overriding pkg-config
  GTKDOC_DEPS_CFLAGS
              C compiler flags for GTKDOC_DEPS, overriding pkg-config
  GTKDOC_DEPS_LIBS
              linker flags for GTKDOC_DEPS, overriding pkg-config
  PYTHON      the Python interpreter

Use these variables to override the choices made by `configure' or to help
it to find libraries and programs with nonstandard names/locations.
```

**Comment by ocaisa** [comment]
Yeah looking at the configure script, setting it for the configure step should be enough

**Comment by boegel** [comment]
@ocaisa: please review/merge https://github.com/ocaisa/easybuild-easyconfigs/pull/17

**Comment by ocaisa** [comment]
The X11 dependencies are probably to be placed in `GTK+`, the configure output from there includes:
```
checking for XOpenDisplay... yes
checking for XextFindDisplay... yes
checking for XRenderQueryExtension... yes
checking if <X11/extensions/XIproto.h> is needed for xReply... no
checking for XConvertCase... yes
checking for XInternAtoms... yes
checking for XAddConnectionWatch... yes
checking for XkbQueryExtension... yes
checking for XShapeCombineMask... yes
checking for XSyncQueryExtension... yes
checking for X11/extensions/sync.h... yes
checking for XShmAttach... yes
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 20 out of 20 (20 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/56b1cbf5630c6134931a for a full test report.

**Comment by boegel** [comment]
@ocaisa: we already have easyconfigs for `GTK+`, but we used `gtk+` there... same for `Gdk-Pixbuf`, and `PyCairo`

Shall we fix that by renaming the easyconfigs we have already (which impacts the places where these are used as a dependency)?

**Comment by ocaisa** [comment]
@boegel Something was broken in your PR

**Comment by boegel** [comment]
@ocaisa: fixed with https://github.com/ocaisa/easybuild-easyconfigs/pull/19

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 19 out of 20 (20 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/239fffa63cd59b8d8e46 for a full test report.

**Comment by ocaisa** [comment]
@boegel Sanity check fail on GLib

On 10 Feb 2016 12:37, "Kenneth Hoste" <notifications@github.com<mailto:notifications@github.com>> wrote:

Test report by @boegel<https://github.com/boegel>
FAILED
Build succeeded for 19 out of 20 (20 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/239fffa63cd59b8d8e46 for a full test report.

—
Reply to this email directly or view it on GitHub<https://github.com/hpcugent/easybuild-easyconfigs/pull/2443#issuecomment-182326388>.


------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Dr. Karl Eugen Huthmacher
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,
Prof. Dr. Sebastian M. Schmidt
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

**Comment by boegel** [comment]
@ocaisa: fixed with https://github.com/ocaisa/easybuild-easyconfigs/pull/21

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 20 out of 20 (20 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0fd9e694287b8ba663c8 for a full test report.

**Comment by boegel** [comment]
OK, good to go now, thanks @ocaisa!

**Pull request merged**
