### PR TITLE
add postinstall command to fix permission issues in molmod easyconfig file

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1d0b5777a56cd945056b for a full test report.

**Comment by lvduyfhu** [comment]
Dit lijkt mij OK

**Comment by boegel** [comment]
@lvduyfhu We stick to English in these repos, but thanks for the review, I think it's easy enough to understand for non-Dutch speakers.

Going in!

**Comment by lvduyfhu** [comment]
@boegel  Indeed, it makes more sense to reply in English, sorry for that.

**Pull request merged**
