### PR TITLE
{chem}[intel/2015b] NWChem 6.5 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-easyblocks/pull/720

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/eb82b31b421724957f58 for a full test report.

**Comment by boegel** [comment]
da hell...

```
The directory name chosen for NWCHEM_TOP is longer than 
the maximum allowed value of 64 characters
      current NWCHEM_TOP/src=/local/100953[2069].master20.golett.gent.vsc/eb-a81QZF/tmpyQP8BM6.5.revision26243/src equal to 86 characters
please chose a directory with a shorter name
E.g., setenv NWCHEM_TOP /home/nwchem_user/nwchem
```

@hajgato: how come we never ran into this before?

**Comment by hajgato** [comment]
@boegel: maybe because your job names were more simple? `100953[2069].master20.golett.gent.vsc` seriously? Anyway, I have never got this error.

**Comment by boegel** [comment]
@hajgato: that's just because I was running the test in a PBS job, where `$TMPDIR` is set to `/local/$PBS_JOBID`.

I'm wondering if we can trick NWChem into using a 'long' path by creating a symlink in `/tmp` to the actual build directory, and defining `$NWCHEM_TOP` as `/tmp/<symlink>`...

**Comment by hajgato** [comment]
@boegel might be. I have never tried. And anyway, I find ridiculous a 64 character limit in 2015...

**Comment by boegel** [comment]
@hajgato: it was ridiculous 15 years ago ;)

**Comment by hajgato** [comment]
@boegel check this: http://www.nwchem-sw.org/index.php/Special:AWCforum/st/id1172/Error%3A_name_chosen_for_NWCHEM_TO....html

set NWCHEM_LONG_PATHS
If you recompile the util directory with the env. variable NWCHEM_LONG_PATHS set,
you might be able to bypass the 64 characters limit.
However, some parts of the code might fail.
You'd better run the full QA suite to test the installation

**Comment by boegel** [comment]
@hajgato: I like how they mention "having to choose between two evils" at https://svn.pnl.gov/svn/nwchem/trunk/src/util/util_nwchem_srcdir.F

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/75fe80083bcba2d80719 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/83caffac81213007a33d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/6b78882ef8bcb5fba5b6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/627ed2c9dfb2cd06d020 for a full test report.

**Comment by boegel** [comment]
New problem:

```
== 2015-10-21 11:56:38,429 main.run DEBUG cmd "./getmem.nwchem" exited with exitcode 1 and output:
/local/100956[2069].master20.golett.gent.vsc/eb-2BSA4O/tmp9KXjlf6.5.revision26243/src/input: No match.
```

Seems like NWChem is not a big fan of being built in a directory than contains characters like `[` and `]`...

I'll see if I can work around that in the NWChem easyblock too via https://github.com/hpcugent/easybuild-easyblocks/pull/720 while I'm at it...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e16c0ded06401fb3e0d9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/cb1ef98247a50711a681 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fb12c49b4fd177124c14 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/60012c674d299b6a28c5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8faf54629cb057605046 for a full test report.

**Comment by boegel** [comment]
Good to go with https://github.com/hpcugent/easybuild-easyblocks/pull/720 merged, thanks for the review @hajgato (was basically just a toolchain bump compared to existing easyconfigs), nothing special here really...

**Pull request merged**
