### PR TITLE
{lib}[intel/2016b] libconfig v1.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2023.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ce7800294c3d17a5c9e15f5d90cfa669 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2413.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8add56f281c354ea51bb9fac6cea78b7 for a full test report.

**Comment by boegel** [comment]
This is new, so: please review @verdurin (trivial imho)

**Comment by verdurin** [comment]
Looks good, and builds and loads fine locally.

**Comment by boegel** [comment]
Thanks for the review @verdurin!

**Pull request merged**
