### PR TITLE
Update of PSI4 to git version from June 30

### PR DESCRIPTION
**Pull request by tovrstra**
@SebWouters  @wpoely86
I've tested these on my HPC account. Everything compiles without error. (I did not test any further yet but that should be fine. It is a development version anyway.)

### CODE REVIEW

**Comment by wpoely86** [comment]
@tovrstra They tagged 1.0rc2 also yesterday?

**Comment by tovrstra** [comment]
Oops. What a coincidence. Good point. I guess that also implies that we have to use "PSI4" as package name in future instead of PSI?

**Comment by wpoely86** [comment]
yes, I tried to convince to keep using increasing version numbers but alas. We should from now on switch to using `PS4/1.0rc2`.

**Comment by tovrstra** [comment]
OK. I'll make a new PR.

**Comment by wpoely86** [comment]
@fgeorgatos The problem is that it's a nightmare to maintain. We currently have:
- PSI 4.0b1
- PSI4 1.0rc2

There is no sane way to do both with the same name. We should then change to version to something like `4.0-1.0rc` which might confuse users even more.

**Comment by tovrstra** [comment]
@fgeorgatos I don't agree with you and I'd like to make a PR in which the new name will be `psi4`: lower case and with the four. I am a downstream user, and this is the way I would like it to be and how I guess most users would prefer it as well. 

In the community, e.g. conferences I attend, this program is always called `Psi4`, sometimes also `PSI4` and everything on the command line seems to be `psi4`, not `PSI4`, nor `Psi4`. EasyBuild should follow that convention and this is a nice opportunity to fix it.

Most users seem to have happily forgotten that there was once a Psi3. The 4 has just become a part of the name. If you like, we can always ask one of the Psi4 developers if they ever intend to make a Psi5, but that seems unlikely.

**Comment by wpoely86** [comment]
@tovrstra I already asked them once: https://github.com/psi4/psi4/issues/213

**Comment by tovrstra** [comment]
@wpoely86 That thread is just hilarious. So there may be a Psi5 one day. It will not be called a new version but rather a new generation. I'm glad I'm warned.

**Comment by fgeorgatos** [comment]
I had a closer look and it is clear to me that @wpoely's argumentation is
strong:
* Not using PSI4 is problematic both due to ordering, as well as it is the
explicit naming by original developers
* The name is really PSI4 rather than Psi4 (per documentation). They simply
use small caps all over the place

On 4 July 2016 at 08:51, Toon Verstraelen <notifications@github.com> wrote:

> @wpoely86 <https://github.com/wpoely86> That thread is just hilarious. So
> there may be a Psi5 one day. It will not be called a new version but rather
> a new generation. I'm glad I'm warned.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hpcugent/easybuild-easyconfigs/pull/3281#issuecomment-230227273>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABdgQJUJ7xtkawkZ26nxqchPIl10sgo_ks5qSLtmgaJpZM4JC62a>
> .
>



-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Pull request closed without merging**
