### PR TITLE
Added missing libxml2 dependency

### PR DESCRIPTION
**Pull request by nathanhaigh**
This is in relation to fixing #2636.

Not sure which version to use, especially for the older ones, but stuck with `2.9.2` for simplicity.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
lgtm, going with libxml2 v2.9.2 makes sense since other GLib easyconfigs in the same version range have the same

**Comment by boegel** [comment]
@nathanhaigh welcome to dep hell:

```
Conflict found for dependencies of CGAL-4.7-intel-2015b-Python-2.7.11: libxml2-2.9.2-intel-2015b vs libxml2-2.9.3-intel-2015b-Python-2.7.11
Conflict found for dependencies of DOLFIN-1.6.0-intel-2015b-Python-2.7.11: libxml2-2.9.2-intel-2015b vs libxml2-2.9.3-intel-2015b-Python-2.7.11
Conflict found for dependencies of Qt5-5.5.1-intel-2015b-Mesa-11.0.8: libxml2-2.9.2-intel-2015b vs libxml2-2.9.3-intel-2015b-Python-2.7.11
```

**Comment by nathanhaigh** [comment]
@boegel Not something I can spend time on at the moment :(

**Comment by boegel** [comment]
merged via #2658, thanks @nathanhaigh!

**Pull request merged**
