### PR TITLE
{bio} [inte/2016b] BWA/0.7.15 (REVIEW)

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2460.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/41a4e20f31a570e91a7f8a66abce1f02 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2045.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8882f50ae7dd603bc72c4b2d7b4eb022 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
@wpoely86 psst, you should still open PRs to `develop`... good that GitHub now allows us to change the target branch :)

**Comment by boegel** [comment]
Going in, thanks @wpoely86!

**Pull request merged**
