### PR TITLE
{lang,tools}[intel/2016b] flex v2.6.2, help2man v1.47.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2089.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3fadcc697f06b25f6efdaa13f15b0d43 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2301.phanpy.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8accd495ea980d47368f02d0d37c6389 for a full test report.

**Comment by akesandgren** [comment]
Looks good to me. Although i would put build deps before runtime deps.

**Comment by boegel** [comment]
Thanks for the review @akesandgren and @rjeschmi!

@akesandgren w.r.t. the order of runtime vs build: we should enforce that consistently via automated style checks (which are WIP)...

**Pull request merged**
