### PR TITLE
add custom sanity_check_paths in libxml2 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
fleshed out from #507

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
looks good

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 15 out of 15 (15 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz, Python 2.7.3
See https://gist.github.com/9bf0157a5f30e44f79da for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 35 out of 35 (35 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ed394164ad8c933983e9 for a full test report.

**Comment by boegel** [comment]
OK, going in.

Thanks for testing/reviewing @geimer and @wpoely86!

**Pull request merged**
