### PR TITLE
AutoDock_Vina-1.1.2-linux_x86.eb

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**SUCCESS**
Build succeeded for 1 out of 1
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/79e0555eaa966e170abe for a full test report.

**Comment by JensTimmerman** [comment]
@boegel this is good to go

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/bc0b5ee7cb15c8da8551 for a full test report.

**Comment by boegel** [comment]
filename issue: `AutoDock_Vina-1.1.2-linux_x86.eb` vs `AutoDock_Vina-1.1.2_linux_x86.eb` (`-` vs `_`)

**Comment by boegel** [comment]
Going in, thanks @pescobar!

**Pull request merged**
