### PR TITLE
{tools}[dummy] EasyBuild v2.4.0 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz, Python 2.7.10
See https://gist.github.com/73b6903eab77562bcb93 for a full test report.

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/bf03dd7a838e2133022d for a full test report.

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Comment by wpoely86** [comment]
any reason why this isn't merged yet?

**Comment by boegel** [comment]
@wpoely86: me not clicking the button ;-)

I had some trouble with some of the Jenkins tests post the 2.4.0 release, so I wanted to get that resolved first.

**Pull request merged**
