### PR TITLE
x264 with foss2016a

### PR DESCRIPTION
**Pull request by RvDijk**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by RvDijk** [comment]
depends on #3022

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2567.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d1cc400ed646a233e174d3bea0a2dd3d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/ff8103c01e166ed38d92d379fc7682fe for a full test report.

**Comment by boegel** [comment]
Going in, thanks @RvDijk!

**Pull request merged**
