### PR TITLE
{math}[foss/2016b] GMP v6.1.2

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2605.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/13df19e8c078782b25dd7abc9fc88ecf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2086.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bafdaff38ce7951c908cee83425cd5ef for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Comment by marbud0** [comment]
Test report by @marbud0
**FAILED**
Build succeeded for 1 out of 31 (1 easyconfigs in total)
hp-1337-3 - Linux Ubuntu 22.10 (Kinetic Kudu), x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.11.0b3
See https://gist.github.com/17b4db86f5ae9a03a3f92ca9f6134711 for a full test report.

**Pull request merged**
