### PR TITLE
{lang}[foss/2016a] R v3.2.3 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 11 out of 13 (13 easyconfigs in this PR)
node2074.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0ecaea42c2380cf54427 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in this PR)
node2715.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e2445d5d2b622828e06a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in this PR)
node2074.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/5a6d1f6df311d56cbd39 for a full test report.

**Comment by boegel** [comment]
just a toolchain bump, going in

**Comment by verdurin** [comment]
Do I need something else to test this, in order to then test #2697 ?:

```
eb --from-pr=2693  -dr
== temporary log file in case of crash /tmp/eb-zb7JpJ/easybuild-gAQDY2.log
== resolving dependencies ...
ERROR: Irresolvable dependencies encountered: CMake/3.4.3-foss-2016a
```

**Comment by boegel** [comment]
@verdurin: the one you're missing is in https://github.com/hpcugent/easybuild-easyconfigs/pull/2355

**Comment by verdurin** [comment]
@boegel - thanks. Got past this by updating my `develop` branch clone.

**Pull request merged**
