### PR TITLE
Clean up style in easyconfigs

### PR DESCRIPTION
**Pull request by wpoely86**
This is a huge cleanup of the style on all easyconfigs. It's done using pep8 with a 120 chars on a line.

### CODE REVIEW

**Comment by wpoely86** [comment]
On request of @boegel this PR will only deal with trailing spaces. I generated it by:
```
find -name '*.eb' -print0 | xargs -0 autopep8 --select=W291 --max-line-length=200 -i  -v
```

@boegel @rjeschmi @JensTimmerman please scroll through it?

**Comment by JensTimmerman** [comment]
looking good to me

**Comment by rjeschmi** [comment]
cleanup is good if we are going to start being stricter (make it easier to make it automated)

**Comment by rjeschmi** [comment]
I read through it quickly and it looks fine (only spaces)

**Comment by wpoely86** [comment]
@rjeschmi yeah the idea is to be stricter. But we first need to make sure that the current develop can pass the style tests of Jenkins :wink:

**Comment by boegel** [comment]
Going in, thanks @wpoely86!

**Pull request merged**
