### PR TITLE
{math}[intel/2015b] scipy 0.16.1 (WIP)

### PR DESCRIPTION
**Pull request by boegel**
requires #2179

### CODE REVIEW

**Comment by boegel** [comment]
WIP because scipy tests fail, see https://github.com/scipy/scipy/issues/5575

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/997bffce2f9749ed5b06 for a full test report.

**Comment by boegel** [comment]
@gppezzi: you mentioned that this does work for you? Which toolchain are you using?

**Comment by gppezzi** [comment]
CrayGNU (on dora), here's the [eb file](https://github.com/eth-cscs/tools/blob/256e6a0b56a558c9657962384b24c99e5bdbf385/easybuild/easyconfigs/p/Python/Python-3.5.0-CrayGNU-5.2.82.eb)

**Comment by boegel** [comment]
already merged via #2284 (on top of numpy 1.10.4)

**Pull request closed without merging**
