### PR TITLE
{perf}[*] Updated PDT easyconfigs using custom easyblock (REVIEW)

### PR DESCRIPTION
**Pull request by geimer**
**ATTENTION**: This PR requires https://github.com/hpcugent/easybuild-easyblocks/pull/624

Changes:
 - removed config parameter hackery now taken care of by custom easyblock
 - add checksums
 - cosmetic changes

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by geimer** [comment]
Test report by @geimer
**FAILED**
Build succeeded for 0 out of 10 (3 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/fb386f69a29c4c60bac3 for a full test report.

**Comment by geimer** [comment]
Test report by @geimer
**FAILED**
Build succeeded for 2 out of 10 (3 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/64c8062f4ce302fe8624 for a full test report.

**Comment by geimer** [comment]
Tested on top of https://github.com/hpcugent/easybuild-easyblocks/pull/624
Remaining test fails since I don't have ictce/5.3.0 available.

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/97200b09be8681ff3619 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/bdec5812ade2f396f1ee for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Good to go now https://github.com/hpcugent/easybuild-easyblocks/issues/624 is in, thanks @geimer!

**Pull request merged**
