### PR TITLE
{math}[binary] MATLAB 2017a (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
needs https://github.com/hpcugent/easybuild-easyblocks/pull/1182

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato or @wpoely86 Any chance for a test report for this?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
nic66 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1eb591a97649cdb0d527a27c4a960908 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
nic66 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/328f0c01d9630d61aff35b950a9ed441 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic66 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/170fa9674b5e3861a0b35ed21b4f0be3 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
