### PR TITLE
{bio}[intel/2016a] HISAT2 v2.0.3-beta

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

depends on ~~#2803~~, ~~#2808~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2717.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0eaeda36656be3f871dae893138336db for a full test report.

**Comment by boegel** [comment]
@rjeschmi please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2140.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/774b86d294c072396ba47642c527963b for a full test report.

**Comment by rjeschmi** [comment]
looks good.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Thanks for the review @rjeschmi!

**Pull request merged**
