### PR TITLE
Added PLINK-1.9b_4.1-x86_64.eb

### PR DESCRIPTION
**Pull request by danielnavarrogomez**

### CODE REVIEW

**Comment by danielnavarrogomez** [comment]
I just did a new commit fixing the issue.

**Comment by boegel** [comment]
@danielnavarrogomez please target the `develop` branch for contributions, the only time we merge into `master` is when a new EasyBuild release is done

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2151.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/30fc2947d96199b40402b013d8ae2d03 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2523.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/26c84ac91cfce76a4b71230859344216 for a full test report.

**Comment by boegel** [comment]
lgtm (I changed the target branch to `develop` myself)

**Comment by boegel** [comment]
Going in, thanks @danielnavarrogomez!

**Comment by danielnavarrogomez** [comment]
Sorry that I targeted the wrong branch... my mistake!

**Pull request merged**
