### PR TITLE
{compiler,mpi,system,toolchain}[GCC/5.2.0] GCC v5.2.0, OpenMPI v2.0.0, gompi v2016.12, ...

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@shahzebsiddiqui other than `gompi/2016.12` (which should have a different version imho, as discussed in https://github.com/hpcugent/easybuild-easyconfigs/pull/3915#issuecomment-265751931), there are several site-specific tweaks included in here, in particular the changes in dependencies and the extended configure options for OpenMPI...

**Comment by shahzebsiddiqui** [comment]
Is version gompi/2016.02 ok to use, i am using GCC-5.2.0 and OpenMPI-2.0.0 the closest version to my GCC is in gompi-2016.04 and after that the gcc goes to 5.4 and 6.1, 6.2.

**Comment by boegel** [comment]
@shahzebsiddiqui OpenMPI 2.0.0 was released June 2016, so 2016.02 (suggesting Feb'16) doesn't make sense to me

The issue is that (compared to `gompi/2016.09`) that you're using a relatively old GCC (5.2 was released July 2015) with a very recent OpenMPI, which messes things up a bit w.r.t. toolchain versioning...

**Comment by shahzebsiddiqui** [comment]
I guess, I don't have time now to change this to comply with EB standard. I
just needed to use the latest version of OpenMPI to build on top of
GCC-5.2.0. The reason being, I don't want to use EB provided files because
I have to customize them to remove other easybuild dependencies. I need
them to be osdependency for the most part, plus I have to configure OpenMPI
to be tuned with many more settings.

I would like to push my work and maybe someone can take a look. Most of
these builds should work for RHEL7. I have tested it with both easybuild
2.9.0 and easybuild 3.0.0. So I think it will work.

What do you suggest I can do.

**Comment by boegel** [comment]
@shahzebsiddiqui rather than using a custom toolchain, I would suggest that you apply the required site-specific changes to an existing toolchain, e.g. `foss-2016b`, and then contribute back easyconfigs using that toolchain (while keeping the site-specific modifications locally).

We have a couple of things in mind to make it easier to maintain site-specific changes locally, but they have not been implemented yet up until now.

**Comment by shahzebsiddiqui** [comment]
Hi Ken,

I have an entire software stack that is built with GCC, foss, or gompi
toolchain and I want to figure out a way to contribute this back. Before I
reconfigured foss-2016b and changed to foss-2016c. Then when I tried to
push my changes, all my easyconfig files were named with
<pkg>-<ver>-foss-2016c.eb There was some confusion with version so I tried
to change it to foss-2016.12.eb and that didn't work so I looked at
https://github.com/hpcugent/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/f/foss
to see which version I can use then I tried to do foss-2016.02.eb and that
didn't make sense with OpenMPI 2.0.0. If you want for sake of naming scheme
we can change the version of OpenMPI to make this work, while I still use
latest version at the site.

There is no foss toolchain with gcc-5.2.0 so I think we should have one
since EB supports 5.2.0

Is it possible if we can discuss this in a meeting, it will be more
effective that way and develop a strategy to push these changes

**Pull request closed without merging**
