### PR TITLE
[foss/2016b] Boost 1.63.0

### PR DESCRIPTION
**Pull request by dolfim**
Note: SOURCEFORGE_SOURCE returned a wrong tarball with missing files

### CODE REVIEW

**Comment by dolfim** [comment]
For me the build fails and I had to patch the easyblock, see hpcugent/easybuild-easyblocks#1080.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2301.phanpy.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/90a1b4ae6c7e8082e13e938dc0a7dc4b for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2052.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0977599daf8d0e40a3fbf4fa47c47f48 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @dolfim!

**Pull request merged**
