### PR TITLE
{math}[intel/2017a] molmod 1.1 w/ Python 2.7.13

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0ba5d3cd24d053e9db2f879e4435c664 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node843.raichu.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2c4fca9a75bf209f4e9a41c59f95d793 for a full test report.

**Comment by boegel** [comment]
@tovrstra please review?

**Comment by tovrstra** [comment]
This should work. Just to be sure, I've quickly tested that np.det returns the right result when suppressing the error:

    vsc-----@gligar02 (delcatty) ~> module load Python/2.7.13-intel-2017a
    vsc-----@gligar02 (delcatty) ~> python
    Python 2.7.13 (default, Apr  6 2017, 07:59:29) 
    [GCC Intel(R) C++ gcc 6.3 mode] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import numpy as np
    >>> np.linalg.det(np.zeros((3, 3), float))
    /apps/gent/CO7/sandybridge/software/Python/2.7.13-intel-2017a/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/linalg/linalg.py:1821: RuntimeWarning: invalid value encountered in det
      r = _umath_linalg.det(a, signature=signature)
    0.0
    >>> with np.errstate(invalid='ignore'): np.linalg.det(np.zeros((3, 3), float))
    ... 
    0.0
    >>> 

That looks good, so no comments.

**Comment by boegel** [comment]
Thanks for the review @tovrstra!

**Pull request merged**
