### PR TITLE
Beast fix

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
Test report by @fgeorgatos
**SUCCESS**
Build succeeded for 2 out of 2
Linux debian 6.0.10, Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz, Python 2.6.6
See https://gist.github.com/c9197e41f3508d550a16 for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 0 out of 1 (2 easyconfigs in this PR)
login18.cluster.bc2.ch - Linux centos 6.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.6.6
See https://gist.github.com/20bfa3b9b60a4e7f7a006f01702355fb for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 0 out of 3 (2 easyconfigs in this PR)
login18.cluster.bc2.ch - Linux centos 6.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.6.6
See https://gist.github.com/adb69b62ea0afd4b58ec4de9bcd463b6 for a full test report.

**Comment by boegel** [comment]
@pescobar test installations failed?

**Comment by pescobar** [comment]
closing. 

See https://github.com/hpcugent/easybuild-easyconfigs/pull/3143 https://github.com/hpcugent/easybuild-easyconfigs/pull/3144

**Pull request closed without merging**
