### PR TITLE
{cae}[*/2015b] OpenFOAM 2.3.1 + deps

### PR DESCRIPTION
**Pull request by boegel**
depends on #1724 and #1725 for `libreadline` + `ncurses` easyconfigs

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/820473f2a9cd1faaea82 for a full test report.

**Comment by boegel** [comment]
Unpacking of the OpenFOAM tarball failed on RHEL6 @hpcleuven with:

```
tar: OpenFOAM-2.3.1/tutorials/mesh/foamyHexMesh/mixerVessel/system/backgroundMeshDecomposition: Cannot create symlink to `.': Invalid argument
tar: OpenFOAM-2.3.1/tutorials/mesh/foamyHexMesh/mixerVessel/system/cellShapeControlMesh: Cannot create symlink to `.': Invalid argument
tar: Exiting with failure status due to previous errors
```

@gjbex: have you ever seen a problem like this?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/172ca81a5fed6ad43334 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/fc5f6bd371e1eb4547db for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c6fafbaa0e2f1f44b96c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f2ee9786f985294d5db4 for a full test report.

**Comment by boegel** [comment]
Seems like the unpack issue is a known problem, that has been fixed in OpenFOAM 2.4.0, see http://www.openfoam.org/mantisbt/view.php?id=1191 and https://github.com/OpenFOAM/OpenFOAM-2.3.x/commit/f7a485069c778495cc39b308580289f6c2d47163 .

I wonder if we can dance around it here by excluding those files when unpacking, and whether that would cause any problems with the build...

**Comment by boegel** [comment]
Failed test report on CentOS7 caused by use of old OpenFOAM easyblock, i.e. without having https://github.com/hpcugent/easybuild-easyblocks/pull/670 included.

Will fix and issue new test report.

**Comment by boegel** [comment]
@wpoely86: please rereview?

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/65fbbffca6237b355714 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/38e5e5c50e1913b20887 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7a15eb82367df8771f1e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3bc4d7523de05ab720cd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/979362452615e399e988 for a full test report.

**Comment by boegel** [comment]
build of OpenFOAM easyconfig using `foss/2015b` failed in last test report because old OpenFOAM easyblock was used, will resubmit new test report using updated easyblock

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux red hat enterprise linux computenode 6.5, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.6.6
See https://gist.github.com/3e67ee0015d64f7a8cd8 for a full test report.

**Comment by boegel** [comment]
All is well, going in, thanks for the review @wpoely86!

**Pull request merged**
