### PR TITLE
sync foss/2016a easyconfigs for X stack with their intel/2016a equivalents

### PR DESCRIPTION
**Pull request by boegel**
follow-up of ~~#3222~~

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 please review? ;)

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 40 out of 40 (40 easyconfigs in this PR)
node2470.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/affec202283dd72894e38c301374e4ab for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 40 out of 40 (40 easyconfigs in this PR)
node2004.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/e79a6be4a6b98d6c0781b90ce00758b1 for a full test report.

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
