### PR TITLE
{perf}[goolf-1.5.14] Score-P (REVIEW)

### PR DESCRIPTION
**Pull request by geimer**
As discussed with @boegel, this PR provides an update of https://github.com/hpcugent/easybuild-easyconfigs/pull/1026. Still needs testing, though.

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by geimer** [comment]
Test report by @geimer
**FAILED**
Build succeeded for 7 out of 11 (8 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/fb65c647e64be54b3c7f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/8911913d2da2403b113d for a full test report.

**Comment by boegel** [comment]
@geimer: from the log you sent me:

```
test.gresource.xml: Error on line 6 char 1: Error processing input file with xmllint:
/usr/bin/xmllint: symbol lookup error: /home/geimer/Projects/EasyBuild/_inst/software/MPI/GCC/4.8.2/OpenMPI/1.6.5/libreadline/6.2/lib/libreadline.so.6: undefined symbol: UP
```

**Comment by boegel** [comment]
so, GLib depends on xmllint?

**Comment by geimer** [comment]
No idea... Interestingly, I just tried to continue the GLib build manually with only the `goolf` toolchain module loaded. And it finished. Maybe a parallel build issue?

**Comment by geimer** [comment]
Wait... I have to load libffi, gettext, and Python too. The it fails in the same way. So yes, apparently it needs xmllint (or uses it if available). And since on my system it's picking up /usr/bin/xmllint - which doesn't work with libreadline.so found in `LD_LIBRARY_PATH` - it barfs...

**Comment by boegel** [comment]
@geimer: from https://developer.gnome.org/gio/stable/glib-compile-resources.html

```
XMLLINT
The full path to the xmllint executable. This is used to preprocess resources with the xml-stripblanks preprocessing option. If this environment variable is not set, xmllint is searched in the PATH.
```

**Comment by geimer** [comment]
So we need a (build?)dependency on libxml2, I guess. If so, this is probably true for many/all versions of GLib. I would therefore suggest to open a separate PR for this, merge that one first, and the come back to this PR. Does that make sense?

**Comment by boegel** [comment]
@geimer: maybe we should try it here first, just to confirm it fixes the issue on your end?

Making sure we have a PR to sync up all GLib easyconfigs make sense.

**Comment by boegel** [comment]
@geimer: https://github.com/geimer/easybuild-easyconfigs/pull/2

**Comment by wpoely86** [comment]
That missing `UP` symbol is pure a linkage problem. On Debian 7, I have fixed it by adding:
```
preconfigopts = " LDFLAGS='-ltinfo' "
```
to the libreadline easyconfig.

**Comment by boegel** [comment]
@wpoely86: so, we should figure out whether this breaks anything on non-Debian systems...

Can you open a WIP PR that makes that change in one of the libreadline easyconfigs, for testing purposes?

**Comment by wpoely86** [comment]
@boegel here you go: #1670

**Comment by wpoely86** [comment]
Fail: https://gist.github.com/12044bcd400b5ea69e91
Works: https://gist.github.com/5ccfed421c347cd3ecff
( with geimer/easybuild-easyconfigs#2 )

**Comment by boegel** [comment]
@geimer: #1666 is merged, which includes the fixes in https://github.com/geimer/easybuild-easyconfigs/pull/2, so just sync your branch with develop?

**Comment by geimer** [comment]
Test report by @geimer
**FAILED**
Build succeeded for 7 out of 10 (8 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/6f7bedec19de3d86e2ef for a full test report.

**Comment by boegel** [comment]
@geimer: please retry submitting a test report?

**Comment by geimer** [comment]
Test report by @geimer
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz, Python 2.7.3
See https://gist.github.com/1de82d9f67a9885df62a for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 23 out of 23 (8 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/d57e1e88f0ce74045116 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 17 out of 17 (8 easyconfigs in this PR)
Linux RHEL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/aab63229ea173e3cf94d for a full test report.

**Comment by boegel** [comment]
Going in, thanks for the effort on this @geimer, @wpoely86 for the reviewing & testing, and @jordiblasco for initiating this in #1026

**Pull request merged**
