### PR TITLE
reversion goolfc 2016.10.0 to goolfc 2016.10 + add HPL easyconfig as testcase

### PR DESCRIPTION
**Pull request by boegel**
@akesandgren please review?

### CODE REVIEW

**Comment by akesandgren** [comment]
Yeah looks good.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/806088dddd64d3651f98cc2bddd8f5f9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2062.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/054c09d434bebec6ea97638f8d542f37 for a full test report.

**Comment by boegel** [comment]
Thanks for the review @akesandgren!

**Pull request merged**
