### PR TITLE
{tools}[dummy] worker v1.5.1 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
@gjbex: please review, since you're the expert on this one?

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/b327ca6581efc6c6bdc1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/46f2261a684991f96c50 for a full test report.

**Comment by gjbex** [comment]
@boegel : looks fine, but note that the configuration file must be edited post-install, since it contains some system/site-specific stuff (path to qsub, email of local support team).

**Comment by boegel** [comment]
@gjbex: what file is that exactly?

I can include `postinstallcmds` that does that, by means of example, to make that clear

**Comment by gjbex** [comment]
@boegel : that would be conf/worker.conf

**Comment by boegel** [comment]
@gjbex: updated with `postinstallcmds`, please take a look?

**Comment by boegel** [comment]
Thanks for the feedback @gjbex!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/da576211d05f8cb83d54 for a full test report.

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
going in, thanks for the review @gjbex and @wpoely86!

**Pull request merged**
