### PR TITLE
Added GDAL-1.9.2-goolf-1.5.16 and zlib-1.2.8 dependency

### PR DESCRIPTION
**Pull request by jas02**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/22fa61b7589721b96e6a for a full test report.

**Comment by boegel** [comment]
@jas02: the GDAL build doesn't seem to be working on our end, see the test report for more details, let me know if you need any more info or if you can't figure it out

**Comment by jas02** [comment]
@boegel It is possible to try it again? I was able to build it against 2.1.0, so it should work.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/36358e9c8de9e2a621ff for a full test report.

**Comment by jas02** [comment]
@boegel It's possible to merge with level branch and close PR?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c767deea7af501ec3b2a for a full test report.

**Comment by boegel** [comment]
@jas02: thanks for the reminder, going in!

**Pull request merged**
