### PR TITLE
{bio} [dummy] IGV and IGVTools (REVIEW)

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by verdurin** [comment]
We've just had a request for this one, so we can help test, at least.

@pescobar - could you update to the latest release, 2.3.68?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/7be4ccd32eaaf647ee2e for a full test report.

**Comment by pescobar** [comment]
@verdurin I have updated both easyconfigs to latest release 2.3.68

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/1c4dbe101bd384918f84 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pescobar!

**Pull request merged**
