### PR TITLE
{tools}Singularity-2.2.1-GCC-6.3.0 added

### PR DESCRIPTION
**Pull request by foxik0070**
next steps after instalations

```console
# INSTALATION_PATH=your_instalation_path
# chown root:root $INSTALATION_PATH/Singularity/*/etc/singularity/singularity.conf
# chown root:root $INSTALATION_PATH/Singularity/*/libexec/singularity/sexec-suid
# chmod +s $INSTALATION_PATH/Singularity/*/libexec/singularity/sexec-suid
```

### CODE REVIEW

**Comment by foxik0070** [comment]
@wpoely86 @boegel I verry sorry (#4335)

**Comment by wpoely86** [comment]
Can you add those `next steps` in the easyconfig itself as comments?

**Comment by foxik0070** [comment]
it would be possible to somehow insert a provision to eb?

**Comment by wpoely86** [comment]
@foxik0070 what do you mean?

**Comment by foxik0070** [comment]
@wpoely86 postinstall script or commands for:

```console
# INSTALATION_PATH=your_instalation_path
# chown root:root $INSTALATION_PATH/Singularity/*/etc/singularity/singularity.conf
# chown root:root $INSTALATION_PATH/Singularity/*/libexec/singularity/sexec-suid
# chmod +s $INSTALATION_PATH/Singularity/*/libexec/singularity/sexec-suid
```

**Comment by wpoely86** [comment]
You have `postinstallcmds` for that but as you need `root` or sudo rights, it will probably fail. So you're probably better off by adding it in comments.

**Comment by vanzod** [comment]
I tested and it seems ok here. Any issue that prevents it from merging?

**Comment by boegel** [comment]
@vanzod Well, I guess it can go in, it's just that you need to make some manual changes afterwards...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2568.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4d5398402b8257d00efbc91c799fd418 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2017.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d198c1c8169561221c76ae205d126be3 for a full test report.

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Going in, thanks @foxik0070!

**Pull request merged**
